### PR TITLE
fix(discord): stop error replies after voice consult cancellation

### LINKED ISSUE #135340: [Bug]: Discord realtime voice reports cancelled consults as errors
### Bug type

Behavior bug (incorrect output/state without crash).

### Beta release blocker

No.

### Summary

Discord realtime voice reports an independently cancelled OpenClaw agent consult as a failure while the voice provider remains active. Forced consults can play the generic error fallback, and joined or late native tool calls lose the cancellation outcome.

### Steps to reproduce

Using the existing joined-voice fixture in `extensions/discord/src/voice/realtime-consults.test.ts`:

1. Start a synthetic `agent-proxy` or `bidi` voice session and provide a speaker context.
2. Start a native consult, or emit a final user transcript and let the forced-consult timer start the host run.
3. Keep the realtime provider active and reject the deferred host agent turn with `AbortSignal.abort().reason` or an `Error` named `AbortError`.
4. For forced consults, also exercise native calls joining before settlement and matching calls arriving afterward, with tool-result suppression both supported and unsupported.

Six injected host-cancellation cases fail on the pre-fix source. Two additional delivery-order cases reproduce premature forced playback when a second native delivery rejects while the first delivery is still pending.

### Expected behavior

Cancellation remains a terminal cancellation, consistent with the existing manually cancelled forced-consult behavior. It does not produce the generic failure fallback, and matching provider calls do not restart the work. Speaker authorization, provider-epoch isolation, successful playback handoff, and ordinary error/timeout behavior remain unchanged.

### Actual behavior

The native path submits `{ error }` and logs consult failure. The forced path can enqueue `I hit an error while checking that. Please try again.` Matching late calls receive `already_delivered` or the cached error rather than cancellation.

The failure originates in the host-rejection handling and recent-result cache in `extensions/discord/src/voice/realtime-consults.ts`; an unchanged provider epoch does not imply the host run completed normally.

### OpenClaw version

Source reproduction at `2881127d3623ac1db43c91db12b5c5fbaf28fdb2`. The implicated Discord owner is unchanged in the subsequently inspected main snapshot `1b236dfc8625cf7d89153818f1e99bdd77c9727a`.

### Operating system

macOS, Darwin 27.0.0.

### Install method

Source checkout, repository test runner.

### Model

Synthetic host agent and mocked realtime provider; no live model calls.

### Provider / routing chain

Joined Discord voice fixture → real Discord realtime session/consult coordinator/ingress → injected host-agent rejection and provider-result observation.

### Logs

Synthetic native cancellation produced `realtime consult failed call=call-native: This operation was aborted`. Forced cases requested the generic fallback speech and late-result acknowledgements described above.

### Screenshots, recordings, and evidence

Failing-before proof uses the existing Discord fixture and a colocated host-cancellation regression suite. The local repair passes all 35 consult-fixture cases and 197 combined focused/sibling cases. The forthcoming PR will include the tests and current-candidate validation.

Live Discord/phone calls, credential access, production state copies, and service restarts were explicitly excluded by the operator. This is deterministic boundary-fixture evidence, not a live Discord call or a full ephemeral-Gateway run.

### Impact and severity

Affected surface: Discord realtime voice in `agent-proxy` and `bidi` modes when an admitted host consult is cancelled independently of the voice provider. The observed consequence is misleading failure feedback and incorrect terminal tool results after cancellation. All six injected cancellation cases reproduce the defect; production frequency was not measured.

### Additional information

Related: https://github.com/openclaw/openclaw/pull/134924 — the phone host-cancellation repair landed the generic `buildRealtimeVoiceAgentErrorProviderResult` runtime helper and realtime SDK export. Discord needs its own settlement/deduplication/playback repair using that shared helper.

### PR DESCRIPTION
**Pull request by steipete**
Closes #135340

Related: #134924 (phone cancellation repair and the already-landed shared helper).

## What Problem This Solves

Fixes an issue where Discord realtime voice users hear a generic failure after OpenClaw cancels a delegated consult while the voice provider remains connected. Joined and late matching provider tool calls can also report an error or `already_delivered` instead of terminal cancellation.

## Why This Change Was Made

Discord now records one normalized host result, marks cancellation before completing the coordinator lifecycle, and uses that result for native, forced, joined, and cached consult delivery. Each outstanding native delivery owns its own settlement: one rejected attempt cannot return forced playback ownership while another attempt can still accept the answer.

The repair belongs to Discord's consult/delivery owner. It reuses the shared error projection already landed by #134924 without changing core, the SDK, or the phone/native Talk flows. It removes separate rejected-result reconstruction and the single overwritten delivery promise. No configuration, dependency, storage, schema, or protocol changes. Production +129/-151 (net -22); tests +380/-36 (net +344); docs +2.

## User Impact

Cancelled consults do not trigger Discord's generic error fallback or restart through matching late calls. The voice session stays available for the next request. Real failures and timeouts retain error handling, and successful native delivery still owns speech without duplicate forced playback. Speaker authority, provider-epoch fencing, and bounded recent-result dedupe remain intact.

## Evidence

- Before the repair, six independent host-cancellation cases and two multi-native-delivery ordering cases failed in the joined-voice fixture. The implicated Discord owner is unchanged between reproduction base `2881127d3623ac1db43c91db12b5c5fbaf28fdb2` and reconciliation base `1e93009a9659ea88ca410c13ad11842afbd8770b`.
- On candidate `4d003c7a43d29345216df22a9550a60c745a289f`, `node scripts/run-vitest.mjs extensions/discord/src/voice/realtime-consults.test.ts extensions/discord/src/voice/realtime-consults.host-cancellation.test.ts` passes all 35 cases. Coverage includes native/forced/joined/late cancellation, both suppression capabilities, rejected native delivery, success/error delivery ordering, reset/teardown, a subsequent guest request, and Error/TimeoutError controls.
- The four Discord blobs remain byte-identical to the previously reviewed candidate; the fresh full-candidate review is recorded below.
- Reconciled sibling proof passes 111 tests across 10 files, covering coordinator/control/talkback, Discord speaker turns, playback, ingress, and terminal-session cleanup (146 tests across 12 files including the consult fixtures). Both extension type lanes, formatting, doctor-contract tests, plugin/dependency boundaries, and code guards passed. The changed-file aggregate stopped before lint on unrelated protocol declaration error TS7056. After #135360 merged, this branch was rebased onto `91067e340a1811f94a3f119fae329542c3f23872`: all four changed files and the stable patch ID are unchanged. The normal extension lint wrapper, 35 consult cases, both extension type lanes, and formatting then passed on the new head. The four remaining storage/media/sidecar/import-cycle guards also passed separately. This is compositional evidence, not a claim that the original aggregate exited successfully. The original nine-file candidate had 197 focused/sibling tests and a full runtime/SDK/Control UI build pass; that build is historical evidence, not a build of this reconciled head.

**Proof limitation:** the operator explicitly prohibited live Discord/phone calls, credential retrieval, production-state copies, and service restarts. This is deterministic joined-voice boundary-fixture evidence with injected host/provider outcomes, not a live Discord call or a full ephemeral-Gateway harness. No screenshots or recordings of a live call were taken. Source inspection also confirms the old unconditional failure projection in stable tag `v2026.8.2`; no live stable-package call was made. Production frequency and the introducing commit are not established.

## Bounded ACP landing-gate repair

The original hosted CI attempt hit a 30-second ACP CLI child timeout; an unchanged-head retry passed, but a later local source run still failed both cases after dependency installation (child ETIMEDOUT and initialize-response timeout). That local run took 283.30s overall, including 177.83s of Vitest imports. These failures are retained, not waived.

An isolated source diagnostic sent initialize plus EOF immediately and observed ACP server module evaluation at 22.995s, followed by clean exit at 23.266s. This supports substantial source-loading/transform cost inside the lifecycle deadline; it is not a pure CPU benchmark or proof excluding every lifecycle defect. The maintainer reviewed the entrypoint and preparation contracts and approved this bounded test-harness repair.

Both existing cases now launch the actual `openclaw.mjs` CLI. The canonical runtime-consumer registry prepares a fresh source-matching runtime before Vitest workers, as it already does for update dry-run coverage. No custom builder, ACP production change, dependency change, timeout increase, assertion weakening, import warmup, or resource override. Both 30-second deadlines, the Vitest deadline, exit/stderr/protocol assertions, initialize-before-hello and initialize-plus-EOF-before-startup orderings, environment isolation, and cleanup are unchanged.

Observed proof:

- The added ACP prerequisite-selection case failed against the old registry: expected `runtime`, received `undefined` (5.87s wrapper). After repair, 35 selected prerequisite/routing cases passed (11.11s wrapper).
- `node scripts/run-vitest.mjs src/cli/acp-cli-exit.process.test.ts`: 2/2 pass. Early initialize+EOF: 3.306s; buffered initialize before hello: 2.189s. Test time 5.53s; Vitest 23.65s; wrapper including normal fresh build and preparation 80.97s. These are observations, not cross-host performance guarantees.
- Nine selected runner/admission/CI-plan cases passed, including failed-build and cancellation cleanup (19.69s wrapper).
- `node scripts/check-changed.mjs -- src/cli/acp-cli-exit.process.test.ts scripts/lib/vitest-build-prerequisites.mts test/scripts/test-projects.test.ts`: exit 0; formatting, core-test/scripts/root-test types, all planned guards and targeted lint passed.
- Fresh isolated Codex review of the complete nine-file candidate: scoped-clean at P0, no findings, confidence 0.95.

### Admission-suite follow-up

The first ACP registry change missed a connected negative admission case: excluding only update dry-run still left ACP selected, so a build was correctly requested and the old no-build expectation exited 91 instead of 0. The existing case failed before repair (24 other CLI-admission cases passed; wrapper 7.56s). It now excludes both runtime consumers. A new row in the existing preparation table proves that excluding only update dry-run still requires preparation for ACP, covering successful build, failure and SIGTERM without new helpers or weaker assertions.

Targeted lint also exposed 15 existing diagnostics in the touched admission file. The approved cleanup adds braces and uses a block Promise executor without returning the setImmediate handle. The startCount unused-variable diagnostic was a false positive: its value supplies a fresh ESM query identity on each CLI replay. URL construction, counter increment and import are now separate, preserving case 0,1,2 progression, increment-before-import ordering, and retained planner dependencies. No cache-busting removal, suppression or dependency change.

Final proof: node scripts/run-vitest.mjs test/scripts/test-projects-build-admission.test.ts passed all 77 tests (8.79s tests, 11.59s Vitest, 14.14s wrapper). Matching root-test tsgo, targeted oxlint, formatting and git diff --check passed. The earlier 77-case pass before lint cleanup (10.45s) and the failing lint run remain history. Earlier ACP runtime proof remains valid and was not rebuilt for this test-only follow-up. The original four Discord blobs and the prior three-file ACP patch are unchanged.

### Compact-plan expectation follow-up

The previous CI run also exposed an outdated single-runtime-job expectation in test/scripts/ci-node-test-plan.test.ts. Registering ACP correctly creates a second prepared-runtime job. The existing case failed locally before repair (15.07s wrapper). Its assertion now requires exactly two jobs and explicit ACP/update-dry-run membership at both job and group preparation levels, without depending on ordering. Runner assignments, workload/time budgets, job-count limits, concurrency and planner code are unchanged.

All 47 tests in the owning compact-plan file passed (40.70s tests, 44.28s Vitest, 48.95s wrapper), including Blacksmith, GitHub-hosted and hybrid profiles. Matching root-test types, targeted lint, formatting and diff checks passed. Fresh isolated review of the full nine-file candidate is scoped-clean at P0 with no findings, confidence 0.95.

ACP repair totals across five files: tooling +8/-6 (net +2), tests +75/-28 (net +47), total +49. Discord remains production -22, tests +344, docs +2. Entire PR: nine files, net +373. No changelog edit.

## Verified merged result

[PR #135380](https://github.com/openclaw/openclaw/pull/135380) merged via the native immediate squash route at 2026-09-01 19:27:42 UTC as [bfe2884ceab69db1442044307f6ae81d65eb7221](https://github.com/openclaw/openclaw/commit/bfe2884ceab69db1442044307f6ae81d65eb7221). The exact approved source head was `b8522bdbaa1838e344f8414def13665b3e3cb631`. [Issue #135340](https://github.com/openclaw/openclaw/issues/135340) auto-closed at 19:27:43 UTC.

Fresh native/server gates passed immediately before dispatch: exact-head hosted CI, required `openclaw/ci-gate`, current ClawSweeper review, pinned head and mergeability admission. [CI run 33545751321, attempt 1](https://github.com/openclaw/openclaw/actions/runs/33545751321) succeeded with 128 successful jobs and 16 skipped. One ancillary ClawSweeper Dispatch was cancelled; it was not a required gate. Fresh isolated full-candidate Codex review was scoped-clean at P0, no findings, confidence 0.95. ClawSweeper's wait-for-CI Rank-up move was satisfied.

`OPENCLAW_TESTBOX=1 scripts/pr prepare-run 135380` and `OPENCLAW_TESTBOX=1 scripts/pr merge-run 135380` both completed successfully. The [native provenance comment](https://github.com/openclaw/openclaw/pull/135380#issuecomment-5499253471) records prepared and landed SHAs. No admin bypass, auto-merge, queue request, rebase or candidate change was used. Native receipt and cleanup completed.

The landed tree was independently reconstructed from the actual landing parent `aaa7dd39e6430e28eadb62c603ca28b831bf7848` and the approved head, and matched exactly. All eight non-documentation blobs match the approved candidate. Discord documentation retains intervening main edits plus the intended two-line cancellation addition. The landed delta remains nine files, +594/-221: runtime -22, tests +391, tooling +2, docs +2. The squash message preserves `Closes #135340`, user behavior and the related phone helper.

Historical failures remain recorded: the original ACP source-startup timeouts, the two connected obsolete sibling expectations in [CI run 33543661288](https://github.com/openclaw/openclaw/actions/runs/33543661288), and the first native preparation attempt's transient publication-policy fetch/validation error. Documented stale-lock recovery followed by one normal preparation retry succeeded; no gate or policy was bypassed. Merge itself succeeded on its first invocation.

The operator's no-live restriction remains: proof is synthetic joined-voice boundary/process fixtures, not a live Discord/phone/provider call or full ephemeral-Gateway demonstration. No release or package publication was performed.

### CODE REVIEW

**Comment by steipete** [comment]
**Held before merge — no merge-ready signoff.** Native preparation completed, but the later local ACP diagnostic remains red. Exact head: `4d003c7a43d29345216df22a9550a60c745a289f`; branch fork base: `91067e340a1811f94a3f119fae329542c3f23872`.

Discord's consult owner previously turned host cancellation into generic failure and kept only one replaceable native-delivery promise. The repair records one normalized terminal result and retains every outstanding native settlement, removing the duplicate failure projection and preventing premature forced playback. Shared helper/SDK and phone behavior remain upstream-owned. Production net **-22**, tests **+344**, docs **+2**, exactly four files.

Local proof: 35 consult cases on this head and 111 sibling cases on the patch-identical reconciled snapshot. Six cancellation cases and two native-delivery races failed before repair. The executed commands were:

```sh
node scripts/run-vitest.mjs extensions/discord/src/voice/realtime-consults.test.ts extensions/discord/src/voice/realtime-consults.host-cancellation.test.ts
node scripts/run-vitest.mjs src/talk/forced-consult-coordinator.test.ts src/talk/agent-run-control.test.ts src/talk/agent-talkback-runtime.test.ts extensions/discord/src/voice/realtime-turns.test.ts extensions/discord/src/voice/realtime-turns.wake-name-followup.test.ts extensions/discord/src/voice/realtime-playback.test.ts extensions/discord/src/voice/realtime-playback.integration.test.ts extensions/discord/src/voice/agent-control.test.ts extensions/discord/src/voice/ingress.test.ts extensions/discord/src/voice/voice-session.terminal.test.ts
node scripts/run-oxlint.mjs --tsconfig extensions/tsconfig.json extensions/discord/src/voice/realtime-consults.ts extensions/discord/src/voice/realtime-consults.test.ts extensions/discord/src/voice/realtime-consults.host-cancellation.test.ts
node scripts/run-tsgo.mjs -p tsconfig.extensions.json --incremental --tsBuildInfoFile .artifacts/tsgo-cache/extensions.tsbuildinfo
node scripts/run-tsgo.mjs -p test/tsconfig/tsconfig.extensions.test.json --incremental --tsBuildInfoFile .artifacts/tsgo-cache/extensions-test.tsbuildinfo
node_modules/.bin/oxfmt --check docs/channels/discord.md extensions/discord/src/voice/realtime-consults.ts extensions/discord/src/voice/realtime-consults.test.ts extensions/discord/src/voice/realtime-consults.host-cancellation.test.ts
```

All listed commands passed. Remaining database-first/media/sidecar/import-cycle guards passed separately. The original changed-check aggregate did not pass: its unrelated declaration-build failure was repaired upstream by merged #135360; after rebasing onto that fix, the normal lint wrapper, fixtures, both type lanes and formatter passed. This is compositional evidence; the historical seven-file full build is not claimed for this head. Fresh isolated Codex review: scoped-clean at P0, no findings, confidence 0.97.

Hosted [CI run 33536706262](https://github.com/openclaw/openclaw/actions/runs/33536706262) attempt 2 and [Workflow Sanity 33536668512](https://github.com/openclaw/openclaw/actions/runs/33536668512) completed successfully on the exact head. The first CI attempt hit a 30-second child-process timeout in the unchanged ACP CLI test; one diagnostic rerun of that failed shard and its dependent gate passed, without changing source, assertions, timeouts or resources. The repository watcher ended `SUCCESS pending=0`, exit 0.

`OPENCLAW_TESTBOX=1 scripts/pr prepare-run 135380` completed with exit 0. Its hosted-gate report selected **exact-head** evidence and verified the remote PR tree equals the local prepared tree; no rebase or push was needed. The three named Blacksmith Testbox workflows were classified not applicable, not claimed as executed. Live rules require `openclaw/ci-gate` and linear history, with no enforced independent approval rule. No bypass was used.

**Proof gap / review disposition:** live Discord/phone/provider calls, credential retrieval, production-state copies and service restarts were explicitly prohibited. The joined-voice boundary fixtures are not a live call or a full ephemeral-Gateway harness. The latest published ClawSweeper comment is only an acknowledgement, with no Rank-up moves available; any later actionable review remains for the maintainer to evaluate before merge. The PR description retains this gap. Held before merge for maintainer disposition of the unresolved ACP diagnostic; any later merge still requires explicit exact-head approval.

**Subsequent local blocker:** after `pnpm install --frozen-lockfile` completed without tracked changes, `node scripts/run-vitest.mjs src/cli/acp-cli-exit.process.test.ts` failed 2/2 cases: the disconnect child hit `ETIMEDOUT`, and the buffered-initialize case hit its response timeout, both at 30 seconds. The wrapper ran for 283.30 seconds, with 177.83 seconds spent importing the test. Cause is not established; the ACP files, entry point and timeouts are unchanged by this PR. The native review recommendation is now `NEEDS DISCUSSION`, superseding the earlier prepare-ready recommendation. No additional retry or out-of-scope repair was made. The PR description has this evidence and hold state.

**Comment by steipete** [comment]
Merged via squash.

- Prepared head SHA: [b8522bdbaa1838e344f8414def13665b3e3cb631](https://github.com/openclaw/openclaw/pull/135380/commits/b8522bdbaa1838e344f8414def13665b3e3cb631)
- Landed commit: [bfe2884ceab69db1442044307f6ae81d65eb7221](https://github.com/openclaw/openclaw/commit/bfe2884ceab69db1442044307f6ae81d65eb7221)
