### ISSUE TITLE
[Bug]: Gateway crashes on startup after upgrade to 2026.2.6-3 — listFeishuAccountIds is not a function

### ISSUE THREAD

**Issue by shi557636shi** [openclaw/openclaw#12741]
## Bug Description

After upgrading from `2026.2.3-1` to `2026.2.6-3`, the Gateway crashes immediately on startup with:

```
TypeError: (0 , _pluginSdk.listFeishuAccountIds) is not a function
```

## Steps to Reproduce

1. Running OpenClaw `2026.2.3-1` with Feishu channel configured in `openclaw.json`
2. Upgrade to `2026.2.6-3` via `npx openclaw@2026.2.6-3 gateway`
3. Gateway crashes on startup

## Expected Behavior

Gateway should start normally after upgrade.

## Actual Behavior

Gateway crashes with `listFeishuAccountIds is not a function`. 

The root cause appears to be that `listFeishuAccountIds` was moved from `dist/plugin-sdk/index.js` to `extensions/feishu/src/accounts.ts` during the refactor, but the gateway health check (or feishu extension compiled via jiti) still references the old `plugin-sdk` export location.

## Attempted Workarounds (all failed)

1. **Removing `plugins.entries.feishu` from config** — New version auto-restores it on startup
2. **Patching plugin-sdk with the missing export** — ESM module loading doesn't pick up appended exports
3. **Clearing npx cache and reinstalling** — Same error

## Workaround

Rolled back to `2026.2.3-1`. Gateway runs fine on old version.

## Environment

- **OS**: macOS 15.5 (Darwin 24.6.0, Apple Silicon)
- **Node.js**: v22.x
- **OpenClaw version**: 2026.2.6-3 (fails) / 2026.2.3-1 (works)
- **Install method**: npx

## Config (redacted)

```json
{
  "channels": {
    "feishu": {
      "appId": "cli_***",
      "appSecret": "***",
      "dmPolicy": "open",
      "allowFrom": ["*"]
    }
  },
  "plugins": {
    "entries": {
      "feishu": { "enabled": true }
    }
  }
}
```

## Related Issues

- #8958 — Feishu Plugin Configuration Conflict After Upgrade (duplicate plugin id)
- #11830 — Feishu streaming cards not working
- #11268 — 2026.2.6-3 config corruption (different bug, same version)
