### ISSUE TITLE
[Bug]: sticky model fixtures fail core test typecheck

### ISSUE THREAD

**Issue by steipete** [openclaw/openclaw#130440]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

The core test typecheck fails on the sticky-model Gateway fixture introduced by #127813, blocking CI for changes that include current main.

### Steps to reproduce

1. Check out main at `54db7d4f99e8286fa26367151db3f3a34fbe08b0`.
2. Run `node scripts/run-tsgo.mjs -b test/tsconfig/tsconfig.core.test.gateway-other.json --builders 1`.
3. Observe TS2540 at `src/gateway/server-methods/sessions-mutations.sticky-model.test.ts:216` and `:245`.

### Expected behavior

The agent fixtures use the mutable `AgentConfig` contract so the expected configuration can include a model for either agent.

### Actual behavior

Both assignments to `agent.model` fail with `Cannot assign to 'model' because it is a read-only property`. The inferred heterogeneous fixture list is narrower than `AgentConfig[]`; checking the outer object with `satisfies OpenClawConfig` does not give the list that domain type.

### OpenClaw version

Main `54db7d4f99e8286fa26367151db3f3a34fbe08b0`; introduced by `ce4a680544a3502f98d3c9dc49ab9b9e77e7c43b` (#127813).

### Operating system

GitHub Actions Linux; also reproduced locally on macOS.

### Install method

Source checkout and CI dependency installation.

### Model

Not applicable: this is a test fixture typecheck failure, not a provider call.

### Provider / routing chain

Not applicable.

### Logs

```text
src/gateway/server-methods/sessions-mutations.sticky-model.test.ts(216,17): error TS2540: Cannot assign to 'model' because it is a read-only property.
src/gateway/server-methods/sessions-mutations.sticky-model.test.ts(245,17): error TS2540: Cannot assign to 'model' because it is a read-only property.
```

### Screenshots, recordings, and evidence

[Failed CI job](https://github.com/openclaw/openclaw/actions/runs/33015906921/job/98334846725). The same two diagnostics reproduce in the owning native typecheck shard before the repair.

### Impact and severity

Blocks core test-type CI and therefore unrelated PR landing. No production runtime behavior change or user data loss is demonstrated.

### Additional information

Maintainer-directed broken-main repair. A focused fix types the fixture's agent-list producer as `AgentConfig[]`, retaining all existing value assertions and changing no runtime code, dependency, or typecheck configuration.
