### PR TITLE
fix: stale subagent completions are no longer delivered into a replaced requester lifecycle

### LINKED ISSUE #118018: [Bug]: Stale subagent completion can be delivered into a replaced requester lifecycle
## Bug type

Behavior/lifecycle bug: a completion can be delivered to the wrong requester lifecycle and then
settled without a crash or an actionable remaining obligation.

## Summary

A persisted subagent requester-settle wake identifies the requester session, but it does not record
the requester lifecycle revision that accepted the child handoff.

If the parent session is reset or replaced while retaining the same session identity, a completion
from the old lifecycle can be dispatched into the replacement lifecycle. The old batch can then be
marked complete and its wake cleared even though the replacement lifecycle never accepted that
work.

From the operator's perspective, delegated work can therefore appear to vanish, complete in the
wrong conversation lifecycle, or leave no truthful status explaining what happened.

## Affected baseline

- OpenClaw `v2026.7.2-beta.7`
- Current source retains the same target-lifecycle contract gap.
- The defect is transport- and provider-independent.

Relevant owner seams include:

- [`src/agents/subagent-registry.ts`](https://github.com/openclaw/openclaw/blob/v2026.7.2-beta.7/src/agents/subagent-registry.ts)
- [`src/config/sessions/session-accessor.sqlite-lifecycle.ts`](https://github.com/openclaw/openclaw/blob/v2026.7.2-beta.7/src/config/sessions/session-accessor.sqlite-lifecycle.ts)
- [`src/gateway/session-reset-service.ts`](https://github.com/openclaw/openclaw/blob/v2026.7.2-beta.7/src/gateway/session-reset-service.ts)

## Deterministic source-backed reproduction

1. Create parent session `agent:main:main` with `sessionId=sess-main` and
   `lifecycleRevision=revision-1`.
2. Have that lifecycle admit a subagent handoff and persist its requester-settle wake.
3. Before the subagent completes, reset or replace the parent so the same session identity now has
   `lifecycleRevision=revision-2`.
4. Let the old subagent complete and run the normal requester-settle dispatch.

### Actual behavior

- The current requester is resolved by session identity.
- The old completion can be dispatched into `revision-2`.
- The old batch can be marked complete.
- The requester-settle wake can be cleared.
- No remaining owner state necessarily explains that the completion belonged to `revision-1`.

### Expected behavior

- The lifecycle revision captured when the handoff was admitted must be validated immediately
  before completion dispatch.
- A matching lifecycle may receive the completion exactly once.
- A missing or mismatched lifecycle must not receive the stale completion.
- A mismatch must not be marked delivered, completed, or cleared as if settlement succeeded.
- The retained state must expose a bounded reason and next safe action through an existing status or
  diagnostic projection.

## Root cause

The subagent owner persists child occurrence identity and requester session identity. The session
owner separately knows the current requester lifecycle revision. The handoff does not persist the
expected target lifecycle revision needed to prove that the current requester is still authorized
to consume the completion.

Session identity answers **where** to route. It does not answer **which lifecycle** accepted the
work.

OpenClaw already uses lifecycle-revision validation in session-owner paths. The missing authority
fact is the requester lifecycle revision captured at subagent handoff admission.

## Suggested owner-local fix boundary

1. Capture the requester lifecycle revision when the subagent handoff is admitted.
2. Persist it as a typed field, such as `expectedRequesterLifecycleRevision`, with the existing
   requester-settle state.
3. Ask the canonical session owner to validate that value immediately before dispatch.
4. On mismatch, do not dispatch, mark delivered, complete the batch, or clear the wake. Retain an
   explicit state such as `requester_replaced` / `target_lifecycle_mismatch` that is queryable
   through an existing bounded projection.
5. Keep exact duplicate settlement idempotent.
6. For legacy persisted rows without the authority fact, do not invent a revision or deliver solely
   because the session key matches. Treat them as `legacy_unfenced` / uncertain unless continuity
   can be proven by the existing owner.

This should remain an owner-local protocol repair. It should not add a shared persistence
framework, generic recovery worker, global mode, or broad inspection API.

## Acceptance criteria

- [ ] An unchanged requester lifecycle receives the completion exactly once.
- [ ] The same session identity with a replaced lifecycle receives no stale completion.
- [ ] A lifecycle mismatch remains explicit and queryable instead of being cleared as successful.
- [ ] Restart between persisted wake admission and dispatch revalidates the target lifecycle.
- [ ] An exact duplicate completion is idempotent.
- [ ] A missing requester produces an explicit bounded state rather than silent settlement.
- [ ] Legacy rows without a requester lifecycle revision fail closed unless continuity is proven.
- [ ] A storage failure before durable admission cannot produce accepted/success framing.
- [ ] Tests keep `sessionId` constant while changing `lifecycleRevision`, so session-key-only routing
      cannot pass accidentally.
- [ ] The implementation adds no new central runtime, generic worker, or recovery topology.

## Related work and scope boundary

- #117412 concerns source-side subagent restart recovery and run-generation fencing. This issue is
  limited to target-side requester lifecycle validation and must work independently of that
  topology.
- #92433 concerns whether queued completion was actually consumed and which yielded run owns the
  delivery outcome. This issue asks the earlier authorization question: whether this requester
  lifecycle may receive the completion at all.

Not in scope: provider idle/liveness watchdogs, timeout presentation, interactive question
delivery, compaction behavior, generic task replay, or arbitrary external side-effect recovery.

## Impact

This affects delegated work that completes across a parent reset or lifecycle replacement. It can
cause stale output to enter a new lifecycle or make an accepted completion disappear from the
operator's actionable state. Stronger models and longer context windows do not remove this
lifecycle race.

## Do you plan to open a PR for this?

Yes, after maintainers confirm the owner-local contract boundary. The intended implementation is
one focused PR containing the persisted authority field, pre-dispatch validation, explicit mismatch
projection, legacy behavior, and deterministic reset/restart tests.

### PR DESCRIPTION
**Pull request by Yuxin-Qiao**
Closes #118018

## What Problem This Solves

Fixes an issue where a parent conversation that was reset or replaced while a subagent was still running could receive the old subagent's completion in the replacement lifecycle. The stale completion was then marked as settled even though the new lifecycle never accepted the work, so delegated work could appear in the wrong conversation or vanish without a truthful terminal state.

## Why This Change Was Made

The requester-settle wake persisted only the requester session key, and dispatch resolved the requester by session identity alone. Session identity answers where to route; it does not answer which lifecycle accepted the handoff. After a reset, the same session key points at a new `lifecycleRevision`, so session-key-only routing can deliver into the replacement lifecycle.

## What This Change Does

- Captures `expectedRequesterLifecycleRevision` at subagent handoff admission (register and steer replacement paths) and persists it with the run record (new `subagent_runs.expected_requester_lifecycle_revision` column).
- Validates every member of the wake batch against the current requester lifecycle revision immediately before dispatch; members whose captured revision differs are retained with an explicit `requester_replaced` outcome, and only matching members are delivered.
- A missing revision on both sides means the session was never reset, so the initial lifecycle still matches and delivery proceeds; a reset always introduces a revision, so stale completions are fenced.
- Adds `requester_settle_wake_lifecycle_mismatch` for the retained outcome; no new central runtime or recovery worker.

## Maintainer review follow-up

Addressed the four points from the issue discussion:

1. **Admission-boundary capture**: the requester lifecycle revision is now captured by the spawn pipeline before async child dispatch (`captureExpectedRequesterLifecycle`) and passed through registration as a typed parameter, so a reset between child acceptance and registration cannot re-tag the admission with the replacement lifecycle. `spawn-pipeline.test.ts` covers the exact interval (capture order + reset-during-dispatch regression).
2. **Operator-visible retention**: the subagent list/status projection now surfaces `requester_replaced` / `requester_missing` as `retained: <reason>` in the status and exposes the bounded reason via `retentionReason`, so the retained outcome is no longer unexplained silence.
3. **Deterministic E2E latch**: the child-release gate is now a one-shot deferred that resolves the promise the request handler is actually awaiting.
4. **Legacy/upgrade proof**: a repair-fixture test drops the two pre-column columns, runs the doctor repair path, confirms the columns are restored additively, and verifies pre-upgrade rows read back with no captured revision; `sessions.reset` stamps a fresh lifecycle revision for both `new` and `reset` (existing reset + fork stamping coverage cited).

Follow-up round (rebase + Gateway path):

5. **Gateway plugin-subagent admissions**: `registerPluginSubagentRunFromGateway` now stamps the requester lifecycle revision at the Gateway admission boundary, so requester-bound plugin runs are fenced identically to native/ACP spawns; the existing requester-lineage test gained a reset-after-registration regression (`agent.sessions-and-models.test-utils.ts`).
6. **Rebase**: the branch was rebased onto current main (the spawn pipeline now wraps admission reservations); GitHub reports the head as MERGEABLE.

## User Impact

Operators no longer see stale subagent output delivered into a replacement conversation lifecycle, and a fenced completion stays visible as a retained mismatch with an explicit reason instead of silently disappearing.

### Real-runtime proof

New `test/subagent-requester-lifecycle.e2e.test.ts` starts a real gateway process with a scripted OpenAI-compatible provider, drives a real `sessions_spawn` + `sessions.reset` + child completion through the actual agent runtime, and reads the persisted registry/session state.

Run: `node scripts/run-vitest.mjs test/subagent-requester-lifecycle.e2e.test.ts` -> 2 passed.

Replaced lifecycle (reset between handoff admission and child completion):

```json
{
  "parentLifecycleRevision": "bab3d152-3529-4ff5-9760-6550c52828a8",
  "wakeRequestCount": 0,
  "runs": [{
    "runId": "3851f2ce-2ca5-4cc5-8736-9676e458476c",
    "taskName": "proof_child",
    "wakeStatus": "pending",
    "lifecycleMismatch": "requester_replaced",
    "deliveryStatus": "suspended",
    "lastError": "requester_replaced: requester lifecycle was replaced before the subagent completion settled; stale completion retained without delivery (requester=agent:main:proof-51a66447)",
    "endedAt": 1785705356498,
    "payloadPresent": true
  }]
}
```

No delivery happened (`deliveredAt`/`announcedAt` absent, no wake model request), and the stale completion is retained with an explicit `requester_replaced` outcome.

Unchanged lifecycle (control):

```json
{
  "wakeRequestCount": 0,
  "runs": [{
    "runId": "b6034686-dc49-4b50-9e8c-b06865239ab4",
    "taskName": "proof_child",
    "deliveryStatus": "pending",
    "endedAt": 1785705398637,
    "payloadPresent": true
  }]
}
```

The completion is not fenced (no mismatch, not suspended) and stays queued for the requester's next turn; a prior control run also observed the completion delivered (`deliveredAt`/`announcedAt` set) through the requester-turn steering path.

### Focused regression tests

- replaced lifecycle (same `sessionId`, new `lifecycleRevision`) -> no delivery, no completion, `requester_replaced` retained; later drains do not retry
- mixed batch in both orderings -> stale members fenced, only matching members delivered
- initial lifecycle without a persisted revision -> delivered exactly once
- missing requester entry -> `requester_missing` retained instead of silent settlement
- yield re-admission preserves the fence; SQLite round-trip for both new columns

### Local validation

- `node scripts/run-vitest.mjs src/agents/subagent-announce.requester-settle-wake.test.ts src/agents/subagent-registry-requester-yield.test.ts src/agents/subagent-registry.store.sqlite.test.ts src/agents/subagent-requester-lifecycle.test.ts src/agents/subagent-registry.test.ts` -> 203 passed
- `node scripts/run-vitest.mjs src/gateway/server-methods/agent.test.ts` -> 268 passed (includes the Gateway admission stamp regression)
- `pnpm tsgo:core`, `pnpm tsgo:core:test` -> clean
- `pnpm tsgo:test:root` -> clean (e2e proof file typechecked)
- `pnpm check:import-cycles` -> 0 cycles
- production knip scan -> clean
- `git diff --check` -> clean

### CODE REVIEW

**Comment by Yuxin-Qiao** [comment]
Rebased onto current `main` and completed the lifecycle-fence repair at exact head `935106ef25e0ba687e19817cf2bd0bc12378c0dc`.

Repair and proof:
- Preserve an explicit initial no-revision expectation through internal dispatch and final Gateway admission; an undefined-to-reset transition now rejects the stale wake and retains `requester_replaced`.
- Added deterministic final-admission and settle-wake regressions, including mixed lifecycle batches and legacy undefined rows.
- Removed redundant lifecycle schema columns; `payload_json` remains the canonical registry state.
- Real Gateway E2E now uses `sessions_yield` and records the retained fence. Redacted output:
  ```
  [proof:fenced] {"wakeRequestCount":1,"runs":[{"wakeStatus":"pending","lifecycleMismatch":"requester_replaced","deliveryStatus":"pending","payloadPresent":false}]}
  [proof:control] {"wakeRequestCount":1,"runs":[{"deliveryStatus":"delivered","deliveredAt":"<redacted>","announcedAt":"<redacted>","payloadPresent":false}]}
  ```
  The fenced run has no `deliveredAt`/ `announcedAt`; the unchanged control delivers normally.

Latest local proof:
- `pnpm tsgo:core`
- `pnpm tsgo:core:test`
- `pnpm db:kysely:check`
- focused gateway/agent/registry/spawn Vitest suites
- `OPENCLAW_E2E_SKIP_BUILD=1 node scripts/run-vitest.mjs test/subagent-requester-lifecycle.e2e.test.ts` (2/2)
- targeted Oxlint and `git diff --check`

@clawsweeper re-review

**Comment by Yuxin-Qiao** [comment]
Follow-up repair at exact head `20de43b62c8e3cd87ffca52d5f5d1e63495db179`.

ClawSweeper's recovery finding is fixed: steer/recovery successors now inherit `source.expectedRequesterLifecycleRevision` instead of rereading the requester session after a reset. Added a reset-before-recovery regression; the source revision remains attached to the successor.

Validation:
- `node scripts/run-vitest.mjs src/agents/subagents/registry/subagent-registry.steer-restart.test.ts` (28/28)
- `node scripts/run-vitest.mjs src/agents/subagents/registry/subagent-registry-restart-recovery.test.ts` (29/29)
- `pnpm tsgo:core`
- targeted Oxlint and `git diff --check`
- prior exact-head Gateway E2E: fenced row retained `lifecycleMismatch=requester_replaced`, `deliveryStatus=pending`, no delivery timestamps; unchanged control delivered normally.

@clawsweeper re-review

**Comment by Yuxin-Qiao** [comment]
Final-admission lifecycle repair pushed at exact head `2179347eb546c5754b5e21dcdf30c8c51106de6c`.

The initial lifecycle is now explicit end-to-end: `null` means “captured before any lifecycle revision existed”; it is persisted on new completion-bearing rows, forwarded through direct/plugin dispatch, carried into Gateway preflight, and asserted as `entry.lifecycleRevision ?? null`. A reset-created UUID therefore fails final admission even when the original captured revision was absent. Legacy rows that omitted the field keep their old undefined-to-undefined behavior.

Added the deterministic Gateway regression for initial/no-revision -> reset before final admission. Recovery successors also preserve the source admission lifecycle.

Latest proof:
- `pnpm tsgo:core` and `pnpm tsgo:core:test`
- gateway suite: 286 passed
- lifecycle/settle-wake/spawn/recovery suites: 143 + 29 passed
- real Gateway E2E: 2/2 passed; fenced output retains `requester_replaced` with pending delivery and no delivery timestamps; control delivers normally
- targeted Oxlint, DB check, and `git diff --check`

@clawsweeper re-review

**Comment by Yuxin-Qiao** [comment]
Follow-up at exact head `3407faf05967f0e11df862bab7c3827ad942d189`: fixed the next final-admission edge found by review. A lifecycle-constrained admission now requires a live requester entry; an absent entry no longer normalizes to the initial lifecycle. Added the missing-requester regression alongside the initial-null -> reset regression.

Validation:
- gateway agent suite: 287 passed
- `pnpm tsgo:core`
- prior `pnpm tsgo:core:test`, focused lifecycle/recovery suites, and real Gateway E2E remain green on the unchanged surrounding code
- targeted Oxlint and `git diff --check`

@clawsweeper re-review

**Comment by Yuxin-Qiao** [comment]
Follow-up repair pushed at exact head `75992cd08`.

The late direct-delivery finding is fixed:

- ordinary completion cleanup now threads the persisted `expectedRequesterLifecycleRevision` into `deliverSubagentAnnouncement`;
- direct delivery rejects a missing/replaced requester lifecycle before dispatch, while the final Gateway admission check remains the race-safe last guard;
- `requester_replaced` / `requester_missing` is retained in the delivery state and surfaced by the existing subagent list projection;
- the prior delivery error is preserved instead of being overwritten by the generic retry message.

Proof:

- real Gateway lifecycle E2E: 3/3, including a no-`sessions_yield` reset race;
- focused announce/direct-delivery/list/SQLite suites: 208 passed;
- lifecycle/settle-wake/recovery suites: 233 + 29 passed;
- Gateway agent suite: 287 passed;
- `pnpm tsgo:core`, `pnpm tsgo:core:test`, DB/Kysely check, targeted Oxlint, SDK surface, max-lines, and `git diff --check` passed;
- autoreview clean; TruffleHog clean.

The terminal E2E evidence is redacted in the PR context. I am not claiming the separate sanitized Control UI recording until it exists.

@clawsweeper re-review

**Comment by Yuxin-Qiao** [comment]
Follow-up at exact head `530da72e4`: fixed the fixed-store/global requester-owner gap found in review.

The lifecycle admission lookup now shares the canonical requester owner resolver with completion delivery. Unscoped `global` keys therefore honor the persisted fixed-store owner instead of falling back to the default agent; retired/conflicting owners fail closed. Added regression coverage for a fixed owner different from the default and kept the direct completion fence unchanged.

Validation after this fix:

- fixed-owner/lifecycle owner tests: 8 passed;
- focused announce/list/SQLite/Gateway suites: 373 passed plus Gateway 287 passed;
- real Gateway lifecycle E2E: 3/3 passed;
- `pnpm tsgo:core` and `pnpm tsgo:core:test` passed;
- targeted Oxlint, max-lines, DB/Kysely, SDK surface, and `git diff --check` passed;
- autoreview clean; TruffleHog clean.

@clawsweeper re-review
