### ISSUE TITLE
[Bug]: outLog.debug is not a function — 9.5 Delivery adapter regression breaks pre-V2 SDK plugins

### ISSUE THREAD

**Issue by gaodaabao** [openclaw/openclaw#153029]
### Bug type
Regression (worked in 2026.9.3, fails in 2026.9.5)

### Summary
The 2026.9.5 Delivery adapter calls `outLog.debug(...)` unconditionally on the
plugin logger object, but plugins built on the pre-Gateway-V2 SDK
(e.g. openclaw-qqbot 2.0.3) do not expose a `.debug` method. Result: all
proactive delivery (cron announcements + message tool sends) throws
`outLog.debug is not a function` and fails. Interactive inbound replies still
work because they do not go through the Delivery adapter.

### Steps to reproduce
1. Upgrade OpenClaw from 2026.9.3 to 2026.9.5
2. With `openclaw-qqbot` 2.0.3 (pre-V2 SDK) enabled
3. Wait for any scheduled cron with `delivery.mode=announce` to fire, or call
   the `message` tool with `action=send`

### Expected
Delivery succeeds; scheduled announcements reach the channel.

### Actual
Both paths fail with identical error:
```
[cron:bb26ce47...] delivery failed (required): outLog.debug is not a function
[cron:c6f957cb...] delivery failed (required): outLog.debug is not a function
[tools] message failed: outLog.debug is not a function  raw_params={"action":"send","channel":"qqbot",...}
```

### Why interactive replies still work
The inbound response path (chat reply) is independent of the Delivery
adapter, so direct chat answers go through. Anything that uses the Delivery
adapter — scheduled announcements and proactive `message` tool sends,
including group/guild targets — fails.

### Affected scope
- All plugins on the pre-Gateway-V2 SDK (confirmed `openclaw-qqbot` 2.0.3;
  likely any other plugin not yet migrated)
- Both cron announce and `message` tool `action=send`
- Both `c2c` (direct) and group/guild targets
- Workaround for users right now: none on the OpenClaw side. Users with cron
  jobs that deliver announcements must disable announce delivery until a fix
  ships, or accept failed-delivery noise.

### Suggested fix
Make the Delivery adapter call defensive:
```js
if (typeof outLog?.debug === 'function') outLog.debug(...);
else if (typeof outLog?.info === 'function') outLog.info(...);
```
This preserves backward compatibility at zero cost and avoids forcing every
plugin to immediately migrate to the V2 SDK to keep working.

### Environment
OpenClaw 2026.9.5 (ec9c1a1) · openclaw-qqbot 2.0.3 · Linux x64 ·
Node 24.18.0 · npm 11.18.0

### Related
This is one of several 9.5 regressions reported today; similar pattern to
the update-failure cluster (#144712, #145954, #146394).
