### ISSUE TITLE
Windows native: Health check fails with ERR_MODULE_NOT_FOUND for task-registry.maintenance

### ISSUE THREAD

**Issue by JIRBOY** [openclaw/openclaw#84796]
**Describe the bug**
When running OpenClaw 2026.5.19 on native Windows, health check fails with the following error:

```
Health check failed: Error: Cannot find module 'D:\Personal\Roaming\npm\node_modules\openclaw\dist\task-registry.maintenance-B-jsfe-3.js' imported from D:\Personal\Roaming\npm\node_modules\openclaw\dist\status.summary-CZND_jzu.js: code=ERR_MODULE_NOT_FOUND
```

**To Reproduce**
1. Install OpenClaw 2026.5.19 on native Windows via npm
2. Run `openclaw status` or trigger health check
3. See the ERR_MODULE_NOT_FOUND error

**Expected behavior**
All required modules should be present in the npm package distribution.

**Environment:**
 - OS: Windows 10/11 (native, not WSL2)
 - OpenClaw version: 2026.5.19
 - Installation method: npm install -g openclaw

**Root Cause Analysis**
The `task-registry.maintenance.ts` module is dynamically imported via `createLazyImportLoader` in:
- `src/commands/status.summary.ts:24`
- `src/gateway/server-startup-early.ts:112`
- `src/gateway/server.impl.ts:422`

The build system (tsdown/rollup) creates code-split chunks with hashed filenames for dynamically imported modules. However, it appears that:
1. Either the chunk file `task-registry.maintenance-B-jsfe-3.js` was not generated during the build
2. Or the chunk file was not included in the published npm package

**Additional context**
This issue was discovered when upgrading from 5.12 to 5.19 on native Windows.

Related observation: The `tsdown.config.ts` has a section for runtime entries with stable filenames, but `task-registry.maintenance` is not listed there. It's treated as a dynamic import and gets a hashed chunk filename.
