### ISSUE TITLE
[Bug]: Discord channel crash loop after upgrade to v2026.5.6

### ISSUE THREAD

**Issue by akessel56** [openclaw/openclaw#78643]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

After upgrading, Discord bot goes into a crash loop — shows "is typing..." briefly then disappears with no response. All Discord channels affected. Other channels (WebChat) work fine.
The separately-installed @openclaw/discord plugin (v2026.5.6) ships module files with different content hashes than what the OpenClaw v2026.5.6 core expects. Specifically:
Cannot find module '.../dist/extensions/discord/manager.runtime-DZtenh59.js'
imported from '.../dist/extensions/discord/provider-Bc1Lm79N.js'
The installed plugin has manager.runtime-B0TEyget.js but core references manager.runtime-DZtenh59.js — hash mismatch between core and plugin package.

Additional missing modules in v2026.5.6 core:

pi-model-discovery-runtime.js (model catalog fails to load)
session-archive.runtime-DHboV7a2.js (cron reaper fails every 60s)

### Steps to reproduce

Upgrading from 4.23 to 5.6 using:
pkill -9 -f openclaw 
rm -f ~/.openclaw/gateway.lock
curl -fsSL https://openclaw.ai/install.sh | bash -s -- --no-onboard

### Expected behavior

Discord messaging should work fine

### Actual behavior

After upgrading, Discord bot goes into a crash loop — shows "is typing..." briefly then disappears with no response. All Discord channels affected. Other channels (WebChat) work fine.

### OpenClaw version

2026.5.6

### Operating system

RPi 5, ARM64, OpenClaw v2026.5.6 (upgraded from v2026.4.23)

### Install method

pkill -9 -f openclaw  rm -f ~/.openclaw/gateway.lock curl -fsSL https://openclaw.ai/install.sh | bash -s -- --no-onboard

### Model

glm-5

### Provider / routing chain

openclaw > glm-5

### Logs, screenshots, and evidence

```shell
Key finding: The @openclaw/discord npm plugin persists in ~/.openclaw/npm/node_modules/ even after rolling back the core via npm install -g. The version mismatch between old core and new plugin causes the same crash. Both must be reverted together.
```

### Impact and severity

Affected Discord not working in 2026.5.6
Severity: was able to roll back to 4.23

### Additional information

roll back method:
npm install -g openclaw@2026.4.23
openclaw plugins uninstall discord
openclaw gateway restart
