### ISSUE TITLE
[Bug]: 2026.6.1 — plugin install index + task registry/flow sidecar migrations fail with "statement.columns is not a function" after upgrade from 2026.5.7

### ISSUE THREAD

**Issue by TreyLawrence** [openclaw/openclaw#90007]
## Description

After upgrading from 2026.5.7 to 2026.6.1 via `openclaw update --yes`, the
post-update `openclaw doctor` step fails. The npm install + global swap succeed;
the doctor verification fails; the gateway is restarted but plugin/task state
stores are broken. The same `TypeError: statement.columns is not a function`
appears across three independent state migrations.

## Environment

- OS: macOS 25.3.0 (Darwin, arm64)
- Node: v23.9.0
- Install method: npm global
- Previous version: 2026.5.7
- Target version: 2026.6.1 (latest tag — just promoted from beta)

## Steps to reproduce

1. Have `openclaw@2026.5.7` installed globally with state in `~/.openclaw/`
2. Run `openclaw backup create`
3. Run `openclaw update --dry-run` (planned actions look normal)
4. Run `openclaw update --yes`

## Actual

```
Update Result: ERROR
  Before: 2026.5.7
  After:  2026.6.1
  Steps:
    ✓ global update (7.09s)
    ✓ global install swap (1.95s)
    ✗ openclaw doctor (2.24s)
        PluginStateStoreError: Failed to open the plugin state database.
```

`openclaw plugins doctor` shows the underlying cause:

```
- Failed migrating plugin install index /Users/<user>/.openclaw/plugins/installs.json:
  TypeError: statement.columns is not a function
- Failed migrating task registry sidecar /Users/<user>/.openclaw/tasks/runs.sqlite:
  TypeError: statement.columns is not a function
- Failed migrating task flow sidecar /Users/<user>/.openclaw/flows/registry.sqlite:
  TypeError: statement.columns is not a function
```

## Workaround

Downgrade to 2026.5.28 — migrations from 2026.5.7 → 2026.5.28 succeed cleanly.

```
npm install -g openclaw@2026.5.28
```

## Possible cause

`statement.columns()` is a method on `node:sqlite` prepared statements
(Node 22.16+/23.x). Node 23.9.0 should have it, so either:

1. The 2026.6.1 migration code is calling `.columns()` against a non-`node:sqlite`
   library (e.g. better-sqlite3 with a different API shape), or
2. The migration code in 2026.6.1 has a regression vs. 2026.5.28.

Happy to provide more logs or test a patch.

**Comment by Countermarch** [comment]
Additional `2026.6.1` evidence for the plugin install index/shared SQLite migration path, from an upgrade where the migration did not throw `statement.columns is not a function` but still left doctor in a non-clearable legacy-state warning.

## Environment

- OpenClaw: `2026.6.1 (2e08f0f)`
- Install path: npm global package update via `npm install -g openclaw@2026.6.1`
- Previous stable runtime: `2026.5.28`
- Gateway remained healthy after restart

## Observed behavior

After the package update and gateway restart, `openclaw doctor --lint --json` reports:

```json
{
  "checkId": "core/doctor/legacy-state",
  "severity": "warning",
  "message": "Plugin install index: <stateDir>/plugins/installs.json → shared SQLite state",
  "fixHint": "Run `openclaw doctor --fix` to migrate legacy state."
}
```

Gateway startup/health commands also print:

```text
Left plugin install index in place because shared SQLite state has conflicting plugin install metadata for: brave, codex
```

The suggested fix path does not clear the warning:

```text
openclaw doctor --fix --json
```

returned exit code `2` with:

```text
doctor lint options require --lint. Use `openclaw doctor --lint ...`.
```

Then:

```text
openclaw doctor --lint --fix --json
```

returned exit code `1` and still reported the same `core/doctor/legacy-state` warning.

## Why this seems related

The original issue covers `2026.6.1` plugin install index migration into shared SQLite failing during upgrade. This is a second failure mode in the same migration/doctor surface:

- migration detects conflicting global plugin install metadata for `brave` and `codex`;
- it leaves the legacy `plugins/installs.json` in place;
- doctor remains `ok: false` with a fix hint;
- the hinted fix command either needs different lint flags or does not resolve/report the conflict after those flags are supplied.

Expected behavior: when the legacy plugin index cannot be safely migrated because shared SQLite state has conflicting plugin metadata, doctor should either clear the warning after a safe migration or report the exact manual/conflict-resolution step instead of leaving a non-clearing `Run openclaw doctor --fix` hint.

## Additional verification

- Gateway health after restart remained OK, event loop not degraded, plugin load errors empty.
- `openclaw secrets audit --json` gating counts remained clean: plaintext `0`, unresolved refs `0`, shadowed refs `0`.
- `openclaw plugins list --json` showed the `brave` and `codex` global plugin entries loaded from the local OpenClaw npm plugin directory while the migration continued reporting conflicting metadata.

Redactions: replaced local absolute paths with `<stateDir>` and omitted account names, private workspace names, hook URLs, and local user paths.

**Comment by sjf** [comment]
Node 23 was EOL'd in 2025, the fix for this issue is to either switch to an LTS version of node (22 or 24), or update to the latest version of node (26).
