### ISSUE TITLE
[Bug]: Mattermost plugin fails to load after upgrading to 2026.4.2 — createSetupInputPresenceValidator is not a function

### ISSUE THREAD

**Issue by Luna2026-a11y** [openclaw/openclaw#59814]
## Bug type
plugin

## Beta release blocker
Yes

## Summary
After upgrading OpenClaw from 2026.4.1 (working) to 2026.4.2, the Mattermost plugin fails to load with `TypeError: createSetupInputPresenceValidator is not a function`, preventing all Mattermost communication.

## Steps to reproduce
1. Have Mattermost plugin configured and working on OpenClaw 2026.4.1-beta.1
2. Run `openclaw update` to upgrade to 2026.4.2 (git commit 65c1716ad4)
3. Observe gateway startup failure with the error below

## Expected behavior
Mattermost plugin loads and functions normally after upgrading OpenClaw, as it did on 2026.4.1-beta.1.

## Actual behavior
Gateway fails to start the Mattermost plugin. Error in logs:
```
[plugins] mattermost failed to load from /home/luna/openclaw/extensions/mattermost/index.ts: TypeError: (0 , _setupRuntime.createSetupInputPresenceValidator) is not a function
  at maybeThrowOnPluginLoadError (file:///home/luna/openclaw/dist/pi-embedded-Bt2cc94B.js:3422:8)
  at loadOpenClawPlugins (file:///home/luna/openclaw/dist/pi-embedded-Bt2cc94B.js:3987:2)
```

## OpenClaw version
2026.4.2 (git commit 65c1716ad4)

## Operating system
Linux 6.12.74+deb13+1-amd64 (x64)

## Install method
pnpm dev / git clone

## Model
minimax/m2.7

## Provider / routing chain
openclaw (local gateway) -> Mattermost server

## Relevant config
```json
"plugins": {
  "entries": {
    "mattermost": { "enabled": true }
  }
}
```

## Logs, screenshots, and evidence
The error originates in `/extensions/mattermost/src/setup-core.ts`:
```typescript
import { createSetupInputPresenceValidator } from "openclaw/plugin-sdk/setup-runtime";
// ...
validateInput: createSetupInputPresenceValidator({ ... })
```

Analysis:
- `createSetupInputPresenceValidator` is exported from `src/channels/plugins/setup-helpers.ts` line 245
- It is re-exported from `src/plugin-sdk/setup-runtime.ts` line 16
- However it does NOT appear in the compiled output at `dist/plugin-sdk/setup-runtime.js` (appears to be tree-shaken out during build)
- This function was present and working in OpenClaw 2026.4.1-beta.1

## Impact and severity
- **Affected:** Mattermost channel users on OpenClaw 2026.4.2
- **Severity:** High — completely blocks Mattermost communication
- **Frequency:** 100% — every startup
- **Consequence:** Cannot use Mattermost as a channel; must fall back to webchat only

## Additional information
Temporary workaround: set `plugins.entries.mattermost.enabled = false` in `openclaw.json` to allow gateway to start without the broken plugin.

Last known good: OpenClaw 2026.4.1-beta.1
First known bad: OpenClaw 2026.4.2

This is a regression caused by a SDK change that removed `createSetupInputPresenceValidator` from the compiled plugin-sdk output while the Mattermost plugin still depends on it.

**Comment by steipete** [comment]
Closing this as implemented after Codex review.

Current `main` and the latest shipped code keep Mattermost setup on the public setup-safe SDK surface, and `createSetupInputPresenceValidator` is exported again from `openclaw/plugin-sdk/setup-runtime`. The changelog also records a shipped bundled-channel setup fix for Mattermost in `v2026.4.8`, so this specific 2026.4.2 regression appears resolved.

What I checked:

- **Current SDK export is present:** [`src/plugin-sdk/setup-runtime.ts`](https://github.com/openclaw/openclaw/blob/ec3dbd22a4de/src/plugin-sdk/setup-runtime.ts) publicly re-exports `createSetupInputPresenceValidator`, so the helper the issue reports as missing is on the supported setup-runtime surface on current `main`. ([`src/plugin-sdk/setup-runtime.ts:14`](https://github.com/openclaw/openclaw/blob/ec3dbd22a4de/src/plugin-sdk/setup-runtime.ts#L14), [ec3dbd22a4de](https://github.com/openclaw/openclaw/commit/ec3dbd22a4de))
- **Mattermost setup now uses narrow setup-safe SDK imports:** [`extensions/mattermost/src/setup-core.ts`](https://github.com/openclaw/openclaw/blob/ec3dbd22a4de/extensions/mattermost/src/setup-core.ts) imports account/config/setup helpers from `openclaw/plugin-sdk/*` subpaths instead of the local `runtime-api.js` barrel, while still calling `createSetupInputPresenceValidator` from `openclaw/plugin-sdk/setup-runtime`. That matches the intended setup-runtime boundary and avoids dragging full runtime barrels into setup loading. ([`extensions/mattermost/src/setup-core.ts:1`](https://github.com/openclaw/openclaw/blob/ec3dbd22a4de/extensions/mattermost/src/setup-core.ts#L1), [ec3dbd22a4de](https://github.com/openclaw/openclaw/commit/ec3dbd22a4de))
- **Public package export exists:** `package.json` still exports `./plugin-sdk/setup-runtime` to [`dist/plugin-sdk/setup-runtime.js`](https://github.com/openclaw/openclaw/blob/ec3dbd22a4de/dist/plugin-sdk/setup-runtime.js), so the supported package entrypoint for this helper remains part of the shipped contract. ([`package.json:120`](https://github.com/openclaw/openclaw/blob/ec3dbd22a4de/package.json#L120), [ec3dbd22a4de](https://github.com/openclaw/openclaw/commit/ec3dbd22a4de))
- **Docs define this as the setup-safe runtime surface:** The plugin SDK docs explicitly direct channel setup code to `openclaw/plugin-sdk/setup-runtime` for runtime-safe setup helpers and explain that `setup-runtime` must avoid re-entering the full bundled channel runtime. Public docs: [`docs/plugins/sdk-entrypoints.md`](https://docs.openclaw.ai/plugins/sdk-entrypoints). ([`docs/plugins/sdk-entrypoints.md:155`](https://docs.openclaw.ai/plugins/sdk-entrypoints), [ec3dbd22a4de](https://github.com/openclaw/openclaw/commit/ec3dbd22a4de))
- **Shipped release notes record bundled Mattermost setup fix:** [`CHANGELOG.md`](https://github.com/openclaw/openclaw/blob/ec3dbd22a4de/CHANGELOG.md) lists a `2026.4.8` fix for bundled channel setup across Mattermost and other channels so packaged installs no longer rely on missing bundled setup internals during gateway startup. That is the first release note in this checkout that matches the reported 2026.4.2 startup regression class. ([`CHANGELOG.md:1092`](https://github.com/openclaw/openclaw/blob/ec3dbd22a4de/CHANGELOG.md#L1092), [ec3dbd22a4de](https://github.com/openclaw/openclaw/commit/ec3dbd22a4de))
- **Latest release tag still contains the repaired setup-runtime export:** The latest shipped tag available in this checkout, `v2026.4.23`, contains the same [`src/plugin-sdk/setup-runtime.ts`](https://github.com/openclaw/openclaw/blob/a9797214338b/src/plugin-sdk/setup-runtime.ts) export for `createSetupInputPresenceValidator`, so the fix is not just on unreleased `main`. ([`src/plugin-sdk/setup-runtime.ts:14`](https://github.com/openclaw/openclaw/blob/a9797214338b/src/plugin-sdk/setup-runtime.ts#L14), [a9797214338b](https://github.com/openclaw/openclaw/commit/a9797214338b))

So I’m closing this as already implemented rather than keeping a duplicate issue open.

Review notes: reviewed against [ec3dbd22a4de](https://github.com/openclaw/openclaw/commit/ec3dbd22a4dea8da4bcc0d0832da48a83ae27d46); fix evidence: release [v2026.4.8](https://github.com/openclaw/openclaw/releases/tag/v2026.4.8).
