### ISSUE TITLE
After upgrade to 4.29: Gateway starts but all bundled channels crash — missing json5 in plugin-runtime-deps

### ISSUE THREAD

**Issue by gzxmren** [openclaw/openclaw#76088]
## Bug Description

After upgrading from 2026.4.26 to 2026.4.29 (and also reproducible on 4.26), all bundled channel plugins (Telegram, Discord, WhatsApp) crash on startup with:

```
Cannot find package 'json5' imported from 
  ~/.openclaw/plugin-runtime-deps/openclaw-2026.4.29-96928547ff78/dist/frontmatter-Cc-V8aI2.js
```

and

```
Cannot find package 'json5' imported from 
  ~/.openclaw/plugin-runtime-deps/openclaw-2026.4.26-96928547ff78/dist/redact-Cv5sPU4g.js
```

The Gateway process itself starts fine, but **no messaging channels are functional**.

## Root Cause

The bundled `dist/frontmatter-*.js` and `dist/redact-*.js` files contain:

```js
import JSON5 from "json5";
```

However, `json5` is **not declared** in the runtime-deps `package.json` dependencies. When the runtime-deps directory is built during upgrade, `json5` is not installed, causing ESM resolution to fail.

## Impact

- **All bundled channels** (Telegram, Discord, WhatsApp) crash in a restart loop (auto-restart 1-10/10)
- Gateway remains running but no messaging channels are functional
- The issue persists across gateway restarts until manually resolved
- During upgrade, also observed two earlier-stage errors before json5:
  - `Cannot find module 'plugin-sdk/root-alias.cjs/bundled-channel-config-schema'`
  - `Cannot find module '../dist/babel.cjs'` (jiti)

## Steps to Reproduce

1. Upgrade from 4.26 to 4.29 via `npm install -g openclaw@2026.4.29` or `openclaw update`
2. Gateway restarts and rebuilds runtime-deps
3. `json5` is missing from `node_modules/` in the new runtime-deps
4. All bundled channels crash with `Cannot find package 'json5'`

## Additional Issue: npm install destroys runtime-deps

Attempting to fix by running `npm install json5` inside the runtime-deps directory triggers npm dependency resolution, which **prunes all packages not in `package.json`** (removed 144–468 packages in our tests). This appears related to #74949 but the fix in 4.29 does not cover `json5`.

## Workaround

Manually place `json5` without triggering npm resolution:

```bash
cd ~/.openclaw/plugin-runtime-deps/openclaw-*-*/node_modules/
npm pack json5@2.2.3 --pack-destination /tmp/
tar xzf /tmp/json5-2.2.3.tgz
mv package json5
rm /tmp/json5-2.2.3.tgz
# No gateway restart needed — json5 will be resolved on next import
```

## Environment

- **OS:** Linux 6.17.0-22-generic (x64)
- **Node:** v25.8.1
- **OpenClaw:** 2026.4.26 → 2026.4.29 (reproduced on both versions)
- **Install method:** npm global
- **Channels affected:** Telegram, Discord, WhatsApp (all bundled channels)
- **Feishu (openclaw-lark):** Not affected (external plugin, separate resolution)

**Comment by comamitc** [comment]
I just upgraded to 04.29 and this issue is still present. Had to rollback to 04.27.
