### PR TITLE
fix: gracefully handle broken provider modules in media understanding registry

### PR DESCRIPTION
**Pull request by Clausinho**
## Problem

When a bundled provider module (e.g. codex) has unresolved imports in Nix builds — specifically `Cannot find package 'openclaw'` imported from `codex/provider.js` — the call to `resolvePluginCapabilityProviders()` in `buildMediaUnderstandingRegistry()` throws, which kills the **entire** media understanding registry. This makes ALL image analysis fail, even for unrelated providers like Google Gemini that would work fine on their own.

## Root Cause

`buildMediaUnderstandingRegistry()` calls `resolvePluginCapabilityProviders()` eagerly with no error handling. A single broken bundled provider module crashes the registry build before any providers can be registered. The fallback chain in `runWithImageModelFallback` then has zero candidates to try.

## Fix

Wrap `resolvePluginCapabilityProviders()` in a `try/catch` in `provider-registry.ts`:
- On success: normal behavior, all plugin providers loaded
- On failure: log a warning via subsystem logger, continue with an empty plugin provider list
- Config-based providers (from `resolveImageCapableConfigProviderIds`) are still registered as fallback

This means that even if codex is broken, Google Gemini (or any other image-capable model in config) still works.

## Changes

- `src/media-understanding/provider-registry.ts` — try/catch around `resolvePluginCapabilityProviders()`, with structured warning log
- `src/media-understanding/provider-registry.test.ts` — added test for graceful degradation (all 6 tests pass: 5 existing + 1 new)

## Testing

```
 ✓ |media-understanding| provider-registry.test.ts (6 tests) 48ms
   Test Files  1 passed (1)
        Tests  6 passed (6)
```

Verified on a Nix-built deployment where codex has a broken `import 'openclaw'` — before the fix, all image tool calls failed. After the fix, image analysis works via config-based providers.

## Related

- Related to #66702 (image contamination — different bug but same code area)
- The underlying codex Nix build issue (`Cannot find package 'openclaw'`) is a separate packaging problem; this fix makes the registry resilient to it

### CODE REVIEW

**Comment by RomneyDa** [comment]
Heads up: this PR needs to be updated against current `main` before the new required Dependency Guard check can pass.
