### ISSUE TITLE
[Bug]: [Beta][Windows] 2026.5.24-beta.1 Codex harness fails: removed plugin-sdk/codex-native-task-runtime export still imported by @openclaw/codex

### ISSUE THREAD

**Issue by jonathangehrke** [openclaw/openclaw#86087]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

Yes

### Summary

On Windows, OpenClaw 2026.5.24-beta.1 loads @openclaw/codex but Codex agent turns fail before reply because the plugin imports the removed openclaw/plugin-sdk/codex-native-task-runtime export.

### Steps to reproduce

1. On Windows, update/install OpenClaw to 2026.5.24-beta.1 with the Codex plugin available.
2. Start or restart the gateway.
3. Verify the gateway logs show the Codex agent runtime auto-enabled and the codex plugin loaded.
4. Send a normal chat message using the Codex-backed agent/model.
5. Observe that the agent turn fails before reply with ERR_PACKAGE_PATH_NOT_EXPORTED for openclaw/plugin-sdk/codex-native-task-runtime.

### Expected behavior

A Codex-backed agent turn should start the Codex harness and produce a reply; on the same Windows host, Codex agent turns previously worked on 2026.5.20-beta.2 after reinstalling the Codex plugin.

### Actual behavior

The gateway starts and reports the Codex runtime/plugin as loaded, but a normal chat turn fails before any assistant reply. The logs show: "Codex agent harness failed; not falling back to embedded PI backend" followed by ERR_PACKAGE_PATH_NOT_EXPORTED for "./plugin-sdk/codex-native-task-runtime" imported from C:\Users\Admin\.openclaw
pm
ode_modules\@openclaw\codex\dist\run-attempt-CRHVB240.js. Running openclaw doctor and restarting the gateway did not resolve the failure.

### OpenClaw version

2026.5.24-beta.1

### Operating system

Windows 11

### Install method

npm global

### Model

gpt5-5

### Provider / routing chain

OpenClaw WebChat/Control UI -> local OpenClaw gateway on ws://127.0.0.1:18789 -> main agent session -> Codex agent harness via @openclaw/codex -> configured model openai/gpt-5.5. The request fails inside the local Codex plugin/runtime before reaching a successful provider response.

### Logs, screenshots, and evidence

```shell
Version:
openclaw --version
OpenClaw 2026.5.24-beta.1 (0e2e7c6)

Doctor was run before the second repro. It completed, restarted the gateway, and did not resolve the issue.

Gateway startup after doctor:
17:05:01 [gateway] auto-enabled plugins for this runtime without writing config:
- codex agent runtime configured, enabled automatically.
17:05:05 [plugins] plugins.allow is empty; discovered non-bundled plugins may auto-load: brave (...), codex (C:\Users\Admin\.openclaw
pmode_modules\@openclaw\codex\dist\index.js).
17:05:06 [gateway] agent model: openai/gpt-5.5 (thinking=medium, fast=off)
17:05:06 [gateway] http server listening (9 plugins: brave, browser, canvas, codex, device-pair, file-transfer, memory-core, phone-control, talk-voice; 5.8s)
17:05:07 [gateway] ready

Failure on normal chat turn:
17:07:37 [agents/harness] Codex agent harness failed; not falling back to embedded PI backend
17:07:37 [diagnostic] lane task error: lane=main durationMs=7631 error="Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './plugin-sdk/codex-native-task-runtime' is not defined by "exports" in C:\Users\Admin\.openclaw
pm
ode_modules\@openclaw\codex
ode_modules\openclaw\package.json imported from C:\Users\Admin\.openclaw
pm
ode_modules\@openclaw\codex\dist\run-attempt-CRHVB240.js"
17:07:37 Embedded agent failed before reply: Package subpath './plugin-sdk/codex-native-task-runtime' is not defined by "exports" in C:\Users\Admin\.openclaw
pmode_modules\@openclaw\codex
ode_modules\openclaw\package.json imported from C:\Users\Admin\.openclaw
pm
ode_modules\@openclaw\codex\dist\run-attempt-CRHVB240.js

Version/export comparison from npm metadata:
- openclaw@2026.5.20-beta.2 exported ./plugin-sdk/codex-native-task-runtime
- openclaw@2026.5.22 and openclaw@2026.5.24-beta.1 export ./plugin-sdk/agent-harness-task-runtime instead
- @openclaw/codex@2026.5.24-beta.1 declares peerDependency openclaw >=2026.5.24-beta.1, but the runtime still imports the removed codex-native-task-runtime path
```

### Impact and severity

Affected users/systems/channels: Observed on a Windows npm/OpenClaw updater beta install using the @openclaw/codex plugin and a Codex-backed main agent model (openai/gpt-5.5) through the local WebChat/Control UI gateway.

Severity: Blocks workflow for this configuration. The gateway starts, but Codex-backed agent turns fail before any assistant reply is produced.

Frequency: Reproduced after doctor/restart on a normal chat turn in 2026.5.24-beta.1. Based on the current evidence, this is reproducible on the affected host; broader frequency is not yet known.

Consequence: User messages to the affected Codex-backed agent do not receive assistant replies. Doctor/restart did not recover the setup, so the practical workaround appears to require changing version/plugin state or avoiding this beta for Codex.

### Additional information

Last known good observed on this host: 2026.5.20-beta.2, after manually uninstalling/reinstalling the Codex plugin.

First known bad observed on this host: 2026.5.24-beta.1 (0e2e7c6).

This may be related to the SDK export rename from codex-native-task-runtime to agent-harness-task-runtime. The failure path shows @openclaw/codex importing the old codex-native-task-runtime subpath from its nested openclaw package, while current openclaw packages no longer expose that export.

openclaw doctor was run before the attached repro and did not resolve the issue.

**Comment by jonathangehrke** [comment]
Update from the original Windows reporter:

After updating this host to OpenClaw 2026.5.26, normal Codex-backed replies work again in my current setup. I no longer see the original `ERR_PACKAGE_PATH_NOT_EXPORTED` failure for `openclaw/plugin-sdk/codex-native-task-runtime`.

Important caveat: this does not necessarily prove the original upgrade-path bug is fully fixed. My current runtime appears to be using the regular `pi` / `openai-codex/gpt-5.5` path, and I no longer see an active stale `@openclaw/codex` package importing the removed `codex-native-task-runtime` subpath.

So from my side:
- Current local symptom: resolved / no longer reproducing on 2026.5.26.
- Original suspected cause: stale `@openclaw/codex` package importing the removed SDK subpath.
- Remaining validation needed before closing: verify that the official Codex plugin/harness upgrade path itself works on Windows with current OpenClaw, especially from a stale/beta install state. 
- This looks consistent with current 2026.5.26 Codex sources using `agent-harness-task-runtime`; however, it does not validate the stale package compatibility path that PR #86130 is trying to cover.

**Comment by hanyizuo** [comment]
Adding a Linux / 2026.5.22 data point from my environment. This looks closely related to the stale `@openclaw/codex` runner / `plugin-sdk` export compatibility problem described here.

Environment:
- Ubuntu server, running as root
- OpenClaw `2026.5.22 (a374c3a)`
- Global npm install: `/usr/bin/openclaw` -> global `openclaw@2026.5.22`
- No pnpm/bun multi-install evidence found on this host
- OpenAI provider/OAuth remained usable
- PI runtime worked as a fallback; failures were isolated to the Codex harness/runtime path

Observed failures after upgrading from 2026.5.4 through 2026.5.20 / 2026.5.22:

```text
Agent failed before reply: Cannot find module '/usr/lib/node_modules/openclaw/dist/plugin-sdk/root-alias.cjs/agent-harness-task-runtime'
```

The require stack pointed at generated `@openclaw/codex` runner files under a per-user OpenClaw npm cache, e.g. a path shaped like:

```text
~/.openclaw/npm/node_modules/@openclaw/codex/dist/run-attempt-*.js
```

A second error was also observed on the Codex harness/runtime path:

```text
Agent failed before reply: (0 , _sandbox.resolveSandboxRuntimeStatus) is not a function
```

Important distinctions from this reproduction:
- The gateway/dashboard could start and listen normally.
- The OpenAI provider/OAuth layer was not the broken layer.
- Switching model-scoped runtime policy from `agentRuntime.id = "codex"` to `agentRuntime.id = "pi"` restored normal chat operation.
- The `openai-codex` provider/OAuth entry was left intact; deleting that is not the right workaround.
- The failing layer appeared to be the Codex harness/generated runner/cache plus `plugin-sdk` export shape/version compatibility.

My working diagnosis is that a stale generated `@openclaw/codex` runner/cache was still importing old compatibility paths such as `root-alias.cjs/agent-harness-task-runtime`, while the installed `openclaw/dist/plugin-sdk` no longer exposed the same shape. The sandbox error looks like the same class of version/export drift: generated runner code expected a sandbox helper export that the installed package no longer provided in that form.

Suggested fix direction:
- Keep/restore backward-compatible `plugin-sdk` exports for stale official `@openclaw/codex` installs where possible.
- During upgrade/postinstall, force rebuild or invalidate stale Codex generated runner/cache under the user OpenClaw npm/cache directories.
- Add a Codex harness self-test after upgrade/doctor so users do not silently end up with `agentRuntime.id = "codex"` pointing at a broken harness.
- Avoid having `doctor --fix` automatically re-enable Codex runtime on affected installs unless the harness self-test passes, because PI may be the only working fallback.

For now I have kept PI as the production runtime fallback on this machine and preserved the OpenAI/Codex OAuth provider config separately.

**Comment by steipete** [comment]
Thanks for the report. Closing as stale beta upgrade-state.

Current Codex packages use the renamed `agent-harness-task-runtime` export. The old `codex-native-task-runtime` reference is no longer a public export to restore; legacy runtime refs are migration/doctor/private-loader-only. The reporter also noted this no longer reproduced on 2026.5.26.
