### ISSUE TITLE
[Bug]: Windows regression after 2026.3.31 update: Telegram plugin fails to load (Cannot find module 'grammy')

### ISSUE THREAD

**Issue by Charlesmpc** [openclaw/openclaw#58676]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

## Summary

After updating OpenClaw on Windows to the 2026-03-31 build, the Telegram plugin regressed and no longer starts.

This setup was working before the update. After the update, Telegram fails to load at startup with:

```text
telegram failed to load from C:\Users\Illidan\AppData\Roaming\npm\node_modules\openclaw\dist\extensions\telegram\index.js: Error: Cannot find module 'grammy'
Require stack:
- C:\Users\Illidan\AppData\Roaming\npm\node_modules\openclaw\dist\sticker-cache-1Tf7t-45.js


### Steps to reproduce

1. Start from a Windows machine where Telegram was previously working with OpenClaw 2026.3.28
2. Update OpenClaw to 2026.3.31
3. Start OpenClaw / gateway normally
4. Observe plugin startup logs

### Expected behavior

The Telegram plugin should load successfully and the Telegram bot/channel should continue working after the update.

### Actual behavior

The Telegram plugin fails to load during startup because module grammy cannot be found, and Telegram becomes unusable.

### OpenClaw version

2026.03.31

### Operating system

Windows 11

### Install method

powershell -c "irm https://openclaw.ai/install.ps1 | iex"

### Model

minimax M2.7

### Provider / routing chain

openclaw -> minimax

### Additional provider/model setup details

_No response_

### Logs, screenshots, and evidence

```shell

```

**Comment by steipete** [comment]
Fixed on `main` by #58782. Closing as resolved.
