### ISSUE TITLE
[Bug]: Stale subagent completion can be delivered into a replaced requester lifecycle

### ISSUE THREAD

**Issue by mjnkao** [openclaw/openclaw#118018]
## Bug type

Behavior/lifecycle bug: a completion can be delivered to the wrong requester lifecycle and then
settled without a crash or an actionable remaining obligation.

## Summary

A persisted subagent requester-settle wake identifies the requester session, but it does not record
the requester lifecycle revision that accepted the child handoff.

If the parent session is reset or replaced while retaining the same session identity, a completion
from the old lifecycle can be dispatched into the replacement lifecycle. The old batch can then be
marked complete and its wake cleared even though the replacement lifecycle never accepted that
work.

From the operator's perspective, delegated work can therefore appear to vanish, complete in the
wrong conversation lifecycle, or leave no truthful status explaining what happened.

## Affected baseline

- OpenClaw `v2026.7.2-beta.7`
- Current source retains the same target-lifecycle contract gap.
- The defect is transport- and provider-independent.

Relevant owner seams include:

- [`src/agents/subagent-registry.ts`](https://github.com/openclaw/openclaw/blob/v2026.7.2-beta.7/src/agents/subagent-registry.ts)
- [`src/config/sessions/session-accessor.sqlite-lifecycle.ts`](https://github.com/openclaw/openclaw/blob/v2026.7.2-beta.7/src/config/sessions/session-accessor.sqlite-lifecycle.ts)
- [`src/gateway/session-reset-service.ts`](https://github.com/openclaw/openclaw/blob/v2026.7.2-beta.7/src/gateway/session-reset-service.ts)

## Deterministic source-backed reproduction

1. Create parent session `agent:main:main` with `sessionId=sess-main` and
   `lifecycleRevision=revision-1`.
2. Have that lifecycle admit a subagent handoff and persist its requester-settle wake.
3. Before the subagent completes, reset or replace the parent so the same session identity now has
   `lifecycleRevision=revision-2`.
4. Let the old subagent complete and run the normal requester-settle dispatch.

### Actual behavior

- The current requester is resolved by session identity.
- The old completion can be dispatched into `revision-2`.
- The old batch can be marked complete.
- The requester-settle wake can be cleared.
- No remaining owner state necessarily explains that the completion belonged to `revision-1`.

### Expected behavior

- The lifecycle revision captured when the handoff was admitted must be validated immediately
  before completion dispatch.
- A matching lifecycle may receive the completion exactly once.
- A missing or mismatched lifecycle must not receive the stale completion.
- A mismatch must not be marked delivered, completed, or cleared as if settlement succeeded.
- The retained state must expose a bounded reason and next safe action through an existing status or
  diagnostic projection.

## Root cause

The subagent owner persists child occurrence identity and requester session identity. The session
owner separately knows the current requester lifecycle revision. The handoff does not persist the
expected target lifecycle revision needed to prove that the current requester is still authorized
to consume the completion.

Session identity answers **where** to route. It does not answer **which lifecycle** accepted the
work.

OpenClaw already uses lifecycle-revision validation in session-owner paths. The missing authority
fact is the requester lifecycle revision captured at subagent handoff admission.

## Suggested owner-local fix boundary

1. Capture the requester lifecycle revision when the subagent handoff is admitted.
2. Persist it as a typed field, such as `expectedRequesterLifecycleRevision`, with the existing
   requester-settle state.
3. Ask the canonical session owner to validate that value immediately before dispatch.
4. On mismatch, do not dispatch, mark delivered, complete the batch, or clear the wake. Retain an
   explicit state such as `requester_replaced` / `target_lifecycle_mismatch` that is queryable
   through an existing bounded projection.
5. Keep exact duplicate settlement idempotent.
6. For legacy persisted rows without the authority fact, do not invent a revision or deliver solely
   because the session key matches. Treat them as `legacy_unfenced` / uncertain unless continuity
   can be proven by the existing owner.

This should remain an owner-local protocol repair. It should not add a shared persistence
framework, generic recovery worker, global mode, or broad inspection API.

## Acceptance criteria

- [ ] An unchanged requester lifecycle receives the completion exactly once.
- [ ] The same session identity with a replaced lifecycle receives no stale completion.
- [ ] A lifecycle mismatch remains explicit and queryable instead of being cleared as successful.
- [ ] Restart between persisted wake admission and dispatch revalidates the target lifecycle.
- [ ] An exact duplicate completion is idempotent.
- [ ] A missing requester produces an explicit bounded state rather than silent settlement.
- [ ] Legacy rows without a requester lifecycle revision fail closed unless continuity is proven.
- [ ] A storage failure before durable admission cannot produce accepted/success framing.
- [ ] Tests keep `sessionId` constant while changing `lifecycleRevision`, so session-key-only routing
      cannot pass accidentally.
- [ ] The implementation adds no new central runtime, generic worker, or recovery topology.

## Related work and scope boundary

- #117412 concerns source-side subagent restart recovery and run-generation fencing. This issue is
  limited to target-side requester lifecycle validation and must work independently of that
  topology.
- #92433 concerns whether queued completion was actually consumed and which yielded run owns the
  delivery outcome. This issue asks the earlier authorization question: whether this requester
  lifecycle may receive the completion at all.

Not in scope: provider idle/liveness watchdogs, timeout presentation, interactive question
delivery, compaction behavior, generic task replay, or arbitrary external side-effect recovery.

## Impact

This affects delegated work that completes across a parent reset or lifecycle replacement. It can
cause stale output to enter a new lifecycle or make an accepted completion disappear from the
operator's actionable state. Stronger models and longer context windows do not remove this
lifecycle race.

## Do you plan to open a PR for this?

Yes, after maintainers confirm the owner-local contract boundary. The intended implementation is
one focused PR containing the persisted authority field, pre-dispatch validation, explicit mismatch
projection, legacy behavior, and deterministic reset/restart tests.

**Comment by jinngimk-lang** [comment]
This is almost the perfect **stale-authority delivery** breaker: the same session ID still exists, but it is a *different lifecycle*, and an old subagent completion can be delivered into the replacement as if continuity were proven.

AgentCI is recruiting lifecycle-fencing cases like this. A portable fixture could bind handoff → expected requester lifecycle revision → persisted wake → reset/replace → completion dispatch, with exact-match / mismatch / legacy-unfenced controls. If you or an external agent contribute the reduced fixture, we’ll preserve this issue as provenance and give permanent public credit/backlink in AgentCI’s Breaker Hall of Fame + priority conversion help.

AgentCI: https://github.com/jinngimk-lang/agentci · recognition: https://github.com/jinngimk-lang/agentci/blob/main/COMMUNITY.md

Affiliation disclosed; no OpenClaw certification claim.

**Comment by mgr-nick** [comment]
*Written and posted by Fable 5.1 Low (an LLM agent), on behalf of the account owner.*

**Still reproduces on 2026.9.4 (3a9d69d), the release after this was closed as completed — requesting reopen.**

### Environment
- OpenClaw **2026.9.4 (3a9d69d)**, Linux x86_64 (Debian 12, GCE), npm global install, systemd user unit
- Upgraded 2026.8.2 → 2026.9.4 at 2026-09-17 23:12–23:19 UTC
- Requester: `main` agent, Telegram DM session (`agent:main:telegram:direct:<id>`), same session key before and after reset
- Registry at the time: ~230 retained `subagent_runs` rows for this agent (all `cleanup: "keep"`, all `execution.status: terminal`), ~120 of them owed to this DM session; every one already `delivery.status: delivered`, oldest 2026-08-19

### What happened
1. 23:46:47 UTC — `/new` on the DM session (journal: session reset for the same key).
2. Within 35 s the gateway dispatched **four** `requester-settle` wakes into the fresh lifecycle (23:47:21, 23:48:40, 23:49:07, 23:49:39), each bundling 2–3 children as "Every subagent spawned from this session has now settled":
   - 3 children spawned together on **2026-09-08** (delivered that day)
   - 2 children spawned together on **2026-09-08** (delivered that day)
   - 2 children spawned together on **2026-09-17 22:25** (delivered that evening)
   - 2 children spawned together on **2026-09-17 22:34** (delivered that evening)
3. The requester model treated each bundle as fresh work and re-reported nine days-old results to the user, including re-sending an attachment.
4. Nothing had fired in the 27 minutes between the upgrade and the reset. All nine re-dispatched rows had `delivery.status: delivered` with their original `deliveredAt`; after the replay they still do, and `cleanupCompletedAt` was untouched. `requesterSettleWake` is `null` on every row on disk (it is only ever set in memory), so the on-disk registry cannot distinguish "settled under the new bookkeeping" from "never considered".

Only children that were **spawned concurrently in one turn** were visible, because a batch needs `requiredSettled.length >= 2` to dispatch; singletons were presumably re-armed too and finished silently. So the reset re-exposed every retained child of the session, bounded only by how many happened to have batch mates.

### Why I think this is the same defect
The wake identifies the requester by session key only. The reset kept the key and replaced the lifecycle; every completion ever owed to that key became deliverable to the new lifecycle, exactly as described in the OP. The `requiredSettled` dispatch check does not consult `delivery.status === "delivered"`, so prior delivery does not protect a row.

### Operator impact / mitigation used
- No config lever removes `keep`-mode rows: the registry sweep `continue`s past `cleanup === "keep"` unconditionally, `session.maintenance.pruneAfter` acts on the session store not `subagent_runs`, and `openclaw sessions archive` likewise.
- Mitigation: stopped the gateway, deleted all terminal `subagent_runs` rows, restarted; switched all spawns to `cleanup: "delete"` with `archiveAfterMinutes: 10080` so the registry ages out. I have not re-tested `/new` on the same session with a populated registry.

### Ask
Reopen, or reference the commit that was meant to close this so it can be checked against 9.4. A lifecycle-revision fence on the wake (as the OP proposes) and/or skipping already-`delivered` entries in `requiredSettled` would both have prevented this.
