### ISSUE TITLE
[Bug]: TUI fuzzy alias type breaks test typecheck

### ISSUE THREAD

**Issue by steipete** [openclaw/openclaw#107586]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

The TUI fuzzy-search refactor added an optional `searchText` alias but left `SearchableSelectList` typed as accepting only the upstream `SelectItem`, so the repository test typecheck fails on current `main`.

### Steps to reproduce

1. Check out `main` at or after `bfb84d3400dea2878d9842aa9f5e52d9168aba57`.
2. Run `pnpm check:test-types`.
3. Observe TS2353 in `src/tui/components/searchable-select-list.test.ts:262`.

### Expected behavior

The documented and tested fuzzy-search alias is accepted by the component's input type and `pnpm check:test-types` passes.

### Actual behavior

TypeScript rejects the `searchText` property because upstream `@earendil-works/pi-tui` 0.80.3 defines `SelectItem` with only `value`, `label`, and optional `description`.

### OpenClaw version

`main` at `66def08d83293b5a6a1fd1fc9e8b048fd51c992c`

### Operating system

Linux (GitHub Actions / Blacksmith runner)

### Install method

Source checkout with pnpm

### Model

Not applicable

### Provider / routing chain

Not applicable

### Logs

```text
src/tui/components/searchable-select-list.test.ts(262,51): error TS2353: Object literal may only specify known properties, and 'searchText' does not exist in type 'SelectItem'.
```

### Screenshots, recordings, and evidence

Failing job: https://github.com/openclaw/openclaw/actions/runs/29340644237/job/87111287026

### Impact and severity

Affected: repository CI and every PR based on the affected main revision. Severity: workflow-blocking. Frequency: deterministic. Consequence: test typecheck fails before otherwise valid PRs can land.

### Additional information

First known bad commit: `bfb84d3400dea2878d9842aa9f5e52d9168aba57` (`refactor(tui): use native fuzzy filtering`).
