### ISSUE TITLE
[Bug]: Discord plugin remains on incompatible 2026.9.2 metadata after 2026.9.6 Gateway update

### ISSUE THREAD

**Issue by DonnieFi** [openclaw/openclaw#157463]
## Bug type

Behavior bug / broken plugin installation

## Summary

After the Gateway updated to OpenClaw `2026.9.6` on the stable channel, Discord remained associated with an old/incompatible plugin installation. The runtime reported the Discord plugin as missing or not loadable, while the configured Discord accounts and channel settings remained present.

The CLI specifically suggested reinstalling `@openclaw/discord@2026.9.2`, even though the running core Gateway and stock plugin tree are `2026.9.6`. This leaves the installation with mixed core/plugin release versions and Discord stops responding.

Related broader update failure: #157227.

## Steps to reproduce

1. Run a stable update to OpenClaw `2026.9.6` on a system with Discord configured.
2. Have the Gateway service transition from the previous git/plugin tree to the npm package.
3. Run `openclaw status --deep` or `openclaw plugins list`.

## Expected behavior

The Discord channel plugin should converge to the same compatible release as the running Gateway, or the updater should stop before changing state and provide a clear repair path.

## Actual behavior

The installation reports:

```text
Discord  ON  WARN  plugin not installed
Plugin "discord" install incomplete: plugin metadata is missing.
Run openclaw plugins install @openclaw/discord@2026.9.2 --force to reinstall the plugin.
```

The configured manifest path is also rejected as unsafe:

```text
/mnt/adata/opt/openclaw/extensions/discord/openclaw.plugin.json
```

The Gateway logs then report:

```text
channels.discord is configured but no channel plugin is installed or loadable
```

Discord is unavailable, while WhatsApp remains healthy. A scheduled run also recorded `Unsupported channel: discord`.

## Environment

- OpenClaw core/Gateway: `2026.9.6`
- Configured update channel: `stable`
- Install method: npm package after a git-to-stable transition
- OS: Debian GNU/Linux 13, x64
- Node.js: 24.16.0
- Gateway: systemd user service

## Additional evidence

During the failed transition, Gateway shutdown cleanup also reported a missing runtime module under the old `/mnt/adata` tree:

```text
Cannot find module '/mnt/adata/opt/openclaw/dist/runtime-DbZsyucN.mjs'
```

No credentials or token values are included. The full update/service failure is tracked in #157227; this issue isolates the Discord plugin version/path convergence failure.

**Comment by DonnieFi** [comment]
Follow-up from the affected installation on 2026-09-24. I repaired Discord and captured the failure and recovery sequence.

**Before repair:** `gateway status --deep --require-rpc --json` confirmed the running Gateway and installed core package were both `2026.9.6`, with RPC working. `channels status --json` did not list Discord. `plugins list --json` had no loadable Discord entry and reported two diagnostics:

```text
unsafe plugin manifest path: /mnt/adata/opt/openclaw/extensions/discord/openclaw.plugin.json (validation)
Plugin "discord" install incomplete: plugin metadata is missing. Run `openclaw plugins install @openclaw/discord@2026.9.2 --force` to reinstall the plugin.
```

The config still selected that local checkout through `plugins.load.paths`, while the update history showed a failed `finalize:doctor` step (`agent-database-lease-active`). The failed update had left Discord's data/settings upgrade pending. After removing only the rejected Discord load path, `openclaw update repair --yes --json` still skipped Discord plugin convergence with `Skipping "discord" (source: path)`. This shows that the saved install record continued to classify it as a path plugin even after the config path was removed.

**Recovery:** I backed up the config, removed that one Discord load path, used `gateway suspend --wait 60 --json` (ready, zero active work), and stopped the managed systemd user service. With the service stopped, I ran update repair, then `plugins install @openclaw/discord@2026.9.6 --force`, followed by `doctor --fix`. Doctor reported `Deferred state migration completed for plugin "discord"`. I restarted the same managed service.

**After repair:** `plugins list --json` reports Discord `version: 2026.9.6`, `origin: global`, `status: loaded`, with no Discord diagnostics. `config validate` passes. Deep Gateway status reports 9.6 and RPC OK; `health --verbose --json` reports OK. Both configured Discord accounts report `running: true`, `connected: true`, `lifecycle: ready`, and `lastError: null`; channel status has no issues. The service startup command hit its 45-second health wait, but the service became ready shortly afterward. I did not send a Discord message round trip.

The before/after Gateway logs, update support logs, service journal, and pre-repair config backup are retained privately on the affected host for follow-up. I have not attached raw logs because they can contain private identifiers or credentials.

**Comment by DonnieFi** [comment]
The `unsafe plugin manifest path ... (validation)` diagnostic above has a separate cause, now filed as #157485. The failed update left a hardlinked `openclaw-update-runtime-*` snapshot of the checkout, so 158 of 161 checkout plugin manifests have a link count of 2. Non-bundled plugins reject hardlinked manifests. This issue stays scoped to the path install record that `update repair` skips.
