### ISSUE TITLE
[Bug]: npm global upgrade leaves stale Vite chunks, gateway 500s on every HTTP request

### ISSUE THREAD

**Issue by EmpireCreator** [openclaw/openclaw#76907]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

After upgrading OpenClaw from 2026.4.23 to 2026.5.2 via `npm install -g`, the gateway starts but every HTTP request returns Internal Server Error due to missing Vite/Rollup chunk files that the new entry points reference.

### Steps to reproduce

1. Have OpenClaw 2026.4.23 installed globally via npm (`npm install -g openclaw@2026.4.23`)
2. Run `npm install -g openclaw@2026.5.2`
3. Run `openclaw gateway restart`
4. Observe Internal Server Error on all HTTP requests and "Something went wrong" on Telegram

### Expected behavior

Gateway starts cleanly after in-place npm global upgrade with no missing modules.

### Actual behavior

Gateway starts but fails on every request. Logs show repeated `ERR_MODULE_NOT_FOUND` for three chunk files:

- `managed-image-attachments-I6Yx6VOU.js` (imported from `server.impl-DhtU4okW.js`)
- `delivery-target.runtime-BrQUPN11.js` (imported from `jobs-DYu8cOq2.js`)
- `io-CP_UgASQ.js` (imported from `status.summary-BvB2CJmS.js`)

All three are Vite/Rollup hashed chunks. The new entry points reference chunk hashes that don't exist on disk. The old chunk files from 2026.4.23 remain in `dist/` but are no longer referenced.

Example error from gateway log:

```
[gateway-http] unhandled error in request handler: Error: Cannot find module
'/opt/homebrew/lib/node_modules/openclaw/dist/managed-image-attachments-I6Yx6VOU.js'
imported from '/opt/homebrew/lib/node_modules/openclaw/dist/server.impl-DhtU4okW.js'
  code: 'ERR_MODULE_NOT_FOUND'
```

### OpenClaw version

2026.5.2 (8b2a6e5), upgraded from 2026.4.23

### Operating system

macOS 26.4.1 (Tahoe), arm64

### Install method

npm global

### Model

N/A, bug is in gateway startup, not model-specific

### Provider / routing chain

N/A, all HTTP requests fail before reaching any provider

### Additional provider/model setup details

Not model-related. The `dist/` directory after npm upgrade contains old chunk hashes from 2026.4.23 mixed with new entry points from 2026.5.2 that reference chunk hashes that were never written to disk.

### Logs, screenshots, and evidence

```shell
Relevant gateway log provided below. The log shows:

- Normal WS operations succeed (`node.list`, `device.pair.list`, `sessions.list`)
- Every HTTP request handler fails with `ERR_MODULE_NOT_FOUND` for the three chunks listed above
- `cron.list` fails with missing `delivery-target.runtime-BrQUPN11.js`
- `/status` fails with missing `io-CP_UgASQ.js`


[2026-05-03T13:51:30.188-05:00] [INFO] [gateway/ws] node.list succeeded

[2026-05-03T13:51:30.189-05:00] [INFO] [gateway/ws] device.pair.list succeeded

[2026-05-03T13:51:31.795-05:00] [ERROR] [gateway-http] unhandled error in request handler: Error: Cannot find module '/opt/homebrew/lib/node_modules/openclaw/dist/managed-image-attachments-I6Yx6VOU.js' imported from /opt/homebrew/lib/node_modules/openclaw/dist/server.impl-DhtU4okW.js
    at finalizeResolution (node:internal/modules/esm/resolve:274:11)
    at moduleResolve (node:internal/modules/esm/resolve:859:10)
    at defaultResolve (node:internal/modules/esm/resolve:983:11)
    at ModuleLoader.#cachedDefaultResolve (node:internal/modules/esm/loader:731:20)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:708:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:310:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:663:21)
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///opt/homebrew/lib/node_modules/openclaw/dist/managed-image-attachments-I6Yx6VOU.js'

[2026-05-03T13:51:33.264-05:00] [INFO] [gateway/ws] sessions.list succeeded

[2026-05-03T13:52:07.205-05:00] [INFO] [gateway/ws] sessions.list succeeded

[2026-05-03T13:52:17.110-05:00] [ERROR] [gateway] request handler failed: Error: Cannot find module '/opt/homebrew/lib/node_modules/openclaw/dist/delivery-target.runtime-BrQUPN11.js' imported from /opt/homebrew/lib/node_modules/openclaw/dist/jobs-DYu8cOq2.js: code=ERR_MODULE_NOT_FOUND

[2026-05-03T13:52:17.110-05:00] [INFO] [gateway/ws] cron.list failed: errorCode=UNAVAILABLE errorMessage=Error: Cannot find module '/opt/homebrew/lib/node_modules/openclaw/dist/delivery-target.runtime-BrQUPN11.js' imported from /opt/homebrew/lib/node_modules/openclaw/dist/jobs-DYu8cOq2.js: code=ERR_MODULE_NOT_FOUND

[2026-05-03T13:52:17.195-05:00] [ERROR] [gateway] request handler failed: Error: Cannot find module '/opt/homebrew/lib/node_modules/openclaw/dist/io-CP_UgASQ.js' imported from /opt/homebrew/lib/node_modules/openclaw/dist/status.summary-BvB2CJmS.js: code=ERR_MODULE_NOT_FOUND

[2026-05-03T13:52:17.196-05:00] [INFO] [gateway/ws] status failed: errorCode=UNAVAILABLE errorMessage=Error: Cannot find module '/opt/homebrew/lib/node_modules/openclaw/dist/io-CP_UgASQ.js' imported from /opt/homebrew/lib/node_modules/openclaw/dist/status.summary-BvB2CJmS.js: code=ERR_MODULE_NOT_FOUND
```

### Impact and severity

- **Affected:** Any node upgrading from 2026.4.23 to 2026.5.2 via `npm install -g`
- **Severity:** Critical — gateway is fully non-functional, all HTTP requests return 500
- **Frequency:** 1/1 observed upgrade attempts on this path
- **Consequence:** Agent completely unresponsive on all channels. Telegram shows "Something went wrong while processing your request. Please try again."

### Additional information

- **Last known good:** 2026.4.23
- **First known bad:** 2026.5.2 (only upgrade path tested)
- **Workaround exists.** Nuke the package directory and reinstall fresh. No data loss -- all user data lives in `~/.openclaw/`, not in the npm package directory:

```bash
sudo rm -rf /opt/homebrew/lib/node_modules/openclaw
npm install -g openclaw@2026.5.2
openclaw gateway restart
```

- `openclaw doctor --fix` alone did not resolve the missing chunks. It did install a missing `brave` plugin and clean stale `acpx` entries, but the core chunk mismatch required a full nuke and reinstall.
- Root cause is likely npm not fully replacing the `dist/` directory during an in-place global upgrade, leaving orphaned old chunks while writing new entry points that reference different hashes.
