### ISSUE TITLE
[Bug]: ARM regression + missing dist file in 2026.1.23–2026.1.24.x

### ISSUE THREAD

**Issue by brainstormity** [openclaw/openclaw#4489]
### Environment

* Device: Raspberry Pi
* Architecture: aarch64 / ARM64
* OS: Raspberry Pi OS (64-bit)
* Node.js: (output of `node -v`)
* npm: (output of `npm -v`)
* Install method: `npm install -g clawdbot`

---

### What worked before

Clawdbot was working correctly on this same Raspberry Pi setup on versions prior to 2026.1.24.
Both the CLI and gateway ran normally.

---

### What broke

After upgrading to **2026.1.24-3**, the gateway repeatedly starts and crashes, entering a restart loop on ARM.

Downgrading to earlier versions reveals additional issues.

---

#### 1. Missing module in 2026.1.23

Running:

```
clawdbot --version
```

Produces:

```
[clawdbot] Failed to start CLI: Error [ERR_MODULE_NOT_FOUND]:
Cannot find module
/home/rpi/.npm-global/lib/node_modules/clawdbot/dist/tts/tts.js
imported from
/home/rpi/.npm-global/lib/node_modules/clawdbot/dist/auto-reply/reply/dispatch-from-config.js
```

This suggests `dist/tts/tts.js` is referenced but not included in the published npm package.

---

#### 2. Gateway restart loop / zombie process

When starting the gateway:

* `clawdbot` starts
* `clawdbot-gateway` briefly appears
* The process becomes `<defunct>`
* Both processes exit
* systemd / CLI restarts them again

Observed via:

```
pgrep -a claw
```

---

#### 3. Config version mismatch spam

When downgrading to **2026.1.22**:

```
Config was last written by a newer Clawdbot (2026.1.24-3);
current version is 2026.1.22.
```

This message repeats multiple times on gateway startup instead of warning once.

---

### Expected behavior

* Published npm packages should not reference missing files
* Gateway should run stably on ARM (aarch64)
* Config version mismatch should warn once and continue normally
* Gateway should not restart-loop or leave defunct processes

---

### Workarounds

* Pinning to **2026.1.22** allows the gateway to run, but with repeated config warnings
* No working version found for ARM in **2026.1.23–2026.1.24.x**

---

### Additional notes

This appears to be a combination of:

* A packaging issue (missing `dist/tts/tts.js`)
* A regression affecting ARM builds in recent releases

**Comment by spiceoogway** [comment]
## Investigation Results

I've investigated both issues reported here:

### ✅ Issue 1: Missing dist/tts/tts.js - **FIXED**
- **Root cause**: `dist/tts/**` was missing from package.json `files` array
- **Fixed in commit**: [11f039ef8](https://github.com/openclaw/openclaw/commit/11f039ef8592dcb4c3195d3addb76a6e32aa0758) (Jan 24, 2026)
- **Fixed versions**: 2026.1.23-1 and all later versions (2026.1.24+)

### ⚠️ Issue 2: Gateway Restart Loop on ARM - **LIKELY FIXED**
- **Related fix**: [dea96a2c3](https://github.com/openclaw/openclaw/commit/dea96a2c3dfaa38b60a5c83536d35242f4a5dc38) "fix: handle PID recycling in container gateway lock"
- **Details**: This commit fixes defunct process issues by verifying PIDs via `/proc/PID/cmdline`
- **Status**: May have resolved the ARM restart loop, but **needs verification on ARM hardware**

### 🔴 New Issue: Clipboard ARMv7 Incompatibility (2026.1.29+)
There's a **separate ARM issue** in newer versions (2026.1.29+) related to clipboard functionality:
- **Symptom**: `Cannot find module '@mariozechner/clipboard-linux-arm-gnueabihf'`
- **Affected**: 32-bit ARM (ARMv7) only; 64-bit ARM (ARM64) works fine
- **Related issues**: #3028, #4596
- **This is NOT part of #4489** - it's a new regression

## Recommendation
1. **Close #4489 as fixed** - both reported issues (tts.js + gateway loop) are addressed
2. **Ask reporter** to test **2026.1.25+** on ARM and report back
3. **Track clipboard issue separately** - it's a different problem in newer versions

## For ARM Users
- **64-bit ARM (aarch64)**: Should work fine in 2026.1.24+ 
- **32-bit ARM (armv7)**: May hit clipboard issue in 2026.1.29+
  - Workaround: Use 2026.1.24-3 or add clipboard fallback

Would appreciate confirmation from @brainstormity that 2026.1.24-3 or 2026.1.25+ resolves the original gateway restart issue!
