### PR TITLE
fix(codex): bound catalog retries and plugin capture retention

### LINKED ISSUE #152689: Codex resident catalog retry loop after 2026.9.5 fills os.tmpdir() with repeated 342 MB plugin captures
## Summary

After updating npm `stable` from 2026.9.4 to 2026.9.5, the Gateway started logging a repeating failure that had never appeared before:

```
[agent/embedded] Codex resident catalog background update failed
error="thread/read transport failed after request write: codex app-server client is closed"
```

The Codex plugin project is 342 MB. Plugin source captures copy it into `os.tmpdir()`, and on this host `/tmp` is a 7.6 GB tmpfs. The volume filled, after which SQLite session writes failed and agent turns ended with:

```
This turn ended before a reply: OpenClaw could not write local session data
because the disk is full. Free some disk space and try again.
Error: ENOSPC: no space left on device, write
```

The real disk was never full: 218 GB with 167 GB free throughout.

## Evidence

**1. The Codex error is new and correlates with the update.** Occurrences per day from the journal:

| Day | `Codex resident catalog background update failed` |
| --- | ---: |
| 10 days before the update | 0 |
| Update day | 84 |

First occurrence was six minutes after the post-update Gateway start. It was still firing hours later.

**2. The capture sizes match the Codex plugin exactly.** A retained model-catalog scratch directory contained nested plugin captures:

```
341M  /tmp/openclaw-model-catalog-XXXXXX/openclaw-plugin-build-XXXXXX
341M  /tmp/openclaw-model-catalog-XXXXXX/openclaw-plugin-build-XXXXXX
152K  ... (7 more)
```

`$OPENCLAW_STATE_DIR/npm/projects/openclaw-codex-*` is 342 MB.

**3. Every ENOSPC in the journal is a plugin load.** 38 occurrences within one hour, all of this shape:

```
[plugins] codex failed during load from
$OPENCLAW_STATE_DIR/npm/projects/openclaw-codex-*/node_modules/@openclaw/codex/dist/index.js:
Error: ENOSPC: no space left on device, write
```

`llama-cpp` failed the same way. Session lanes then failed: `lane task error: lane=session:agent:main:main error="ENOSPC: no space left on device, write"`.

**4. Secondary defect: reclaiming `/tmp` leaves loaded plugins pointing at deleted captures.** After the temp directories were freed, `plugins disable` failed:

```
Cannot find module '/tmp/openclaw-plugin-build-XXXXXX/package-0/node_modules/@openclaw/whatsapp/dist/secret-contract-api.js'
Require stack:
- $OPENCLAW_STATE_DIR/npm/projects/openclaw-whatsapp-*/node_modules/@openclaw/whatsapp/dist/index.js
```

A live Gateway lazily requires files from a capture directory that anything may remove, with no revalidation.

## Relation to #150541

#150541 ("Gateway retains plugin build temp directories after forced exits") describes the accumulation, and its fix landed in #150580 (`eeb75c8`, merged on the update day at 07:24 UTC). **That fix is not in the 2026.9.5 release.** The release commit `ec9c1a1` is dated 18:40 UTC the same day, yet `compare eeb75c8...ec9c1a1` reports `diverged`, 116 behind. The installed `dist` confirms it:

```js
function createPluginSourceCapture(execute) {
  const directory = fs.realpathSync(fs.mkdtempSync(
    path.join(sourceCaptureDirectory.getStore() ?? tmpdir(), "openclaw-plugin-build-")
  ));
```

No owner registration, no orphan reclamation, no total-size bound — matching the cause named in #150541. So the capture accumulation and the Codex retry loop compound: the loop supplies repeated 342 MB captures, and nothing bounds or reclaims them.

The reported trigger in #150541 was `SIGKILL`. Here there was no forced exit — the journal shows only a clean restart drain. So the accumulation path is reachable without a forced exit.

## Steps to reproduce

1. Run npm `stable` with the Codex plugin enabled and a Codex plugin project substantially larger than free space in `os.tmpdir()` (342 MB project, 7.6 GB tmpfs here).
2. Update from 2026.9.4 to 2026.9.5 and let the Gateway restart.
3. Observe `Codex resident catalog background update failed` repeating in the journal, with no prior occurrences.
4. Watch `os.tmpdir()` accumulate `openclaw-plugin-build-*` copies of the Codex project until the filesystem fills.
5. Observe agent turns failing with the session-write ENOSPC message.

## What I could not establish

`/tmp` was reclaimed before I captured a full inventory, so I cannot give the exact copy count that consumed the 6.5 GB; the arithmetic is consistent (roughly twenty copies) but unmeasured. I also observed that `/tmp` stopped growing while the Codex loop continued, so capture creation is tied to plugin reload rather than to every retry.

## Workaround

Disabling the Codex plugin (`config set plugins.entries.codex.enabled false`) stopped the loop. Removing the stale temp directories reclaimed 1 GB. A Gateway restart is still required to repair the dangling capture references from defect 4.

## Environment

- OpenClaw 2026.9.5 (`ec9c1a1`), npm global install, channel `stable`, updated from 2026.9.4
- The update itself reported success: `validating (202.46s) → activating (143.96s) → restarting (9.89s) → verifying (62.13s)`
- Node 24.20.0, Linux 6.12.107+deb13-amd64 (x64)
- `/tmp`: tmpfs, 7.6 GB
- State directory: ~2.0 GB
- `codex-cli` 0.118.0; `@openclaw/codex` 2026.9.5, matching core

### LINKED ISSUE #152886: [Bug]: Codex/model-catalog startup retains multi-GB plugin builds in /tmp, causing ENOSPC and inference failure (2026.9.5)
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

## Summary

After upgrading to OpenClaw 2026.9.5, starting the Gateway creates multiple
`/tmp/openclaw-plugin-build-*` trees plus an
`/tmp/openclaw-model-catalog-*` tree.

On this system, a single clean Gateway startup consumes approximately 2.8 GB
of a 3.9 GiB `/tmp` tmpfs before any user inference request is made.

The dominant payload is repeated copies of:

`@openai/codex-linux-x64`

Each full plugin-build tree is ~341 MB, of which ~324 MB is
`@openai/codex-linux-x64`.

The model-catalog temporary directory itself contains additional complete
plugin-build trees.

These temporary directories remain after startup. Repeated startup/catalog
activity can exhaust `/tmp`, after which the Codex plugin fails with ENOSPC,
retires, and OpenClaw inference becomes unavailable.

This is reproducible from an empty `/tmp`.

## Environment

- OpenClaw: 2026.9.5 (`ec9c1a1`)
- `@openclaw/codex`: 2026.9.5
- Install method: npm global install
- Node: v26.8.1
- OS: Debian 13 (Trixie)
- Architecture: x86_64
- `/tmp`: tmpfs, 3.9 GiB
- Gateway: systemd user service
- Codex plugin: official/trusted global plugin
- Codex `sessionCatalog.enabled`: true during primary reproduction

Relevant Codex config:

    {
      "enabled": true,
      "config": {
        "codexDynamicToolsLoading": "searchable",
        "codexDynamicToolsExclude": [],
        "sessionCatalog": {
          "enabled": true
        }
      }
    }

## Minimal reproduction

1. Stop Gateway.

2. Remove only abandoned OpenClaw temporary build/catalog directories:

    rm -rf /tmp/openclaw-plugin-build-* \
           /tmp/openclaw-model-catalog-*

3. Verify clean `/tmp`:

    $ df -h /tmp
    Filesystem  Size  Used  Avail  Use%  Mounted on
    tmpfs       3.9G  101M  3.8G   3%   /tmp

4. Verify that no matching directories exist:

    find /tmp -maxdepth 1 \
      \( -name 'openclaw-plugin-build-*' \
      -o -name 'openclaw-model-catalog-*' \) \
      -print

    # no output

5. Start Gateway:

    systemctl --user start openclaw-gateway.service

6. Do NOT issue an inference request or interact with the GUI.

7. Approximately two minutes later:

    $ df -h /tmp
    Filesystem  Size  Used  Avail  Use%  Mounted on
    tmpfs       3.9G  2.9G  953M   76%  /tmp

    $ du -sh /tmp/openclaw-plugin-build-* \
             /tmp/openclaw-model-catalog-*

    64K     /tmp/openclaw-plugin-build-0AUlJD
    341M    /tmp/openclaw-plugin-build-1vFFaV
    341M    /tmp/openclaw-plugin-build-2fKbka
    341M    /tmp/openclaw-plugin-build-bp4O9v
    69M     /tmp/openclaw-plugin-build-DPpS71
    64K     /tmp/openclaw-plugin-build-g1YdGc
    152K    /tmp/openclaw-plugin-build-iy6sBl
    69M     /tmp/openclaw-plugin-build-mO3CNw
    64K     /tmp/openclaw-plugin-build-s13v8e
    152K    /tmp/openclaw-plugin-build-WN7yIf
    341M    /tmp/openclaw-plugin-build-ywcugk
    1.4G    /tmp/openclaw-model-catalog-yTVg5F

No user inference request was required to produce this.

## Contents of a ~341 MB build

For example:

    $ du -h --max-depth=5 /tmp/openclaw-plugin-build-1vFFaV |
      sort -h | tail

    3.3M  .../node_modules/@openclaw/codex
    7.7M  .../node_modules/zod
    324M  .../package-2
    324M  .../package-2/node_modules
    324M  .../package-2/node_modules/@openai
    324M  .../package-2/node_modules/@openai/codex-linux-x64
    324M  .../package-2/node_modules/@openai/codex-linux-x64/vendor
    341M  /tmp/openclaw-plugin-build-1vFFaV

The payload includes:

    @openai/codex-linux-x64/vendor/x86_64-unknown-linux-musl/
      codex-resources/
      codex-path/
      bin/

The `openclaw-model-catalog-*` directory contains additional nested
`openclaw-plugin-build-*` directories. In this reproduction it contained
four ~341 MB builds:

    341M .../openclaw-plugin-build-gNvE87
    341M .../openclaw-plugin-build-T18ZR0
    341M .../openclaw-plugin-build-tl8X3s
    341M .../openclaw-plugin-build-wuxyae
    1.4G /tmp/openclaw-model-catalog-yTVg5F

Each nested build again contained approximately 324 MB of
`@openai/codex-linux-x64`.

## Runtime behavior

Gateway itself initially starts successfully:

    [gateway] http server listening (... codex ...; 22.8s)
    [gateway] ready

The initial Codex catalog request can also succeed:

    [session-catalog] slow Codex catalog page producer ...
    outcome=resolved
    origin=cold
    ...
    controlClientRequestMs=2179

A short time later, the following begins appearing:

    [agent/embedded] Codex resident catalog background update failed
    error="thread/read transport failed after request write:
    codex app-server client is closed"

This message then repeats.

## Failure when `/tmp` becomes full

During the original occurrence `/tmp` reached ~97% while the root filesystem
still had ~69 GB free and ample free inodes.

Codex subsequently failed during plugin loading with:

    Error: ENOSPC: no space left on device, write

OpenClaw then reported:

    Plugin codex is retiring

and inference became unavailable.

Removing only the abandoned:

    /tmp/openclaw-plugin-build-*
    /tmp/openclaw-model-catalog-*

directories reduced `/tmp` from ~97% to ~3%, after which Codex could load
again.

## `sessionCatalog.enabled=false` negative test

I also repeated the test with:

    plugins.entries.codex.config.sessionCatalog.enabled=false

This does NOT prevent the large temporary build allocation.

Starting from a cleaned `/tmp`, Gateway startup still increased `/tmp`
usage from approximately 101 MB to 2.6 GB and recreated multiple
`openclaw-plugin-build-*` directories plus an approximately 1 GB
`openclaw-model-catalog-*` directory.

Therefore disabling the user-facing native Codex session catalog is not a
workaround for the underlying temporary-build behavior.

The setting has since been restored to `true`.

## Additional observation

During an earlier reproduction, after the temporary directories had been
created, `lsof +D /tmp` showed no open handles for the
`openclaw-plugin-build-*` or `openclaw-model-catalog-*` trees.

This suggests these are retained/abandoned temporary build artifacts rather
than files that need to remain open for the running Gateway, although I have
not verified the intended lifecycle in the implementation.

## Expected behavior

Temporary plugin/model-catalog construction should either:

1. clean up its staging trees once construction/catalog discovery completes,
2. reuse an existing prepared build instead of repeatedly unpacking the
   ~324 MB Codex platform package, or
3. retain only the artifacts actually required by the running process.

A normal Gateway startup should not consume several GB of `/tmp`, and
temporary catalog construction should not be capable of exhausting `/tmp`
and disabling inference.

## Actual behavior

A clean Gateway startup can retain approximately 2.5–2.8 GB of temporary
plugin/model-catalog builds on this system.

The same large Codex platform payload is duplicated several times, including
inside the model-catalog temporary workspace.

When `/tmp` fills, Codex fails with ENOSPC, the plugin retires, and inference
becomes unavailable.

### OpenClaw version

26.9.5

### Operating system

OS: Debian 13 (Trixie) - Architecture: x86_64

### Install method

nem global | Node: v26.8.1

### Model

n/a occurs before first inference

### Provider / routing chain

n/a occurs before first inference

## Related Codex lifecycle symptom

There are existing reports concerning Codex app-server/shared-client
lifecycle failures, including the same general
"codex app-server client is closed" class of error.

I am filing this separately because the multi-GB temporary-build retention
and resulting ENOSPC failure appear to be a distinct problem.

The app-server closure may be related, but this report does not assume that
it is the root cause.

### Logs

```shell

```

### Screenshots, recordings, and evidence

_No response_

## Impact

High on systems where `/tmp` is tmpfs or otherwise space-constrained:

- several GB consumed during normal Gateway startup/catalog preparation
- ENOSPC despite substantial free space on the root filesystem
- Codex plugin retirement
- loss of inference
- repeated copies of the ~324 MB Codex native package consume most of the
  temporary space

This is particularly problematic because the resulting ENOSPC initially
looks like ordinary disk exhaustion even though the persistent filesystem
has ample capacity.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by steipete**
Fixes #152689, fixes #152886. Related: #152993 and #153009 (closed duplicates).

## What Problem This Solves

After updating to 2026.9.5, catalog preparation can retain multi-GB plugin captures and exhaust temporary storage, while resident Codex observations can attempt metadata reads through retired clients.

## User Impact

An updated Gateway bounds live catalog capture retention and cleans up failed or replaced generations. A closed-client observation records one deferral and recovers through the current catalog owner; failed background checks wait for fresh activity or the next safety cycle. No configuration change is required. This change does not delete historical captures left by older killed processes.

## Scope

Builds on #153041 (merged), by @shakkernerd, at `c7fa3d9b842fc9986c91bbc39f3918e823405a0b`. This branch is rebased onto `5ca92f8dd27a576d7d3ec0206153f4ecbb782c02`. Main's final `templateModelRegistry.getAll()` scope block is preserved byte-for-byte, exactly once, with no diff on that block.

The residual here is one retained successful worker generation, explicit release of failed/replaced captures, worker-root cleanup after shutdown, bounded resident background retries, and one recorded deferral for observations interrupted by client closure.

The rebase resolved conflicts in the catalog worker and pool integration test. It keeps main's scope wrapper/comment and source-reuse assertions, followed by this PR's credential-refresh retention and shutdown-cleanup assertions. The earlier follow-up's wrapper-removal hunk is dropped because it would undo the merged fix; duplicate scope-only test instrumentation remains removed. Retention/retry production code is unchanged.

## Why This Change Was Made

The worker retained successive registry generations without releasing their ownership. Retain one successful generation, own widened discovery, and release failed or replaced acquisitions. Preserve each request's configuration and credential provenance when reusing preparation.

Attribute queued Codex observations to their physical source, stop rereading a closed source, and consume failed reconciliation triggers instead of rearming every idle tick. Capture retention and closed-client observations are separate owner defects; one warning is not evidence of one capture allocation.

Thanks @mrzeepek, @Conan-Scott, @ge0el, @cnflwzh, and @lishewen for the reports, and @zl0nline for tracing the unscoped capture path.

## Evidence

Blacksmith Testbox, Linux/Node 24.19, isolated state, free loopback port, and a 4 GiB tmpfs. Both cells ran two successful Codex turns followed by six alternating provider refreshes through `models.list`. The after cell installs the packed candidate core with the same published Codex plugin, preserving its large native dependency payload.

| Observation | Published 2026.9.5 | Candidate |
| --- | ---: | ---: |
| Nested worker captures after refresh | 150 | 22 on every refresh; 13 after idle reconciliation |
| Total tmpfs allocation | 3,986,014,208 bytes (3.71 GiB) | 777,887,744 bytes on every refresh; 419,700,736 bytes after idle |
| Codex plugin-load ENOSPC errors | 7 | 0 |
| Verified Codex replies | 2 | 2 |

The candidate replaced nine discovery captures on each provider switch and reclaimed all 54 discovery captures by the final observation. Fourteen managed main-process captures occupied 1,791,848,448 bytes outside the tmpfs and remained unchanged throughout; these are recorded separately so relocation is not counted as reclamation.

The closed-client loop was **not reproduced live on Testbox**. Its fix is proven at the client boundary: call the real client's `close()` before/during a written read, require one explanatory deferral, preserve `CODEX_APP_SERVER_REQUEST_TRANSPORT_INDETERMINATE` and `mayHaveWritten: true`, prohibit another request against that client, then publish fresh metadata on the next legitimate trigger. The regressions fail on the original code.

Upstream contract inspected at `openai/codex` revision `41e22fee981a63b3698df7ed36bad393cda24715`: [`thread_processor.rs:853,2790`](https://github.com/openai/codex/blob/41e22fee981a63b3698df7ed36bad393cda24715/codex-rs/app-server/src/request_processors/thread_processor.rs#L853) serves `thread/read` from persisted metadata and optional live state; [`lib.rs:1017`](https://github.com/openai/codex/blob/41e22fee981a63b3698df7ed36bad393cda24715/codex-rs/app-server/src/lib.rs#L1017) closes the connection RPC gate and schedules owner cleanup.

Initial local validation stopped before tests because the pre-rebase install had `@openclaw/fs-safe` 0.13.1 while main requires 0.16.0. `pnpm install --frozen-lockfile` reconciled this worktree without changing tracked files.

At head `b70ba783908f9db52a8b6ee6923ca6f69239b684`, all **88 focused tests passed** (30 worker/capture cases, including the complete pool integration file, and 58 Codex catalog/transport cases). Fresh independent P1 autoreview is **scoped-clean**. Main's exact final `getAll()` scope block is preserved once, and the combined pool regression passes.

`node scripts/check-changed.mjs --base 5ca92f8dd27a576d7d3ec0206153f4ecbb782c02` passed every step before extension lint, where declaration preparation hit the documented nested-checkout ancestor-`node_modules` error. The authorized direct extension-lint substitute passed after the canary below. All eight remaining guards passed separately; CI extension lint remains authoritative.

```text
$ node_modules/.bin/oxlint --tsconfig test/tsconfig/tsconfig.extensions.test.json <six changed extension files>
Canary: session-catalog-currency.ts:101:1: error eslint(no-debugger): `debugger` statement is not allowed
canary exit=1
Restored exact source bytes; real files: clean exit=0
```

Native CI attachment/precheck confirmed [run 35471981846](https://github.com/openclaw/openclaw/actions/runs/35471981846) for the exact head. The watcher stopped immediately after attachment; full CI completion was not awaited.

LOC delta from the rebased main: production **+173/-53**, tests **+132/-5**, docs **+7/-3**. The residual LOC delta is unchanged from the previous head; the merged scope fix is inherited from main and is not counted in this PR.

The earlier Testbox proof used source tree `5373a089308826217f4f3b3871d14701ee44cd79`, including the equivalent scope fix now merged in #153041. Its **150 captures / 3.71 GiB → 22 / 742 MiB** evidence still applies to the unchanged retention/retry implementation composed with that scope fix. The workload was not rerun; fresh focused suites, including the combined pool regression, and changed checks validate the rebase.

[Before Testbox run](https://github.com/openclaw/openclaw/actions/runs/35450829878) · [Candidate Testbox run](https://github.com/openclaw/openclaw/actions/runs/35454094107)

The initial inventory probe incorrectly required stable random directory names. The corrected verifier checks fixed counts/bytes, replacement retirement, and worker shutdown cleanup against the recorded observations; product requests and error assertions succeeded. The corrected Testbox verifier exited 0 and confirmed zero worker roots after Gateway shutdown.

<details>
<summary>Exact final retained capture inventory (allocated bytes)</summary>

Worker root: `tmp/openclaw-model-catalog-RUoZ9O`. Final set SHA-256: `5158f47b9e3ca5fedb4ce0177a7c7c896e7859e177a41dde2a219f0af2e7e1f8`. Total worker capture allocation: 358,653,952 bytes.

| Capture directory | Allocated bytes |
| --- | ---: |
| `openclaw-plugin-build-8WdZS2` | 357388288 |
| `openclaw-plugin-build-DZhTVG` | 106496 |
| `openclaw-plugin-build-F7xXmK` | 172032 |
| `openclaw-plugin-build-LtwyAt` | 126976 |
| `openclaw-plugin-build-TAiR6O` | 61440 |
| `openclaw-plugin-build-V0hPOe` | 61440 |
| `openclaw-plugin-build-Vp4IDZ` | 77824 |
| `openclaw-plugin-build-Wiepyc` | 172032 |
| `openclaw-plugin-build-bvbaFO` | 90112 |
| `openclaw-plugin-build-nz3j3K` | 65536 |
| `openclaw-plugin-build-spD1ri` | 106496 |
| `openclaw-plugin-build-xVx7hG` | 98304 |
| `openclaw-plugin-build-zGd8E0` | 126976 |

Managed main-process captures under `state/tmp/plugin-captures`, unchanged from startup through the final observation:

| Relative capture path | Allocated bytes |
| --- | ---: |
| `4d5faef8-592f-4411-8f14-f1b23f9414cf/captures/openclaw-plugin-build-mklkAO` | 358105088 |
| `92033941-3a28-4228-9ed9-af5543fb6399/captures/openclaw-plugin-build-1ngdPn` | 139264 |
| `92033941-3a28-4228-9ed9-af5543fb6399/captures/openclaw-plugin-build-22QEL4` | 204800 |
| `92033941-3a28-4228-9ed9-af5543fb6399/captures/openclaw-plugin-build-6mLrOI` | 204800 |
| `92033941-3a28-4228-9ed9-af5543fb6399/captures/openclaw-plugin-build-GO7eIG` | 358105088 |
| `92033941-3a28-4228-9ed9-af5543fb6399/captures/openclaw-plugin-build-JvnZ43` | 159744 |
| `92033941-3a28-4228-9ed9-af5543fb6399/captures/openclaw-plugin-build-Pr0KKl` | 358105088 |
| `92033941-3a28-4228-9ed9-af5543fb6399/captures/openclaw-plugin-build-WSAwSZ` | 358109184 |
| `92033941-3a28-4228-9ed9-af5543fb6399/captures/openclaw-plugin-build-iEWoTv` | 98304 |
| `92033941-3a28-4228-9ed9-af5543fb6399/captures/openclaw-plugin-build-jfMcdn` | 94208 |
| `92033941-3a28-4228-9ed9-af5543fb6399/captures/openclaw-plugin-build-kPIEvZ` | 122880 |
| `92033941-3a28-4228-9ed9-af5543fb6399/captures/openclaw-plugin-build-lcN1G0` | 139264 |
| `92033941-3a28-4228-9ed9-af5543fb6399/captures/openclaw-plugin-build-rqdMxt` | 159744 |
| `f7ba0437-2da0-4dd6-afbe-9b0a8a4c2ee7/captures/openclaw-plugin-build-sE35zj` | 358100992 |

</details>

## Landing review disposition

The latest ClawSweeper review covers exact head `41ff6d5649b28899fa144cbceb3762ac71d48b1e` at 2026-09-20 00:08 UTC and reports no actionable correctness or security findings, no before-merge actions, and no new Rank-up moves. The independent recorded Codex round-4 review is scoped-clean at the requested P0/P1 threshold. Its scope does not independently reverify the earlier rebase comparison or rerun the recorded tests.

Rank-up move: confirm the published 2026.9.5 updater against the combined candidate. **Skipped in this authorized landing lane**, which reuses the recorded runtime proof and exact-head CI. The earlier Testbox workload proves bounded captures and working plugin-backed turns after installing the packed candidate, but it does not prove the published updater transition. That compatibility proof remains a gap; this disposition does not claim it was run or passed. No new runtime proof or ClawSweeper rerun was performed for landing.

### CODE REVIEW

**Comment by steipete** [comment]
Merged via squash.

- Prepared head SHA: [41ff6d5649b28899fa144cbceb3762ac71d48b1e](https://github.com/openclaw/openclaw/pull/153038/commits/41ff6d5649b28899fa144cbceb3762ac71d48b1e)
- Landed commit: [1c4ee884396e509cc63abe87669e279e4e7d313c](https://github.com/openclaw/openclaw/commit/1c4ee884396e509cc63abe87669e279e4e7d313c)

**Comment by safrano9999** [comment]
🦞 Confirming the pre-fix capture-retention symptom on 2026.9.5 with 5 GiB under `openclaw-model-catalog-*`; this merged fix has not been tested on our installation.
