### PR TITLE
fix(cron): ignore malformed persisted jobs

### LINKED ISSUE #51871: [Bug]: Control UI: Cron jobs not displayed in dashboard (2026.3.13)
### Bug type

Regression (worked before, now fails)

### Summary

**Version:** OpenClaw 2026.3.13 (61d171a)
**OS:** Raspberry Pi 5, Linux (Debian), systemd service
**Install:** npm global

**Bug:**
Cron-Aufgaben werden im Dashboard (Control UI) nicht angezeigt — 
die Seite bleibt leer. 

**jobs.json ist valid:**
- Datei vorhanden: ~/.openclaw/cron/jobs.json
- JSON valid (python3 json.load OK)
- Jobs laufen korrekt (lastRunStatus: "ok", cron.runs im Log aktiv)
- openclaw cron list zeigt alle Jobs korrekt an

Alternativ gibt es auch den Discord (Link im CHANGELOG erwähnt) falls du lieber dort fragst — manchmal reagieren die Maintainer dort schneller.

### Steps to reproduce

**Reproduced:** Hard refresh, anderer Browser — kein Unterschied.
openclaw doctor --fix hat keine Cron-Migration durchgeführt.

### Expected behavior

should show all cron_jobs in dashboard

### Actual behavior

does not show cron_jobs in dashboard

### OpenClaw version

2026.3.13 (61d171a)

### Operating system

Linux (Debian)

### Install method

_No response_

### Model

all

### Provider / routing chain

all

### Additional provider/model setup details

_No response_

### Logs, screenshots, and evidence

```shell

```

### Impact and severity

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yfge**
## Summary

- Closes #51871.
- Quarantine malformed persisted cron rows into `jobs-quarantine.json` before sanitizing active `jobs.json`, so agents that later rewrite cron config keep only canonical valid jobs without silently deleting recoverable raw rows.
- Preserve split runtime metadata (`state`, `updatedAtMs`, `scheduleIdentity`) plus original `sourceIndex`, including duplicate malformed rows and legacy `jobId` rows.
- Block later cron persists until pending quarantine succeeds; after it succeeds, force a full config/state sanitize even for state-only callers.
- Report quarantine files from `openclaw doctor`, and document the runtime quarantine/doctor review path.

## Verification

- `pnpm test src/cron/service/store.test.ts src/cron/service/store.load-missing-session-target.test.ts src/cron/store.test.ts src/commands/doctor-cron-store-migration.test.ts src/commands/doctor-cron.test.ts ui/src/ui/controllers/cron-filters.test.ts ui/src/ui/controllers/cron.test.ts ui/src/ui/app-render.helpers.node.test.ts ui/src/ui/app-settings.refresh-active-tab.node.test.ts`
- `node scripts/run-tsgo.mjs -p tsconfig.core.json --incremental --tsBuildInfoFile .artifacts/tsgo-cache/core.tsbuildinfo && node scripts/run-tsgo.mjs -p test/tsconfig/tsconfig.core.test.json --incremental --tsBuildInfoFile .artifacts/tsgo-cache/core-test.tsbuildinfo`
- `node scripts/run-oxlint.mjs --tsconfig config/tsconfig/oxlint.core.json src/cron/store.ts src/cron/service/store.ts src/cron/service/state.ts src/commands/doctor-cron.ts src/cron/store.test.ts src/cron/service/store.test.ts src/cron/service/store.load-missing-session-target.test.ts src/commands/doctor-cron.test.ts src/commands/doctor-cron-store-migration.test.ts`
- `git diff --check`
- `pnpm exec oxfmt --check --threads=1 src/cron/store.ts src/cron/store.test.ts src/cron/service/store.ts src/cron/service/state.ts src/cron/service/store.test.ts src/cron/service/store.load-missing-session-target.test.ts src/commands/doctor-cron.ts src/commands/doctor-cron.test.ts src/commands/doctor-cron-store-migration.test.ts docs/automation/cron-jobs.md docs/cli/cron.md docs/gateway/doctor.md`
- `pnpm docs:list`
- `pnpm check:changed` reached core lint but failed because `tsgolint` segfaulted while parsing `node_modules/openai/index.d.mts`; targeted lint/type/tests above passed after that.
- autoreview: clean, no accepted/actionable findings.

## Real behavior proof

Behavior addressed: malformed persisted cron rows are automatically removed from the active runtime store only after they are copied into the quarantine sidecar, while valid jobs continue to load and persist normally.

Real environment tested: local OpenClaw checkout on macOS, with temporary cron stores in Vitest and focused cron service/store tests covering malformed rows, duplicate rows, legacy `jobId`, split state, quarantine failure recovery, and doctor reporting.

Exact steps or command run after this patch: the verification commands listed above were run after the final patch.

Evidence after fix: copied live terminal output from the Gateway repro plus focused tests. The live `openclaw cron list --json` output showed only the valid job after the malformed row was skipped/quarantined:

```text
$ OPENCLAW_STATE_DIR=/tmp/... OPENCLAW_CONFIG_PATH=/tmp/.../openclaw.json pnpm openclaw cron list --json --url ws://127.0.0.1:18890 --token <redacted>
{
  "jobs": [
    {
      "id": "job-ok",
      "name": "Daily",
      "payload": { "kind": "systemEvent", "text": "ping" },
      "state": { "nextRunAtMs": 1779699600000 }
    }
  ],
  "total": 1,
  "hasMore": false
}

cron: sanitized active jobs.json after quarantining malformed persisted jobs
```

Focused tests also assert active `jobs.json` contains only valid jobs after successful quarantine, `jobs-quarantine.json` keeps the malformed raw rows and runtime metadata, repeated failures do not rewrite or spam warnings, and doctor reports quarantined rows for manual review.

Observed result after fix: valid cron jobs remain usable; malformed persisted rows are quarantined outside active runtime config; later agent/config writes cannot delete malformed rows before quarantine succeeds.

What was not tested: a fresh browser screenshot/video of the Control UI was not captured for this rewrite; UI coverage is through the existing cron controller tests included above.

### CODE REVIEW

**Comment by yfge** [comment]
Addressed the review findings in cfd5b0abc68f9794aa38b9d08b5a968dfb80b699:

- Quarantined malformed persisted cron rows are now preserved across later config writes via `preserveConfigJobs`, while staying out of runtime `state.store.jobs`.
- Added regression coverage that calls `persist(state)` after loading valid + malformed rows and verifies the malformed raw rows remain in `jobs.json`.
- Added the Unreleased `CHANGELOG.md` fix entry.

Verification rerun:

- `pnpm test src/cron/service/store.test.ts ui/src/ui/controllers/cron.test.ts ui/src/ui/app-render.helpers.node.test.ts ui/src/ui/app-settings.refresh-active-tab.node.test.ts`
- `pnpm exec oxfmt --check --threads=1 src/cron/service/store.ts src/cron/service/store.test.ts src/cron/service/state.ts src/cron/service.test-harness.ts src/cron/store.ts ui/src/ui/controllers/cron.ts CHANGELOG.md`
- `pnpm check:changed` still fails in the existing `tsgo:core` baseline dependency/type drift outside this PR surface; touched cron/UI files are clear.

**Comment by yfge** [comment]
Rebased this branch onto current `origin/main` and resolved the `CHANGELOG.md` conflict, preserving the malformed persisted cron-job quarantine/preservation behavior.

Pushed updated head: `c400bba52c`.

Validation after rebase:
- `pnpm test src/cron/service/store.test.ts ui/src/ui/controllers/cron.test.ts ui/src/ui/app-render.helpers.node.test.ts ui/src/ui/app-settings.refresh-active-tab.node.test.ts` ✅
- `pnpm exec oxfmt --check --threads=1 src/cron/service/store.ts src/cron/service/store.test.ts src/cron/service/state.ts src/cron/service.test-harness.ts src/cron/store.ts ui/src/ui/controllers/cron.ts CHANGELOG.md` ✅
- `pnpm check:changed` ✅

**Comment by yfge** [comment]
Addressed the malformed-payload review hole in 0136ead23f.

- `src/cron/service/store.ts` now only hydrates `systemEvent` payloads with a string `text` and `agentTurn` payloads with a string `message`.
- Added regression coverage for persisted jobs with `payload: { kind: "agentTurn" }` and `payload: { kind: "systemEvent" }` so incomplete variants stay quarantined/preserved instead of reaching runtime/UI consumers.

Verification rerun:
- `pnpm test src/cron/service/store.test.ts ui/src/ui/controllers/cron.test.ts ui/src/ui/app-render.helpers.node.test.ts ui/src/ui/app-settings.refresh-active-tab.node.test.ts` ✅
- `pnpm format:check -- src/cron/service/store.ts src/cron/service/store.test.ts src/cron/service/state.ts src/cron/service.test-harness.ts src/cron/store.ts ui/src/ui/controllers/cron.ts CHANGELOG.md` ✅
- `pnpm check:changed` ✅

**Comment by yfge** [comment]
Rebased this branch onto current `origin/main` and resolved the Control UI cron edit conflict by combining the newer safe `getCronJobPayload` parsing with schedule-kind guarding for malformed persisted rows.

Updated head: `1563519dc5`.

Validation after rebase:
- `pnpm test src/cron/service/store.test.ts` ✅
- `pnpm exec oxfmt --check --threads=1 ui/src/ui/controllers/cron.ts src/cron/service/state.ts src/cron/service/store.ts src/cron/store.ts src/cron/service.test-harness.ts src/cron/service/store.test.ts` ✅

**Comment by yfge** [comment]
Follow-up CI/lint fix: removed the now-unused `resolveCronJobPayloadKind` helper left over from the rebase conflict resolution.

Updated head: `381b8e5819`.

Additional validation:
- `pnpm exec oxfmt --check --threads=1 ui/src/ui/controllers/cron.ts` ✅
- `pnpm lint` ✅

**Comment by yfge** [comment]
Addressed the schedule-body validation gap in `dd3c6b4a0c`.

- `src/cron/service/store.ts` now rejects kind-only persisted schedules unless the required variant body is present (`at`, `everyMs`, or `expr`).
- `src/cron/service/store.test.ts` adds regression coverage for persisted `schedule: { kind: "cron" }`, `schedule: { kind: "every" }`, and `schedule: { kind: "at" }` rows so they stay quarantined/preserved instead of hydrating into runtime/UI consumers.

Verification rerun:
- `pnpm test src/cron/service/store.test.ts ui/src/ui/controllers/cron.test.ts ui/src/ui/app-render.helpers.node.test.ts ui/src/ui/app-settings.refresh-active-tab.node.test.ts` ✅
- `pnpm exec oxfmt --check --threads=1 src/cron/service/store.ts src/cron/service/store.test.ts src/cron/service/state.ts src/cron/service.test-harness.ts src/cron/store.ts ui/src/ui/controllers/cron.ts` ✅
- `pnpm check:changed` still hits the existing unrelated baseline failure `TS2307: Cannot find module 'web-tree-sitter'` in `src/infra/command-explainer/extract.ts:1` and `src/infra/command-explainer/tree-sitter-runtime.ts:4`; no touched cron/UI file failures remain.

**Comment by yfge** [comment]
Addressed the legacy interval compatibility regression from comment 4363090557 in 5167e18bd1.

The loader now accepts and normalizes persisted `every` schedules where `everyMs` and `anchorMs` are numeric strings (for example `everyMs: "30000"`) instead of quarantining those already-supported legacy rows. Added regression coverage for the string interval path.

Verification:
- `pnpm test src/cron/service/store.test.ts src/cron/schedule.test.ts ui/src/ui/controllers/cron.test.ts ui/src/ui/app-render.helpers.node.test.ts ui/src/ui/app-settings.refresh-active-tab.node.test.ts`
- `pnpm exec oxfmt --check --threads=1 src/cron/service/store.ts src/cron/service/store.test.ts src/cron/service/state.ts src/cron/service.test-harness.ts src/cron/store.ts src/cron/normalize.ts ui/src/ui/controllers/cron.ts CHANGELOG.md`
- `pnpm check:changed`

**Comment by yfge** [comment]
Rebased this branch onto current `origin/main` and resolved the `src/cron/store.ts` conflict by preserving both the newer state-only split-store write path and this branch's quarantined raw-job preservation (`preserveConfigJobs`).

Updated head: `97c3fce83f`.

Validation:
- `git diff --check origin/main...HEAD` ✅
- Targeted test command attempted: `pnpm test src/cron/service/store.test.ts src/cron/schedule.test.ts ui/src/ui/controllers/cron.test.ts ui/src/ui/app-render.helpers.node.test.ts ui/src/ui/app-settings.refresh-active-tab.node.test.ts`
  - blocked locally because this fresh worktree has no `node_modules` (`Cannot find module 'vitest/package.json'`) and the host is nearly out of disk; no test failure from the code path was observed.

**Comment by yfge** [comment]
Follow-up after the new CI run: the merge conflict is resolved and the branch is mergeable. The remaining failing check is `checks-node-core-fast`, timing out in unrelated `src/auto-reply/reply/followup-delivery.test.ts` (`delivers distinct replies when originating channel resolves the provider`, 120s). The aggregate `checks-node-core` failure is from that shard.

I tried to rerun failed jobs, but this token/user does not have permission to rerun the workflow (`Must have admin rights to Repository`).

**Comment by yfge** [comment]
The schedule-less row follow-up is addressed on the current branch head.- malformed persisted rows are now quarantined during store load before they can reach the dashboard job list- the branch adds a regression that covers the missing-schedule / dashboard-breaking case in `src/cron/service/store.test.ts`- string `interval` schedules from legacy rows are also preserved during normalization so they do not get dropped on reloadI did not push anything new here today because the PR branch already contains that repair line.

**Comment by yfge** [comment]
Addressed the schedule-less row gap in `13a4059`.

What changed:
- `ui/src/ui/controllers/cron.ts`: `getVisibleCronJobs()` now drops jobs whose schedule kind cannot be resolved, so malformed rows cannot reach `renderJob()` and trip `formatCronSchedule()`.
- `ui/src/ui/controllers/cron-filters.test.ts`: added a regression covering an unsupported/missing schedule row.

Verification:
- `pnpm test ui/src/ui/controllers/cron-filters.test.ts ui/src/ui/controllers/cron.test.ts ui/src/ui/app-render.helpers.node.test.ts ui/src/ui/app-settings.refresh-active-tab.node.test.ts`
- `pnpm exec oxfmt --check --threads=1 ui/src/ui/controllers/cron.ts ui/src/ui/controllers/cron-filters.test.ts`

**Comment by yfge** [comment]
Rebased this branch onto current `origin/main` in `eb642f9a56`.

Validation:
- `pnpm exec oxfmt --check --threads=1 src/cron/service/store.ts src/cron/service/store.test.ts ui/src/ui/controllers/cron.ts ui/src/ui/controllers/cron-filters.test.ts CHANGELOG.md`

Targeted test rerun attempted:
- `pnpm test src/cron/service/store.test.ts ui/src/ui/controllers/cron-filters.test.ts -- -t "malformed|schedule"`
- blocked in this local worktree by dependency resolution before tests loaded: `Cannot find package '@openclaw/fs-safe/config' imported from src/infra/fs-safe-defaults.ts`.

The push should also pick up the current real-behavior-proof workflow script from `main`, replacing the stale-base `MODULE_NOT_FOUND` failure seen on the previous head.

**Comment by yfge** [comment]
I rechecked this one. The quarantine/UI-guard direction still looks good, but I think there are two remaining follow-ups before merge:

1. add after-fix real behavior proof showing a malformed persisted cron row no longer breaks the dashboard / cron list flow
2. please address the repeated malformed-row warning case ClawSweeper called out, so the same quarantined bad row does not spam logs on repeated reloads

If you update the branch for those and refresh the PR body with the proof, I’m happy to re-review.

**Comment by yfge** [comment]
Addressed the repeated malformed-row warning follow-up in `0749c279c8`.

What changed:
- added process-level dedupe for malformed persisted-job quarantine warnings, mirroring the existing missing-`sessionTarget` pattern
- keeps malformed rows quarantined/preserved, but avoids re-emitting the same warning on every `forceReload` timer tick while the bad row still exists on disk
- added regression coverage that reloads the same malformed row multiple times and asserts the warn fires once

Verification:
- `pnpm test src/cron/service/store.test.ts src/cron/service/store.load-missing-session-target.test.ts`
- `pnpm exec oxfmt --check --threads=1 src/cron/service/store.ts src/cron/service/state.ts src/cron/service/store.test.ts`

Still outstanding before merge: after-fix real behavior proof showing a malformed persisted row no longer breaks the dashboard / cron list flow.

**Comment by yfge** [comment]
Fixed the CI typecheck regression from the malformed-warning follow-up in `521a5718e1`.

Change made:
- initialized `warnedMalformedPersistedJobKeys` in `createMockCronStateForJobs`, matching the required `CronServiceState` field added by the warning-dedupe change.

Verification:
- `pnpm exec oxfmt --check --threads=1 src/cron/service.test-harness.ts` ✅
- `pnpm tsgo:core && pnpm tsgo:core:test` attempted, but this local worktree is blocked by existing unrelated type errors outside this PR area (for example `src/media-understanding/attachments.cache.ts`, `src/media/store.ts`, and missing `@openclaw/fs-safe/*` package types).
- targeted cron tests attempted, but this local worktree cannot collect them because `@openclaw/fs-safe/config` is missing from the worktree dependency resolution.

CI should now clear the specific TS2741 failure from `src/cron/service.test-harness.ts`.

**Comment by yfge** [comment]
Review follow-up: I re-checked the current review thread. The remaining blocker is still the requested real behavior proof showing a malformed jobs.json no longer blanks the cron dashboard/list; I don’t see another code-review delta to apply from the open comments themselves.\n\nI’m treating this PR as waiting on that proof artifact before re-review.

**Comment by yfge** [comment]
I rechecked the open review comments here. I do not see a new code-level blocker in the latest diff; the remaining blocker is still after-fix real behavior proof.

Please update the PR body with one concrete proof item showing that a malformed persisted cron row no longer blanks the cron dashboard/list (for example: redacted screenshot, screen recording, terminal output, or logs from a real malformed jobs.json repro).

Once that proof is attached and the PR body is updated, ClawSweeper should re-review automatically; if it does not, a maintainer can trigger `@clawsweeper re-review`.

**Comment by RomneyDa** [comment]
Heads up: this PR needs to be updated against current `main` before the new required Dependency Guard check can pass.

**Comment by steipete** [comment]
Landed via squash merge onto main.

- PR head before merge: 24a9736ae1e6e2e89900d382f1458b1b14c5337a
- Merge commit: f634062f351c333664f92890757e17e1fdb3bb88
- Proof: focused cron/doctor/UI tests, tsgo focused types, oxlint focused lint, oxfmt check, git diff --check, pnpm docs:list, autoreview clean, GitHub real behavior proof, build/docs/lint/type/security/quality checks, cron shard, and Windows rerun green.
- Known CI note: checks-node-agentic-agents was red here and on recent main with unrelated module/mock failures outside the touched cron/doctor/docs/UI cron files.

Thanks @yfge.
