### ISSUE TITLE
v2026.3.8: Crash loop on startup — plugin errors, SyntaxErrors, V8 JIT crashes

### ISSUE THREAD

**Issue by russellweiss** [openclaw/openclaw#41193]
## Summary

After upgrading from v2026.2.26 to v2026.3.8, the gateway enters a crash loop on startup. **32 crashes in ~50 minutes.** v2026.2.26 was stable (19 crashes over 4 days, mostly cold-start JIT). The gateway is essentially unusable on 2026.3.8.

## Environment

- **OS:** Ubuntu 24.04.4 LTS
- **Kernel:** 6.17.0-14-generic (HWE)
- **Node:** v22.22.0
- **CPU:** 13th Gen Intel Core i9-13900
- **RAM:** 60GB DDR5
- **OpenClaw:** upgraded from 2026.2.26 → 2026.3.8
- **Gateway mode:** local, bind=lan, TLS enabled (self-signed)
- **Plugins enabled:** telegram, discord, mattermost

### 1. Telegram plugin — Zod v4 incompatibility
```
[gateway] [plugins] telegram failed to load: TypeError: _zod.z.number(...).int is not a function
```
`.int()` doesn't exist in Zod v4. This crashes the plugin on every startup.

### 2. Discord plugin — undefined property access
```
[gateway] [plugins] discord failed to load: TypeError: Cannot read properties of undefined (reading 'Optional')
```
Possibly related to #34540 (reported on 2026.3.2, not fixed in 2026.3.8).

### 3. Telegram plugin — second variant
```
[gateway] [plugins] telegram failed to load: TypeError: Cannot read properties of undefined (reading 'run')
```

### 4. SyntaxErrors in dist bundle
```
[openclaw] Failed to start CLI: SyntaxError: Duplicate parameter name not allowed in this context
[openclaw] Failed to start CLI: SyntaxError: Illegal 'use strict' directive in function with non-simple parameter list
```
These abort the gateway subprocess before it can even bind a port.

### 5. Config schema error
```
Failed to read config at openclaw.json: TypeError: Cannot read properties of undefined (reading 'optin')
```
Non-fatal, but logged on every start. Config was valid on v2026.2.26.

### 6. V8 JIT crashes (LoadIC_Miss)
```
# Fatal error in , line 0
# Check failed: static_cast<unsigned>(index) < static_cast<unsigned>(length()).
V8_Fatal(char const*, ...)
v8::internal::Runtime_LoadIC_Miss(int, unsigned long*, v8::internal::Isolate*)
```
These occurred on v2026.2.26 too (~5/day) but are dramatically more frequent on 2026.3.8 (~6 in 50 minutes). The new dist bundle's code patterns appear to trigger the Turboshaft JIT bug more aggressively.

## Crash statistics

| Version | Period | Total crashes | V8 JIT crashes | Plugin/Syntax crashes |
|---------|--------|--------------|----------------|----------------------|
| 2026.2.26 | 4 days | 19 | ~6 | ~13 (WeakMap plugin error) |
| 2026.3.8 | 50 min | 32 | 6 | ~26 |

## Steps to reproduce

1. Install v2026.3.8 with telegram + discord plugins enabled
2. Run `openclaw gateway run`
3. Gateway crashes within 1-15 seconds on most attempts
4. Occasional successful starts, but runtime V8 crashes follow within minutes

## Workaround

Downgraded back to v2026.2.26 which is stable.

## Related issues

- #34540 — Discord plugin ReferenceError in 2026.3.2
- #34539 — structuredClone FATAL ERROR
- #26539 — uncaughtException + IPv6 crash

**Comment by steipete** [comment]
Closing this as outdated / not currently reproducible enough to act on.

What I checked:

- This report is for OpenClaw v2026.3.8 after an upgrade from v2026.2.26. Current main is well past that release line.
- The issue combines several independent failure classes: Telegram plugin load errors, Discord plugin load errors, bundle SyntaxErrors, config-schema errors, and V8/JIT crashes. There is no single actionable root cause here now.
- The related narrower issues called out here (#34540, #34539, #26539) are already closed after going stale / no fresh latest-version reproduction.
- Searches for the exact reported signatures did not find a newer active report that ties these symptoms to the current release.

If this still happens on the latest OpenClaw, please reopen or create a new issue with one crash signature per issue. The most useful payload is:

```bash
openclaw --version
node --version
openclaw gateway status --deep
openclaw gateway restart
```

Then include the fresh post-restart gateway log and the exact plugin/channel config involved, with secrets redacted.
