### PR TITLE
fix(agents): constrain sessions_spawn agentId schema with description and enum

### LINKED ISSUE #149550: sessions_spawn: agentId is advertised as an unconstrained string but only main is accepted
### Bug type

Behavior bug (incorrect output/state without crash)

### Beta release blocker

No

### Summary

The sessions_spawn tool schema delivers agentId to the model as an optional free-form string with no enum and no description, while the gateway rejects every value except main at runtime. The constraint is discoverable only by violating it.

### Steps to reproduce

1. Declare more than one agent under agents.list in openclaw.json, for example main and builder.
2. From an agent session, call sessions_spawn with agentId set to one of the non-main names, for example builder.
3. Observe the forbidden response quoted under Actual behavior.

The schema the model receives for that parameter is exactly:

```json
"agentId": { "type": "string" }
```

Optional (absent from required). No enum, no allowed-values list, no description text.

### Expected behavior

The schema communicates the constraint: an enum of accepted values, or a description naming them, or the parameter omitted where it cannot vary.

This matters more for a tool-calling model than for a human caller. A parameter offered as an unconstrained string, on a gateway whose own configuration declares several agents by name, is one a model will reasonably populate with one of those names.

### Actual behavior

The call is rejected by the gateway:

```json
{"status":"forbidden","error":"agentId is not allowed for sessions_spawn (allowed: main)","role":"builder"}
```

The value used, builder, is a legitimately declared agent under agents.list in openclaw.json. So the configuration declares the agent, the tool schema accepts the parameter without constraint, and the gateway forbids the combination. Nothing in the tool schema or its description communicates the allowed set.

### OpenClaw version

2026.6.34

### Operating system

Raspberry Pi OS 64-bit (aarch64)

### Install method

Docker, via docker compose

### Model

deepseek/deepseek-v4-flash

### Provider / routing chain

deepseek/deepseek-v4-flash primary with minimax/MiniMax-M2.7 as fallback. The rejection is returned by the gateway as a forbidden status rather than by the model provider.

### Additional provider/model setup details

agents.list declares four agents: main, research, builder, reviewer. main inherits the default model (deepseek/deepseek-v4-flash) with minimax/MiniMax-M2.7 as fallback; the three role agents are configured with minimax/MiniMax-M2.7 primary and deepseek/deepseek-v4-flash fallback. No API keys, tokens or passwords are included in this report.

### Logs

```shell
{"status":"forbidden","error":"agentId is not allowed for sessions_spawn (allowed: main)","role":"builder"}
```

### Screenshots, recordings, and evidence

The tool schema as held by the agent at the time of the call, quoted verbatim by the agent when asked to report it:

```json
"agentId": { "type": "string" }
```

Asked explicitly whether anything in that tool schema or its description states that only main is accepted, the agent answered no.

### Impact and severity

- Affected: any deployment that declares more than one agent under agents.list and instructs its orchestrator to delegate by role name.
- Severity: blocks workflow. In this deployment it failed a daily scheduled job.
- Frequency: deterministic whenever the model supplies agentId; in practice intermittent, since whether the model populates the optional parameter varies by turn.
- Consequence: the scheduled run was recorded as failed and its remaining steps did not run, even though a retry without agentId was accepted and the sub-agent completed its work. That downstream accounting behaviour is a separate defect and is being filed as its own issue, per the one-issue-per-submission rule.

### Additional information

The governance files injected into the orchestrator context name builder as an agent to delegate to, and agents.list declares it, so the model had two independent reasons to treat the value as valid and none to treat it as invalid.

Local workaround: an explicit instruction in the injected governance file never to pass agentId to sessions_spawn. This prevents the rejection.

Whether this is a regression is unverified. We have not tested an earlier version, so this is filed as a behavior bug rather than a regression.

### PR DESCRIPTION
**Pull request by SunnyShu0925**
Closes #149550

## What Problem This Solves

The `sessions_spawn` tool offered `agentId` as a free-form string with no description, so models filled in configured agent names (e.g. `builder`) that the gateway rejected. The fix adds a parameter description explaining the constraint for native, ACP, and collector runtimes.

- Problem: The schema for `agentId` was `Type.Optional(Type.String())` — no description. Models had no way to know which values the gateway accepts.
- Solution: Add a description explaining that `agentId` targets a configured agent, with runtime-specific omission behavior: native subagent defaults to the requester's agent, ACP uses `acp.defaultAgent` or fails if unset, and `collect=true` honors `tools.swarm.defaultAgentId`.
- What changed: `src/agents/tools/sessions-spawn-tool.ts` — replaced the bare `Type.Optional(Type.String())` with a described string. Updated 4 prompt snapshot fixtures to reflect the new schema.
- What did NOT change: Runtime validation logic, spawn execution, or the tool's top-level `description` text.

## Why This Change Was Made

An enum of configured agent ids was considered but rejected: it would exclude valid ACP harness targets (`codex`, `claude`, etc.) and advertise agents that native `allowAgents` policy may not permit. A description avoids both issues while giving the model enough context to avoid invalid values.

## User Impact

Models calling `sessions_spawn` now see parameter guidance explaining which agent ids are valid for each runtime, reducing invalid `agentId` rejections.

## Evidence

Production tool schema, produced with `node --import tsx` calling `createSessionsSpawnTool` (head `2edd037`):

```
$ node --import ./scripts/tsx.mjs --input-type=module <<'NODE'
import { createSessionsSpawnTool } from "./src/agents/tools/sessions-spawn-tool.js";

const tool = createSessionsSpawnTool({
  agentSessionKey: "agent:main:main",
  config: { agents: { entries: { main: { default: true }, builder: {}, reviewer: {} } } },
});

console.log(JSON.stringify(tool.parameters.properties.agentId, null, 2));
NODE

{
  "type": "string",
  "description": "Configured agent id; native allowAgents policy or ACP harness id (codex, claude, gemini, opencode)."
}
```

Prompt snapshot check passes after regenerating fixtures:

```
$ node --import ./scripts/tsx.mjs scripts/generate-prompt-snapshots.ts --check
Prompt snapshots are current (7 files).
```

## AI Assistance

This PR is AI-assisted. Used Codex CLI to analyze issue #149550, locate the unconstrained `agentId` schema in `src/agents/tools/sessions-spawn-tool.ts`, and implement the fix. Revised across two ClawSweeper review rounds: replaced the initial enum approach with a description-only schema to preserve ACP targets, then qualified the omission-default language to match runtime-specific behavior (ACP uses `acp.defaultAgent`, collector uses `tools.swarm.defaultAgentId`). The implementer understands the code: ACP runtime resolves omitted `agentId` via `resolveTargetAcpAgentId` which uses `acp.defaultAgent` or returns `target_agent_required`, not the requester's agent. Rebased onto origin/main to resolve CI drift; no code changes.

### CODE REVIEW

**Comment by SunnyShu0925** [comment]
@clawsweeper re-review.

**Comment by SunnyShu0925** [comment]
@clawsweeper re-review.

**Comment by SunnyShu0925** [comment]
CI on this push is red on two checks, both tracing to main HEAD `9edc73fc2f9` (#149737 "improve(doctor): reuse one metadata snapshot"), not to anything in this PR:

- **`check-test-types`** — `extensions/slack/src/monitor/provider.interop.test.ts:508` fails with `error TS2769` on `Buffer.concat(data)` (`ArrayBuffer | Buffer` not assignable to `WithImplicitCoercion<string | ArrayLike<number>>`).
- **`checks-node-changed-extensions-bundle-28`** — 85 unhandled errors in `extensions/slack/...`, all rooted in `Slack Socket Mode envelope guard requires the SDK acknowledgement sender`.

Both live entirely in the slack extension's Socket Mode code/tests introduced by #149737. This PR only touches `src/agents/tools/sessions-spawn-tool.ts` (agentId schema description/enum) and a few prompt-snapshot fixtures — no slack changes. The failures are deterministic (a type error + a runtime guard mismatch), not flaky, so re-running won't clear them.

`openclaw/ci-gate` is just the aggregate gate failing on the two above.

Leaving this here so reviewers know the red is inherited from main; it should clear once #149737's slack breakage is fixed on main and this branch rebases past it. The sessions_spawn schema change itself is unrelated and unaffected.
