### PR TITLE
test(tooling): accept Bun missing-module wording

### PR DESCRIPTION
**Pull request by steipete**
## What Problem This Solves

The direct-Bun tooling lane now follows Node's module-loading behavior for inline TypeScript type specifiers after oven-sh/bun#43062, but Bun and Node format the resulting missing-module error differently. The test asserted Node's error code text even though its contract is the dependency edge and failed resolution.

## User Impact

There is no runtime behavior change. The test now asserts the shared `Cannot find module` message while retaining the exact nonzero exit and unresolved eager-closure assertions.

## Evidence

- Direct custom Bun: `test/scripts/eager-import-closure.test.ts` passes 10/10.
- Node: the same file passes 10/10.
- The exact formerly loaded-timeout docs case passes in isolation under both runtimes; no code change was needed for that unrelated inventory result.
- `node scripts/check-changed.mjs` passes.
- Fresh Codex P0-P2 review reports no actionable finding.

### CODE REVIEW

**Comment by steipete** [comment]
Merged via squash.

- Prepared head SHA: [a23718f29307f2ed161523c44ae35a37fec0c5e3](https://github.com/openclaw/openclaw/pull/150860/commits/a23718f29307f2ed161523c44ae35a37fec0c5e3)
- Landed commit: [ada4d947e88433d86f1f5df7432c720af12295aa](https://github.com/openclaw/openclaw/commit/ada4d947e88433d86f1f5df7432c720af12295aa)
