### PR TITLE
fix(ui): prevent lost avatars and stuck identity saves

### PR DESCRIPTION
**Pull request by steipete**
## What Problem This Solves

Fixes an issue where users editing an agent's name and choosing an avatar could silently save only the name when they clicked Save before image decoding finished. Also fixes an identity editor that remained stuck on Saving after its Gateway connection dropped and reconnected during a save.

## Why This Change Was Made

The identity editor owned image conversion and saving independently. Save could snapshot the draft before its selected image existed, then reset the draft and retire that conversion. The pending conversion is now the selection's canonical owner: Save claims its busy state, waits for that exact selection, and checks the current operation before taking the draft snapshot. Failed or retired conversions cannot become partial saves.

The page's connection invalidation now releases the old save's busy state while retaining editable drafts. Existing generation checks still fence stale completions, and agent/client replacement still retires pending selections. Bitmap disposal is also paired with the successful decode in `finally`, including missing-canvas and drawing-error fallback paths.

Best-fix judgment: keep the existing config write coordinator and page connection owner; a new view-level busy flag or downstream retry would duplicate ownership. The numeric selection epoch is removed in favor of the actual pending operation. Production delta is **+50/-41 (net +9)**; tests are **+441/-8**, plus one changelog line. The growth represents pending-operation and resource ownership, with no new config, API, protocol, schema, dependency, or identity-clearing semantics.

The editor was introduced in #106058 (`9086389527b17e7e1ea5a2583f4a76948a4887c4`); its save-state reset was not added to the already-existing connection invalidator. This PR does not implement the independent null-clearing contract in #119930 or the hovercard refresh in #126392.

## User Impact

Saving a selected avatar together with other identity edits waits for conversion and sends them together. If conversion fails, the draft and visible error remain. After reconnect, the interrupted draft can be edited and retried. Existing set/replace-only behavior is unchanged.

## Evidence

Baseline: `6c10672d95072cc1a4b645c519a4513621cd940a`.

- Before the production patch: seven owner regression failures and two mocked Chromium failures, for premature update dispatch, stuck Saving after reconnect, and missing bitmap disposal. All are green after the repair.
- Final focused owner and sibling proof: **157 tests passed across 11 files**, including agent file lifecycle, profile avatar processing, and the config write coordinator. The reconnect cases live in a focused lifecycle file; they were reverified failing with the old invalidator before restoring the fix. No max-lines suppression was added.
- Chromium: **2/2 passed**, using a real PNG and native image decoding with controlled timing. Assertions cover the update payload, visible decoded image, reload, reconnect, draft editing, and successful retry. Transport and server state are mocked; these are not real-profile or real-Gateway results.
- Final full UI unit run: **10,821 passed, 67 skipped** across 756 files. An earlier candidate run had **10,819 passed, 2 failed, 67 skipped**; untouched main reproduced those exact two route/resource-base failures (**10,810 passed, 2 failed, 67 skipped**). Both minimal producer-before-consumer runs reproduce the failure, while the browser test alone passes. The serialized mock-Gateway fixture leaves an empty resource-base global in the shared test window. This remains a separate order-sensitive test-lifecycle follow-up; the passing final order does not mean this PR repaired it.
- Fresh structured Codex review: no P0 findings. Independent hands-on production review: no actionable findings.
- Complete changed-file gate: **passed**, including core-test and UI typechecks, type-aware lint, UI styles, i18n, formatting, and repository guards. The initial max-lines failure was fixed by moving the reconnect cases to their focused lifecycle file, not by adding a suppression.
- Hosted product CI is **skipped while this PR is a draft**; the local results above are not an exact-head hosted-CI claim. Re-run the normal PR checks when the live-proof blocker is resolved and the PR is ready for review.

**Draft / live-proof blocker:** real-profile Chrome verification remains outstanding. The configured extension relay is unavailable, the documented direct attachment fallback returns HTTP 403, and no usable Chrome approval window is available. No browser access policy was changed and no operator Gateway was modified. Do not treat the deterministic Chromium evidence as live-profile proof or this PR as merge-ready.

Before: Save dispatches before the selected image finishes decoding.

Before: Saving while the selected image is still pending

After: the image and name are saved together and the decoded avatar is visible.

After: saved image and display name

Before: reconnect leaves the interrupted editor stuck on Saving.

Before: Saving remains stuck after reconnect

After: reconnect retains the draft and enables editing and Save again.

After: editable draft and enabled Save after reconnect

All captures use synthetic QA data. The emoji input's right border is clipped in both before and after captures; named follow-up: migrate the constrained identity fields to canonical Settings input sizing after rendered-geometry proof. This PR does not claim to fix that existing layout defect.

### CODE REVIEW

**Comment by steipete** [comment]
Addressing the latest review and Rank-up moves: the changelog entry is retained under the maintainer's explicit instruction to include changelog notes for user-visible fixes. This is a scoped exception to the normal release-owned changelog workflow, not an overlooked request.

The net +9 production lines implement the selected-avatar pending-operation lifetime and bitmap cleanup; the former numeric epoch path was removed. No additional UI busy flag, retry path, config option, or protocol surface was introduced.

The PR remains a draft. Real-profile Chrome access was rechecked: the extension relay is unavailable and the documented direct attachment fallback still returns HTTP 403. The focused Chromium evidence uses a mocked Gateway and is not live-profile verification. Exact-head hosted product checks must run when the draft is promoted; skipped draft checks are not green CI. The review's 12 passing tests are useful owner regression evidence, not a live-browser result.
