### ISSUE TITLE
[Bug]: Control UI assets missing from npm package - scripts/ui.js and dist/control-ui not found

### ISSUE THREAD

**Issue by eastwen** [openclaw/openclaw#53101]
### Bug type

Regression (worked before, now fails)

### Summary

After upgrading to 2026.3.22, Control UI shows "assets not found". scripts/ui.js and dist/control-ui directory are missing from the npm package.

### Steps to reproduce

1. Install openclaw via npm: npm install -g openclaw
2. Start gateway: openclaw gateway
3. Open http://<host>:18789/
4. Page shows: "Control UI assets not found. Build them with pnpm ui:build"
5. Run pnpm ui:build - fails with: Cannot find module 'scripts/ui.js'

### Expected behavior

Control UI loads normally as it did in previous versions.

### Actual behavior

"Control UI assets not found" error. scripts/ui.js missing, dist/control-ui directory does not exist in the npm package.

### OpenClaw version

2026.3.22

### Operating system

Ubuntu 24.04

### Install method

npm-global

### Model

baidu-coding/qianfan-code-latest

### Provider / routing chain

openclaw -> baidu-coding

### Additional provider/model setup details

Affected: All npm-global installs on 2026.3.22
Severity: Medium (Control UI inaccessible, core functions still work)
Frequency: Always reproducible
Consequence: Cannot use web dashboard, must use chat channels only

### Logs, screenshots, and evidence

```shell
Last known good version: NOT_ENOUGH_INFO
First known bad version: 2026.3.22
scripts/ui.js does not exist in npm package, dist/control-ui directory also missing.
```

### Impact and severity

Affected: All npm-global installs on 2026.3.22
Severity: Medium (Control UI inaccessible, core functions still work)
Frequency: Always reproducible
Consequence: Cannot use web dashboard, must use chat channels only

### Additional information

Last known good version: NOT_ENOUGH_INFO
First known bad version: 2026.3.22
scripts/ui.js does not exist in npm package, dist/control-ui directory also missing.
