### ISSUE TITLE
lossless-claw plugin update fails after core update

### ISSUE THREAD

**Issue by jcenters** [openclaw/openclaw#53426]
After updating OpenClaw core from 2026.3.22 to 2026.3.23-2, the lossless-claw plugin update fails with:

```
Failed to update lossless-claw: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/linuxbrew/.linuxbrew/lib/node_modules/openclaw/dist/install.runtime-Deq6Beal.js' imported from /home/linuxbrew/.linuxbrew/lib/node_modules/openclaw/dist/installs-XLSjUYkq.js
```

The plugin is installed as a global extension at `~/.openclaw/extensions/lossless-claw/` and loads successfully (version 0.3.0). The failure only occurs during the plugin update step after core update.

Steps:
1. `openclaw update` (core updates successfully)
2. Plugin update step runs and fails for lossless-claw

Environment: Linux x64, npm install, global extension (not npm package).

**Comment by theDanielJLewis** [comment]
This happens for me, too, on an Intel Mac for every version since I installed Lossless Claw.

But it happens only the first time I run `openclaw update` for that version. The second time I run it (on the same OpenClaw version), the plugin updates just fine.

Here's an example log from 2026.4.8:

```
$ openclaw update
◇  ✓ Updating via package manager (82.92s)
│
◇  ✓ Running doctor checks (20.97s)

Update Result: OK
  Root: /Users/REDACTED/.nvm/versions/node/v22.19.0/lib/node_modules/openclaw
  Before: 2026.4.5
  After: 2026.4.8

Total time: 104.54s

Updating plugins...
npm plugins: 0 updated, 0 unchanged, 1 failed.
Failed to update lossless-claw: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/REDACTED/.nvm/versions/node/v22.19.0/lib/node_modules/openclaw/dist/install.runtime-B-MtEMSR.js' imported from /Users/REDACTED/.nvm/versions/node/v22.19.0/lib/node_modules/openclaw/dist/install-B56SF3dk.js

Restarting service...
Daemon restart completed.

Upgraded! Peter fixed stuff. Blame him if it breaks.

$ openclaw update
Updating OpenClaw...

│
◇  ✓ Updating via package manager (45.31s)
│
◇  ✓ Running doctor checks (16.2s)

Update Result: OK
  Root: /Users/REDACTED/.nvm/versions/node/v22.19.0/lib/node_modules/openclaw
  Before: 2026.4.8
  After: 2026.4.8

Total time: 62.02s

Updating plugins...
Downloading @martian-engineering/lossless-claw…
Extracting /var/folders/ss/r0_c2m4966758ss674kpgkbw0000gn/T/openclaw-npm-pack-aCkzFY/martian-engineering-lossless-claw-0.6.3.tgz…
Plugin "lossless-claw" has 1 suspicious code pattern(s). Run "openclaw security audit --deep" for details.
Installing to /Users/REDACTED/.openclaw/extensions/lossless-claw…
Installing plugin dependencies…
Config overwrite: /Users/REDACTED/.openclaw/openclaw.json (REDACTED)
npm plugins: 1 updated, 0 unchanged.

Restarting service...
Daemon restart completed.

Version bump! Same chaos energy, fewer crashes (probably).
```

Is this really only Lossless Claw that does this? It's my only installed plugin right now.

**Comment by theDanielJLewis** [comment]
My update from 2026.4.12 to 2026.4.14 looks like this problem may have been fixed!

Here's the output from running the update _only once_. Lossless Claw updated without trubble

```
$ openclaw update
Updating OpenClaw...

│
◇  ✓ Updating via package manager (65.38s)
│
◇  ✓ Running doctor checks (26.49s)

Update Result: OK
  Root: /Users/REDACTED/.nvm/versions/node/v22.19.0/lib/node_modules/openclaw
  Before: 2026.4.12
  After: 2026.4.14

Total time: 92.69s

Updating plugins...
Downloading @martian-engineering/lossless-claw…
Extracting /var/folders/ss/r0_c2m4966758ss674kpgkbw0000gn/T/openclaw-npm-pack-yFKpbX/martian-engineering-lossless-claw-0.9.0.tgz…
Installing to /Users/REDACTED/.openclaw/extensions/lossless-claw…
Installing plugin dependencies…
Config overwrite: /Users/REDACTED/.openclaw/openclaw.json (REDACTED)
npm plugins: 1 updated, 0 unchanged.

Restarting service...
Daemon restart completed.
```

**Comment by steipete** [comment]
Closing this as implemented after Codex review.

Current `main` already addresses this post-self-update plugin refresh bug. The update CLI now respawns into the updated install before running plugin refresh, and regression tests cover that exact flow. The latest shipped tag available in this checkout, `v2026.4.22`, also contains the same post-core respawn path.

What I checked:

- **Post-update work is deferred to a fresh process:** After a package-manager core update, `updateCommand` calls `continuePostCoreUpdateInFreshProcess(...)` and only runs in-process plugin refresh if that fresh-process resume did not happen. ([`src/cli/update-cli/update-command.ts:1354`](https://github.com/openclaw/openclaw/blob/8f64cd3e4d83/src/cli/update-cli/update-command.ts#L1354), [8f64cd3e4d83](https://github.com/openclaw/openclaw/commit/8f64cd3e4d83))
- **Fresh process uses the updated entrypoint:** `continuePostCoreUpdateInFreshProcess` resolves [`<root>/dist/entry.js`](https://github.com/openclaw/openclaw/blob/8f64cd3e4d83/%3Croot%3E/dist/entry.js), spawns `node <updated-root>/dist/entry.js update`, and passes `OPENCLAW_UPDATE_POST_CORE*` env vars so plugin updates run from the updated install instead of the stale pre-update process. ([`src/cli/update-cli/update-command.ts:895`](https://github.com/openclaw/openclaw/blob/8f64cd3e4d83/src/cli/update-cli/update-command.ts#L895), [8f64cd3e4d83](https://github.com/openclaw/openclaw/commit/8f64cd3e4d83))
- **Resume mode skips core update and performs only post-core tasks:** When `OPENCLAW_UPDATE_POST_CORE=1`, `updateCommand` bypasses the core update path and runs only `runPostCorePluginUpdate(...)`, which is the exact safeguard needed for the stale hashed-module failure described in the issue. ([`src/cli/update-cli/update-command.ts:968`](https://github.com/openclaw/openclaw/blob/8f64cd3e4d83/src/cli/update-cli/update-command.ts#L968), [8f64cd3e4d83](https://github.com/openclaw/openclaw/commit/8f64cd3e4d83))
- **Regression tests cover the respawn fix:** Tests assert that update respawns into the updated package root before post-update tasks and that post-core resume mode runs plugin updates without rerunning the core update. ([`src/cli/update-cli.test.ts:475`](https://github.com/openclaw/openclaw/blob/8f64cd3e4d83/src/cli/update-cli.test.ts#L475), [8f64cd3e4d83](https://github.com/openclaw/openclaw/commit/8f64cd3e4d83))
- **Latest shipped release in this checkout contains the fix path:** The `v2026.4.22` release commit includes the same `OPENCLAW_UPDATE_POST_CORE` code path in [`src/cli/update-cli/update-command.ts`](https://github.com/openclaw/openclaw/blob/00bd2cf7a376/src/cli/update-cli/update-command.ts) and the same respawn coverage in [`src/cli/update-cli.test.ts`](https://github.com/openclaw/openclaw/blob/00bd2cf7a376/src/cli/update-cli.test.ts), so this is not just an unreleased main-branch change. ([`src/cli/update-cli/update-command.ts:83`](https://github.com/openclaw/openclaw/blob/00bd2cf7a376/src/cli/update-cli/update-command.ts#L83), [00bd2cf7a376](https://github.com/openclaw/openclaw/commit/00bd2cf7a376))

So I’m closing this as already implemented rather than keeping a duplicate issue open.

Review notes: reviewed against [8f64cd3e4d83](https://github.com/openclaw/openclaw/commit/8f64cd3e4d8339a6aab3ca230d5e14944c91cfaf); fix evidence: release [v2026.4.22](https://github.com/openclaw/openclaw/releases/tag/v2026.4.22), commit [00bd2cf7a376](https://github.com/openclaw/openclaw/commit/00bd2cf7a376f1fba26291c6c4766f1f15cbdfa5).
