### ISSUE TITLE
[Bug]: MSTeams Channel Replies Not Being Sent

### ISSUE THREAD

**Issue by matosonline** [openclaw/openclaw#9873]
# Bug Report: MSTeams Channel Replies Not Being Sent

**Reporter:** [REDACTED]  
**Date:** 2026-02-05  
**OpenClaw Version:** 2026.2.1  
**Platform:** WSL2 (Linux 6.6.87.2-microsoft-standard-WSL2, x64)  
**Node Version:** v22.22.0  
**Affected Plugin:** `/mnt/e/openclaw/extensions/msteams/`

---

## Summary

Agent successfully processes Microsoft Teams channel messages and generates replies, but **replies are never sent back to Teams channels**. DM replies work correctly. This is a critical bug affecting all Teams channel interactions.

---

## Environment

- **OpenClaw:** 2026.2.1
- **Runtime:** WSL2 on Windows
- **Agent:** [Bot Name] (main agent)
- **Model:** anthropic/claude-sonnet-4-5 (primary), openai-codex/gpt-5.2 (fallback)
- **Teams App ID:** [REDACTED-APP-ID]
- **Tenant ID:** [REDACTED-TENANT-ID]

---

### Primary Issue (Critical)
When a user @mentions the bot in a Teams **channel**, the message is received and processed, the agent generates a reply, but **the reply is never sent back to Teams**. No errors are logged.

### Secondary Issue
Messages without @mentions are routed to the DM session instead of the channel session, despite `groupPolicy: "open"` and `requireMention: false` being set.

---

### Setup
1. Install bot to a Teams team
2. Configure gateway with:
```json
{
  "channels": {
    "defaults": {
      "groupPolicy": "open"
    },
    "msteams": {
      "enabled": true,
      "groupPolicy": "open",
      "teams": {
        "[REDACTED-TEAM-ID]": {
          "replyStyle": "top-level"
        }
      }
    }
  }
}
```

### Reproduce Bug
1. In Teams channel, post: `@[botname] test message`
2. Wait for processing to complete
3. **Expected:** Bot replies in the channel
4. **Actual:** No reply appears in Teams

---

#### Message Received Successfully
```
2026-02-05T19:11:55.260Z [msteams] received message
2026-02-05T19:11:56.451Z [msteams] dispatching to agent
2026-02-05T19:11:57.815Z [diagnostic] lane enqueue: lane=session:agent:main:msteams:channel:[REDACTED-CONVERSATION-ID]@thread.tacv2
```

#### Agent Processing Completed
```
2026-02-05T19:11:57.843Z [agent/embedded] embedded run start: runId=af20ba96-03d1-4de2-9e98-9636444e5434 sessionId=f490c738-8c0e-426b-a7b6-5941fdf15921 messageChannel=msteams
2026-02-05T19:12:04.653Z [agent/embedded] embedded run agent end
2026-02-05T19:12:04.680Z [agent/embedded] embedded run done: durationMs=6839 aborted=false
2026-02-05T19:12:06.362Z [msteams] dispatch complete
```

#### **NO Send Activity** ❌
- **Expected:** Log entries like `msteams:send` or `sending proactive message`
- **Actual:** None found in logs around timestamp 19:12:04-19:12:07

#### Comparison: Working DM Send (for reference)
```
2026-02-05T17:13:28.603Z [msteams:send] sending proactive message
2026-02-05T17:13:29.970Z [msteams:send] sent proactive message
```

### Session History Evidence

Query: `sessions_history(sessionKey="agent:main:msteams:channel:[REDACTED-CONVERSATION-ID]@thread.tacv2")`

**User message:**
```
[2026-02-05 14:11:55 EST] test message
```

**Agent reply (generated but never sent):**
```
Great! This message came through **without** a mention — so the mention gate fix is working now! 

Did you also fix the image issue? Want to test sending me an image to see if I can now see it?
```

**Delivery context in session:**
```json
{
  "deliveryContext": {
    "channel": "msteams",
    "to": "conversation:[REDACTED-CONVERSATION-ID]@thread.tacv2",
    "accountId": "default"
  }
}
```

---

## Expected vs Actual Behavior

| Context | Expected | Actual | Status |
|---------|----------|--------|--------|
| DM to bot | Message received → Reply sent | ✅ Works correctly | ✅ PASS |
| Channel @mention | Message received → Reply sent | ❌ Reply generated but not sent | ❌ **FAIL** |
| Channel no mention | Message received by channel session | ❌ Routes to DM session instead | ❌ FAIL |

---

### What We Tried (All Failed)

1. ✅ Verified bot has correct manifest scopes: `["personal", "team", "groupChat"]`
2. ✅ Added Microsoft Graph permission `Group.Read.All` with admin consent
3. ✅ Set `groupPolicy: "open"` in both `channels.defaults` and `channels.msteams`
4. ✅ Added team by ID and by name to allowlist
5. ✅ Set `requireMention: false` at team level
6. ✅ Removed tool restrictions that might interfere
7. ✅ Set `replyStyle: "top-level"` for the team
8. ✅ Multiple gateway restarts
9. ✅ Verified Graph API team resolution working

**None of these resolved the channel reply issue.**

### Key Observations

1. **DMs work perfectly** - send logs appear, replies are delivered
2. **Channel processing works** - messages are received, agent runs successfully
3. **Reply generation works** - session history shows valid replies created
4. **Reply delivery fails silently** - no send attempt logged, no errors, no timeout

This suggests the bug is in the **conversation reference handling** or **proactive messaging logic** specifically for channel conversations in `/mnt/e/openclaw/extensions/msteams/`.

### Relevant Files

- Plugin: `/mnt/e/openclaw/extensions/msteams/`
- Source file (suspected): `/mnt/e/openclaw/extensions/msteams/src/monitor-handler/message-handler.ts`
- Logs: `/tmp/openclaw/openclaw-2026-02-05.log`

### Teams Channel Details

- **Team Name:** [My Team]
- **Team ID:** `[REDACTED-TEAM-ID]`
- **Channel Name:** General
- **Conversation ID:** `[REDACTED-CONVERSATION-ID]@thread.tacv2`
- **Channel Type:** Appears to be "Threads" style (not classic "Posts")
- **Session Key:** `agent:main:msteams:channel:[REDACTED-CONVERSATION-ID]@thread.tacv2`

---

## Suspected Root Cause

The MSTeams plugin likely:
1. ✅ Correctly stores conversation reference when receiving channel messages
2. ✅ Correctly routes to channel-specific session
3. ❌ **Fails to use stored conversation reference when sending replies back**

Possible issues:
- Conversation reference not being passed to send logic
- Reply delivery code path missing for channel conversations
- Bug in proactive messaging for threaded conversations (`@thread.tacv2`)
- Silent error swallowing in send path

---

## Workaround

**Current:** Bot works correctly for **DMs only**. Channel interactions are non-functional.

---

## Impact

**Severity:** HIGH  
**Impact:** Complete inability to use bot in Teams channels (only DMs work)

This blocks:
- Team collaboration use cases
- Multi-user channel assistance
- Public/shared bot interactions in Teams

---

## Attachments

- Full config: Available upon request (contains sensitive credentials)
- Session transcript: Available via `sessions_history` for sessionId `f490c738-8c0e-426b-a7b6-5941fdf15921`
- Logs: `/tmp/openclaw/openclaw-2026-02-05.log` (entries 2904-2924 for failing message)

---

## Contact

**Reporter:** [REDACTED]  
**Available for testing/follow-up**

---

**Generated:** 2026-02-05 14:57 EST  
**Session ID:** 06f7f265-ebfb-4a1b-a616-3aa007ef42a6

**Comment by matosonline** [comment]
# Bug Update: Root Cause Identified

## 🔍 Key Finding: Bot Framework Context Lifecycle Issue

After deeper investigation, I've identified the **root cause** of why channel replies aren't being sent.

---

## The Problem

**Bot Framework context is being revoked/disposed before OpenClaw finishes sending async replies.**

### Evidence

#### 1. **"Revoked Proxy" Error in Logs**
```
2026-02-05T19:55:02.695Z [msteams] msteams typing action=start failed: 
TypeError: Cannot perform 'set' on a proxy that has been revoked
```

This error appears when OpenClaw tries to send typing indicators or messages **after** the Bot Framework has already disposed the conversation context.

#### 2. **Replies Generated But Never Sent**

Query of session history for channel `[REDACTED-CONVERSATION-ID]@thread.tacv2` shows:

**User message (14:11:55 EST):**
```
test message
```

**Agent reply (generated successfully):**
```
Great! This message came through **without** a mention — so the mention gate fix is working now! 

Did you also fix the image issue? Want to test sending me an image to see if I can now see it?
```

**Result:** Reply stored in session history, `stopReason: "stop"` (normal completion), but **NEVER sent to Teams**.

#### 3. **Zero Send Attempts After Gateway Restart**

Log analysis shows:
- ✅ Last successful channel send: `2026-02-05T18:32:49.231Z` (13:32 EST)
- ❌ After gateway restart at 15:26 EST: **ZERO** `sending proactive message` or `msteams:send` log entries
- ⚠️ Multiple `dispatch complete` logs with NO corresponding send logs

This isn't a send failure — **the send code path isn't being triggered at all**.

---

## Sequence of Events (Timeline)

1. **Message arrives** → Bot Framework creates conversation context (proxy object)
2. **OpenClaw receives message** → Stores conversation reference, dispatches to agent
3. **Agent processes message** → Generates reply (async operation, takes ~10-20 seconds)
4. **Bot Framework handler completes** → **Revokes/disposes the context** ❌
5. **Reply dispatcher tries to send** → Context already gone → Silent failure (no send logs)

---

## Why This Affects Channels But Not DMs

- **DMs:** Simpler conversation structure, faster agent response, context stays alive long enough
- **Channels:** Agent takes longer to process (more context, tool calls), Bot Framework times out and disposes context before reply is ready

---

## Config Status

Confirmed `replyStyle: "thread"` is already set:
```json
"teams": {
  "[REDACTED-TEAM-ID]": {
    "replyStyle": "thread"
  }
}
```

This is **not a config issue** — it's a code-level lifecycle bug in how the MSTeams plugin manages the Bot Framework context.

---

## Required Fix

The MSTeams plugin needs one of these solutions:

### Option A: Keep Context Alive
Prevent Bot Framework from disposing the context until OpenClaw's async reply dispatcher completes.

### Option B: Proactive Messaging
Properly implement proactive messaging using stored conversation references (independent of the inbound context lifecycle).

### Option C: Synchronous Ack + Async Reply
Send an immediate typing indicator or ack to keep the connection alive, then send the full reply asynchronously.

---

## Impact

**Severity:** CRITICAL  
**Scope:** All Teams channel interactions (groups, team channels)  
**Workaround:** None — channels completely non-functional

DMs continue to work normally.

---

## Files Implicated

- `/mnt/e/openclaw/extensions/msteams/src/messenger.ts` (send logic)
- `/mnt/e/openclaw/extensions/msteams/src/reply-dispatcher.ts` (dispatcher creation)
- `/mnt/e/openclaw/extensions/msteams/src/monitor-handler/message-handler.ts` (context management)

The issue is in how these coordinate the Bot Framework conversation context lifecycle with OpenClaw's async reply system.

---

**Reporter:** [REDACTED]  
**Updated:** 2026-02-05 15:51 EST  
**Diagnostic Session:** agent:main

**Comment by dm-bradgroux** [comment]
@matosonline I had my Opus 4.5 agent fix itself with: 

> To try and fix your teams config, check the issues on the repo for clues? https://github.com/openclaw/openclaw/issues?q=is%3Aissue%20teams

**Comment by BradGroux** [comment]
Scratch that, I'm experiencing this issue too. 

> The channel messages aren't showing up in the logs at all — not even rejected.

Definitely needs a patch ASAP, at least DMs work.

**Comment by BradGroux** [comment]
## Additional Reproduction + Diagnostic Findings

**OpenClaw Version:** 2026.2.3-1
**Platform:** macOS 15.3 (Darwin 25.1.0, arm64)
**Node Version:** v23.11.0
**Model:** anthropic/claude-opus-4-6 (patched into model catalog manually)
**MSTeams Plugin:** @openclaw/msteams 2026.2.3-1

---

### Environment

- Bot registered in Azure with correct app ID, password, and tenant ID
- Messaging endpoint pointing to local tunnel → `localhost:3978/api/messages`
- Bot installed in a Teams team with 14 channels configured
- `groupPolicy: "allowlist"` with team/channel allowlist structure
- `requireMention: true` on all channels
- `dmPolicy: "allowlist"` with explicit user IDs

### Config Structure (redacted)

```json
{
  "channels": {
    "msteams": {
      "enabled": true,
      "appId": "[REDACTED]",
      "appPassword": "[REDACTED]",
      "tenantId": "[REDACTED]",
      "webhook": {
        "port": 3978,
        "path": "/api/messages"
      },
      "dmPolicy": "allowlist",
      "allowFrom": ["[user-email]", "[user-aad-id]"],
      "groupAllowFrom": ["[user-email]", "[user-aad-id]"],
      "groupPolicy": "allowlist",
      "teams": {
        "TeamName": {
          "requireMention": true,
          "channels": {
            "General": { "requireMention": true },
            "ChannelA": { "requireMention": true },
            "ChannelB": { "requireMention": true }
          }
        }
      }
    }
  }
}
```

---

### What Works

| Scenario | Status |
|----------|--------|
| DM to bot (desktop) | ✅ Works perfectly |
| DM to bot (mobile) | ✅ Works perfectly |
| Bot sends TO channels proactively (via `message` tool) | ✅ Works |
| Webhook listening on port 3978 | ✅ Returns 401 (correct — requires Bot Framework auth) |
| Channel allowlist resolution | ✅ All 14 channels resolve correctly in startup logs |
| User allowlist resolution | ✅ All configured users resolve correctly |

### What Fails

| Scenario | Status |
|----------|--------|
| @mention bot in any channel → bot receives message | ❌ No activity logged |
| @mention bot from mobile in channel | ❌ No activity logged |
| Any channel message reaching the handler | ❌ Zero evidence in logs |

---

### Diagnostic Evidence

#### 1. Webhook is running and accessible

```
curl -s -o /dev/null -w "%{http_code}" http://localhost:3978/api/messages
→ 401 (expected — Bot Framework auth required)
```

#### 2. Channel resolution succeeds on startup

```
[msteams] channels resolved: TeamName/General→[group-id]/19:xxx@thread.tacv2,
  TeamName/ChannelA→[group-id]/19:yyy@thread.tacv2, ... (+8)
```

All 14 channels resolve correctly every restart.

#### 3. Zero channel inbound activity in logs

Searched all gateway logs for the past hour during active testing:

- **No** `received message` entries for any channel conversation
- **No** `skipping message (mention required)` entries
- **No** `dropping group message` entries
- **No** `dispatching to agent` entries for channel sessions
- **No** errors related to channel message processing

The messages simply never arrive at the webhook handler.

#### 4. One historical channel message DID arrive (earlier in the session)

Found one piece of evidence that a channel message was processed earlier:

```
[agent/embedded] workspace bootstrap file MEMORY.md ... 
  (sessionKey=agent:main:msteams:channel:19:xxx@thread.tacv2)
```

This was during a period when all models were in rate-limit cooldown, so the agent could not generate a reply. After recovery, no further channel messages have been received despite 20+ test attempts.

#### 5. DMs work on the same webhook, same port, same process

DM delivery is immediate and reliable. The same Express server on port 3978 handles both DMs and channels. DMs arrive; channels do not.

---

### Key Observation: Regression from 2026.1.30

**This was working before the update.** Channels functioned correctly on OpenClaw 2026.1.30 with zero config changes. After updating to 2026.2.3-1, channel messages stopped arriving. The bot registration in Azure has not changed. The tunnel has not changed. Only OpenClaw was updated.

### Hypothesis

The issue appears to be at the Bot Framework adapter level — specifically how channel activities are received and routed to the `onMessage` handler. Since:

1. The webhook IS listening (401 on unauthenticated requests)
2. DMs DO arrive through the same webhook
3. Channel messages DO NOT arrive (zero log evidence)
4. Proactive sends TO channels work fine

The adapter may be filtering or dropping channel `activity.type === "message"` events before they reach the registered `onMessage` handler. Alternatively, something in the `@microsoft/agents-hosting` dependency update (used by the msteams extension) may have changed how channel conversation activities are authenticated or dispatched.

### Source Code Review

Reviewed the full MSTeams plugin source in `extensions/msteams/src/`:

- `monitor-handler/message-handler.ts` — The handler logic looks correct. Policy gating, mention detection, conversation reference storage, and reply dispatch are all properly implemented.
- `messenger.ts` — Send logic for both `thread` (ctx.sendActivity) and `top-level` (continueConversation) reply styles is correct.
- `policy.ts` — `resolveMSTeamsRouteConfig` and `resolveMSTeamsReplyPolicy` correctly resolve team/channel configs.

**The message handler code never executes for channel messages** — the issue is upstream, before `handleTeamsMessage()` is called.

---

### Suggestion

Check if the `@microsoft/agents-hosting` or `@microsoft/agents-hosting-express` packages changed how they authenticate/route `conversationType: "channel"` activities between the versions bundled in 2026.1.30 vs 2026.2.3-1. The adapter `.run()` method or the Express middleware may be silently rejecting channel activities while allowing personal/DM activities through.

**Comment by BradGroux** [comment]
## Workaround Found — `groupPolicy: "allowlist"` Broken in 2026.2.9

After extensive debugging tonight, I found the root cause. **Channel messages are received but silently dropped before they reach the agent.** The issue is on the receive side, not the send side.

### Environment
- OpenClaw 2026.2.9 (upgraded from 2026.2.3-1)
- macOS (Darwin 25.1.0, arm64), Node v23.11.0
- MSTeams channel with Agents SDK (`@microsoft/agents-hosting` v1.2.3)
- 14 channels configured under one team, all with `requireMention: true`

### Symptoms
- Bot receives channel @mentions (visible in logs as `received message`)
- Agent processes the message and generates a reply
- **Reply is never sent to the channel** — no `msteams:send` log entries for channel context
- DMs work perfectly (full `sending proactive message` → `sent proactive message` log pairs)

### Root Cause
The log reveals the exact failure point:

```
received message
html attachment summary
dropping group message (not in team/channel allowlist)
```

With `groupPolicy: "allowlist"` and a fully configured `teams:` block (team name + channel names + `requireMention`), channel messages are **still being dropped** by the allowlist filter. The new Agents SDK appears to have changed how channel/team identifiers are presented, so the allowlist matching no longer finds a match against the configured team/channel names.

### Workaround
Set `groupPolicy: "open"` in your msteams channel config:

```json
{
  "channels": {
    "msteams": {
      "groupPolicy": "open",
      "teams": {
        "YourTeamName": {
          "requireMention": true,
          "channels": {
            "General": { "requireMention": true },
            "OtherChannel": { "requireMention": true }
          }
        }
      }
    }
  }
}
```

The `teams:` block with `requireMention: true` still works for gating responses — the bot only responds when @mentioned. So you retain control over when the bot engages; you just lose the team/channel-level allowlist filtering.

### Troubleshooting Steps (for others hitting this)

1. **Check if messages are received at all:**
   ```bash
   grep "received message" /tmp/openclaw/openclaw-$(date +%Y-%m-%d).log
   ```
   If no entries, your webhook/tunnel isn't reaching OpenClaw (port 3978 issue).

2. **Check for the allowlist drop:**
   ```bash
   grep "dropping group message" /tmp/openclaw/openclaw-$(date +%Y-%m-%d).log
   ```
   If you see `not in team/channel allowlist`, this is the bug.

3. **Check if DMs work:** Send the bot a direct message. If DMs work but channels don't, you've confirmed this issue.

4. **Apply the workaround:** Set `groupPolicy: "open"` via config patch or edit `~/.openclaw/openclaw.json` directly, then restart.

### Additional Note: Missing Dependencies After Update

After updating to 2026.2.9 via `gateway update.run`, the MSTeams extension crashed on startup with:

```
Cannot find module '@microsoft/agents-hosting'
```

The new Agents SDK dependencies aren't being installed by the npm global install. Had to manually install in the openclaw `node_modules`:

```bash
cd $(npm root -g)/openclaw
npm install @microsoft/agents-hosting@^1.2.3 \
  @microsoft/agents-hosting-express@^1.2.3 \
  @microsoft/agents-hosting-extensions-teams@^1.2.3 \
  express@^5.2.1 \
  proper-lockfile@^4.1.2 \
  --no-save
```

These deps get wiped on the next `npm i -g openclaw@latest`, so they need to be reinstalled after every update.

**Comment by BradGroux** [comment]
cc @matosonline — workaround above in case it helps unblock others hitting this.

**Comment by dm-bradgroux** [comment]
Fix is in, should not be marked as inactive.

**Comment by BradGroux** [comment]
Not stale.
