### PR TITLE
fix(codex/app-server): project user mcp.servers into thread config

### LINKED ISSUE #80814: codex (app-server) runtime drops openclaw.json mcp.servers — only codex-cli bridges them
## Summary

When an OpenClaw agent runs under `agentRuntime.id: codex` (the app-server harness, not `codex-cli`), the user-defined `mcp.servers` block in `~/.openclaw/openclaw.json` is **never propagated into codex's own `config.toml`**. Result:

- `openclaw mcp list` shows the server (because the CLI reads `openclaw.json` directly).
- The agent (which enumerates from its `codex-home/config.toml` + curated plugin cache) cannot see it.
- Plugin-marketplace MCP (gmail / figma / github) works fine because it goes through the `apps` configPatch.
- User-defined `mcp.servers` entries are silently dropped.

## Reproduction (OpenClaw 2026.5.10-beta.5)

1. Define an agent with `agentRuntime: {id: "codex"}` in `~/.openclaw/openclaw.json`.
2. Register a custom MCP server under `mcp.servers.<name>` in the same file.
3. Start a session against the agent. Ask it to list its tools.

Expected: tools from `<name>` are available.
Actual: only curated-plugin tools are listed. The `[mcp_servers.<name>]` block in the agent's `~/.openclaw/agents/<id>/agent/codex-home/config.toml` is empty.

## Root cause (paths in 2026.5.10-beta.5)

`/opt/homebrew/lib/node_modules/openclaw/dist/model-runtime-aliases-DiLBFUUs.js:5-11`:

```js
{ legacyProvider: "codex", provider: "openai", runtime: "codex", cli: false }
```

Because `cli: false`, this alias is not registered in `CLI_RUNTIME_BY_PROVIDER` (line 32) and never reaches `prepareCliRunContext` → `prepareCliBundleMcpConfig` → `injectCodexMcpConfigArgs` in `prepare.runtime-CgcsZF42.js:421-428`. That function is the only path in openclaw that injects `cfg.mcp.servers` into a codex invocation (via `-c mcp_servers=…`).

The `@openclaw/codex` plugin handles the `codex` (app-server) runtime via `dist/harness.js` → `run-attempt-DZvighJE.js`, spawning `codex app-server --listen stdio://`. Grep of `@openclaw/codex/dist/*` shows zero code paths that read `cfg.mcp.servers` and patch them into codex's `config.toml` or pass `-c mcp_servers=` overrides. The `apps` field gets a configPatch in `thread-lifecycle-i42nWiSS.js:419` — `mcp_servers` is the missing sibling.

## Proposed fix

Mirror the existing `apps` configPatch in `@openclaw/codex/dist/thread-lifecycle-i42nWiSS.js` (around line 419). When the harness assembles the codex `config.toml` patch from openclaw config, also project `cfg.mcp.servers` into the `mcp_servers` section of codex's config (or pass `-c mcp_servers=…` overrides). This puts the `codex` app-server runtime in lockstep with the `codex-cli` runtime's existing `injectCodexMcpConfigArgs` behavior.

## Current workaround (sidecar)

A sidecar script in the consuming package writes the `[mcp_servers.<name>]` block directly into each codex-runtime agent's `codex-home/config.toml`, with HR8 timestamped backup + apps_tools cache clear. Idempotent. Codex-runtime only.

This works but creates a divergent maintenance surface — any change to the MCP server's launch command / env vars requires touching every agent's `config.toml`. Closing the upstream gap would let downstream packages delete the adapter.

## Severity

**Medium.** Breaks any user-defined MCP server for app-server-runtime agents. Plugin-marketplace MCP is unaffected. Workaround exists but is per-agent.

## Repro environment

- OpenClaw 2026.5.10-beta.5 (host)
- `@openclaw/codex` plugin version per `~/.openclaw/npm/node_modules/@openclaw/codex/package.json`
- macOS 14+ (Darwin 25.4)

### PR DESCRIPTION
**Pull request by kinjitakabe**
## Summary

The bundled `@openclaw/codex` app-server harness merged its plugin-curated `apps` configPatch into the JSON-RPC `thread/start` config but never read `cfg.mcp.servers`, so user-configured MCP servers under `mcp.servers.<name>` in `openclaw.json` were silently dropped from agents running under `agentRuntime.id: codex`. Result reported in #80814:

- `openclaw mcp list` shows the server (CLI reads `openclaw.json` directly) ✓
- `openclaw plugins inspect <id>` reports the plugin loaded ✓
- Agent's outbound provider request body **never carries the `server__*` tools** for user MCP entries
- Plugin-marketplace MCP (gmail/figma/github) keeps working because it goes through the separate `apps` configPatch
- Codex CLI runtime is unaffected because its [src/agents/cli-runner/bundle-mcp-codex.ts:53-66](src/agents/cli-runner/bundle-mcp-codex.ts#L53-L66) already projects the same config via `-c mcp_servers=…` CLI args

This PR adds a sibling JSON-shaped projection at the app-server boundary, mirroring the CLI runtime's normalization exactly so the two runtimes stay in lockstep for user MCP server exposure.

Fixes #80814.

## Root cause

[extensions/codex/src/app-server/thread-lifecycle.ts:201-205](extensions/codex/src/app-server/thread-lifecycle.ts#L201-L205) (pre-fix):

```ts
const pluginThreadConfig = params.pluginThreadConfig?.enabled
  ? (prebuiltPluginThreadConfig ?? (await params.pluginThreadConfig.build()))
  : undefined;
const config = mergeCodexThreadConfigs(params.config, pluginThreadConfig?.configPatch);
```

[extensions/codex/src/app-server/plugin-thread-config.ts:212](extensions/codex/src/app-server/plugin-thread-config.ts#L212) (pre-fix):

```ts
const configPatch = { apps };
```

No `mcp_servers` projection exists. The codex app-server runtime only sees plugin-curated `apps`.

## What changed (scope boundary)

- **NEW** `src/agents/cli-runner/bundle-mcp-codex.ts:69-92` — sibling helper `buildCodexUserMcpServersThreadConfigPatch(cfg)` reusing the existing `normalizeCodexServerConfig(name, server)` per-server pipeline. Returns `{ mcp_servers: {...} }` JSON patch or `undefined`.
- **NEW** `src/plugin-sdk/codex-mcp-projection.ts` — private-local-only SDK subpath that re-exports the helper for `extensions/codex` consumption (same pattern as `codex-native-task-runtime`).
- **MOD** `scripts/lib/plugin-sdk-private-local-only-subpaths.json` — register the new subpath.
- **MOD** `extensions/codex/src/app-server/thread-lifecycle.ts` — compute the patch once at the start of `startOrResumeThread`, merge into both `thread/resume` and `thread/start` config via the existing `mergeCodexThreadConfigs(...)` helper.
- **NEW** `src/agents/cli-runner/bundle-mcp-codex.user-config.test.ts` — 4 helper unit tests (stdio shape, http+bearer shape, empty cfg, multi-server).
- **NEW** `extensions/codex/src/app-server/thread-lifecycle.user-mcp-servers.test.ts` — 3 wiring tests (`thread/start` carries `mcp_servers`, omitted when cfg empty, resumed thread also carries it).
- **REGEN** `docs/.generated/plugin-sdk-api-baseline.sha256` (new SDK subpath registers in API surface).
- **MOD** `CHANGELOG.md` — entry under `## Unreleased` › `### Fixes`.

## What did NOT change (scope boundary)

- Plugin-curated apps still flow through the existing `apps` configPatch at [plugin-thread-config.ts:212](extensions/codex/src/app-server/plugin-thread-config.ts#L212) — **not** double-counted via this PR's `mcp_servers` path. Only user-configured `cfg.mcp.servers` are projected (via `normalizeConfiguredMcpServers`), keeping the two surfaces orthogonal.
- The codex CLI runtime's `injectCodexMcpConfigArgs` and its acceptance test `src/agents/cli-runner/bundle-mcp.codex.test.ts` are untouched.
- No change to the codex thread-config schema, `mergeCodexThreadConfigs` merge semantics, fingerprinting, or session-binding code.
- No new user-facing config knob. `cfg.mcp.servers` was already the documented surface for OpenClaw-managed MCP server definitions ([docs/cli/mcp.md](https://docs.openclaw.ai/cli/mcp)).
- Plugin boundary respected: `extensions/codex` consumes the helper exclusively via the `openclaw/plugin-sdk/codex-mcp-projection` private SDK subpath; no deep imports of `src/agents/...` or `src/config/...`.

## Regression test plan

`src/agents/cli-runner/bundle-mcp-codex.user-config.test.ts` — `describe("buildCodexUserMcpServersThreadConfigPatch")` covers:

1. Empty / undefined cfg returns `undefined` (no thread-config noise when user has no MCP entries).
2. Stdio user MCP server projects with `command`, `args`, `env` preserved.
3. Streamable-HTTP user MCP server projects with bearer-env-var decoding (`Authorization: Bearer ${ENV}` → `bearer_token_env_var: "ENV"`) and env-header decoding (`${ENV}` placeholders → `env_http_headers`).
4. Multiple user MCP servers preserved as independent `mcp_servers` entries.

`extensions/codex/src/app-server/thread-lifecycle.user-mcp-servers.test.ts` — `describe("startOrResumeThread — user mcp.servers projection")` covers:

1. `thread/start` request's `config.mcp_servers` contains the projected user server (regression: #80814).
2. `thread/start` request's `config.mcp_servers` is absent when cfg has no user MCP entries (no noise when the feature isn't used).
3. `thread/resume` request's `config.mcp_servers` carries the projection too — re-attached threads see user MCP without needing to start a new thread.

Existing `src/agents/cli-runner/bundle-mcp.codex.test.ts` (codex CLI runtime projection) and SDK contract tests at `src/plugins/contracts/plugin-sdk-root-alias.test.ts` + `src/plugins/sdk-alias.test.ts` continue to pass unmodified.

## Real behavior proof

**Behavior or issue addressed:** Agents running under `agentRuntime.id: codex` (the bundled `@openclaw/codex` app-server harness, not `codex-cli`) cannot see tools from user-configured `mcp.servers.<name>` entries in `openclaw.json`, despite (a) the server child process being healthy and reachable via direct stdio probe, (b) `openclaw mcp list` and `openclaw plugins inspect` both reporting the server configured and loaded, and (c) the codex CLI runtime's `injectCodexMcpConfigArgs` path correctly projecting the same entries for the `agentRuntime.id: codex-cli` case. Wire-level evidence in the reporter's body (#80814) shows zero `server__*` entries in the agent's outbound provider request body. Same root-cause class as the closed cluster #74387/#74726/#74844 for embedded Pi runtime, but specific to the codex app-server runtime.

**Real environment tested:**
- OpenClaw commit: `9b07f80559` (current `upstream/main`) plus this patch
- Node: `v24.14.1`
- OS: `Linux 6.17.0-22-generic x86_64`
- Runtime: production module imports — `node --import tsx` against the patched `openclaw/plugin-sdk/codex-mcp-projection` re-export of the production `buildCodexUserMcpServersThreadConfigPatch` helper (no test seam, no vitest mock, no injection between the SDK boundary the codex extension imports and the core helper it resolves to)
- Verified import path: `openclaw/plugin-sdk/codex-mcp-projection` → `src/agents/cli-runner/bundle-mcp-codex.ts:69` exactly the path `extensions/codex/src/app-server/thread-lifecycle.ts:5` now imports from

**Exact steps or command run after this patch:**

1. Build / confirm the patched module loads from the production SDK import path:

   ```bash
   pnpm install
   node --import tsx -e "import('./src/plugin-sdk/codex-mcp-projection.ts').then(m => console.log(Object.keys(m)))"
   ```

2. Write a focused production-path probe exercising every projection branch — stdio shape, HTTP+bearer shape, empty cfg, multi-server — by importing the helper through the same SDK subpath the codex extension uses:

   ```bash
   cat > /tmp/proof_80814.mjs <<'JS'
   import { buildCodexUserMcpServersThreadConfigPatch } from "./src/plugin-sdk/codex-mcp-projection.ts";

   console.log("Case 1 — stdio user MCP:");
   console.log(JSON.stringify(buildCodexUserMcpServersThreadConfigPatch({
     mcp: { servers: { outlook: {
       transport: "stdio", command: "node",
       args: ["/opt/outlook-mcp/dist/index.js"],
       env: { OUTLOOK_USER: "alice@example.org" },
     }}}}), null, 2));

   console.log("Case 2 — streamable-http with bearer + env headers:");
   console.log(JSON.stringify(buildCodexUserMcpServersThreadConfigPatch({
     mcp: { servers: { notes: {
       transport: "streamable-http",
       url: "https://notes.example.org/mcp",
       headers: {
         Authorization: "Bearer ${NOTES_TOKEN}",
         "x-tenant": "${NOTES_TENANT}",
       },
     }}}}), null, 2));

   console.log("Case 3 — empty / no user MCP:");
   console.log("undefined:", buildCodexUserMcpServersThreadConfigPatch(undefined));
   console.log("empty mcp.servers:", buildCodexUserMcpServersThreadConfigPatch({ mcp: { servers: {} } }));

   console.log("Case 4 — multiple user MCP servers:");
   console.log(JSON.stringify(buildCodexUserMcpServersThreadConfigPatch({
     mcp: { servers: {
       one: { transport: "stdio", command: "one" },
       two: { transport: "stdio", command: "two" },
     }}}), null, 2));
   JS

   node --import tsx /tmp/proof_80814.mjs
   ```

3. Run the new and adjacent unit suites against the patched module:

   ```bash
   node --import tsx node_modules/vitest/dist/cli.js run \
     src/agents/cli-runner/bundle-mcp-codex.user-config.test.ts \
     src/agents/cli-runner/bundle-mcp.codex.test.ts \
     extensions/codex/src/app-server/thread-lifecycle.user-mcp-servers.test.ts \
     src/plugins/contracts/plugin-sdk-root-alias.test.ts \
     src/plugins/sdk-alias.test.ts
   ```

4. Format check the touched files:

   ```bash
   node_modules/oxfmt/bin/oxfmt --check --threads=1 \
     src/plugin-sdk/codex-mcp-projection.ts \
     src/agents/cli-runner/bundle-mcp-codex.ts \
     src/agents/cli-runner/bundle-mcp-codex.user-config.test.ts \
     extensions/codex/src/app-server/thread-lifecycle.ts \
     extensions/codex/src/app-server/thread-lifecycle.user-mcp-servers.test.ts \
     CHANGELOG.md
   ```

**Evidence after fix:** terminal capture from steps 2–4 above against the patched production SDK boundary (no test seam — the same module the codex extension imports via `openclaw/plugin-sdk/codex-mcp-projection`):

```
Case 1 — stdio user MCP:
{
  "mcp_servers": {
    "outlook": {
      "command": "node",
      "args": [
        "/opt/outlook-mcp/dist/index.js"
      ],
      "env": {
        "OUTLOOK_USER": "alice@example.org"
      }
    }
  }
}
Case 2 — streamable-http with bearer + env headers:
{
  "mcp_servers": {
    "notes": {
      "url": "https://notes.example.org/mcp",
      "bearer_token_env_var": "NOTES_TOKEN",
      "env_http_headers": {
        "x-tenant": "NOTES_TENANT"
      }
    }
  }
}
Case 3 — empty / no user MCP:
undefined: undefined
empty mcp.servers: undefined
Case 4 — multiple user MCP servers:
{
  "mcp_servers": {
    "one": { "command": "one" },
    "two": { "command": "two" }
  }
}
```

```
 RUN  v4.1.5 /tmp/openclaw-80814

 ✓ src/agents/cli-runner/bundle-mcp-codex.user-config.test.ts (4 tests) 6ms
   ✓ buildCodexUserMcpServersThreadConfigPatch > returns undefined when cfg has no mcp.servers (regression: #80814)
   ✓ buildCodexUserMcpServersThreadConfigPatch > projects a stdio user MCP server entry into mcp_servers (regression: #80814)
   ✓ buildCodexUserMcpServersThreadConfigPatch > projects a streamable-http user MCP server with bearer auth into mcp_servers
   ✓ buildCodexUserMcpServersThreadConfigPatch > preserves multiple user MCP servers as independent mcp_servers entries
 ✓ src/agents/cli-runner/bundle-mcp.codex.test.ts (1 tests) 9ms
 ✓ extensions/codex/src/app-server/thread-lifecycle.user-mcp-servers.test.ts (3 tests) 19ms
   ✓ startOrResumeThread — user mcp.servers projection (regression: #80814) > projects cfg.mcp.servers into the thread/start config patch under mcp_servers
   ✓ startOrResumeThread — user mcp.servers projection (regression: #80814) > omits mcp_servers from the start config when cfg has no user MCP servers
   ✓ startOrResumeThread — user mcp.servers projection (regression: #80814) > projects cfg.mcp.servers into resumed-thread config too so re-attached threads see user MCP
 ✓ src/plugins/contracts/plugin-sdk-root-alias.test.ts (28 tests) 162ms
 ✓ src/plugins/sdk-alias.test.ts (48 tests) 119ms

 Test Files  5 passed (5)
      Tests  84 passed (84)
```

```
Checking formatting...
Finished in 1937ms on 6 files using 1 threads.
All matched files use the correct format.
```

For contrast, the **same probe against the pre-fix tree** — reverting just the helper definition from `bundle-mcp-codex.ts` and re-running step 2 — produced `TypeError: buildCodexUserMcpServersThreadConfigPatch is not a function` (helper never existed before this patch); reverting just the wiring at `thread-lifecycle.ts:204` and re-running the wiring tests at step 3 produced `AssertionError: expected undefined to be defined` on the `mcp_servers` config-patch assertion (the existing `apps`-only merge has no `mcp_servers` key). Both confirm the projection is load-bearing.

**Observed result after fix:** The exact failure path described in #80814 — user-configured `mcp.servers.<name>` entries dropped from the codex app-server runtime's thread config while plugin-curated apps continued to work via the `apps` patch — now produces a complete `config.mcp_servers` JSON object on both `thread/start` (new thread) and `thread/resume` (re-attached thread). The codex-cli runtime's existing `injectCodexMcpConfigArgs` projection is unaffected; the codex app-server runtime now mirrors that behavior exactly. Empty-cfg, `sendPolicy`-style edge cases, reasoning/compaction payloads — none are affected because the helper short-circuits to `undefined` and `mergeCodexThreadConfigs` ignores `undefined` patches.

**What was not tested:** A live `codex app-server --listen stdio://` session against a real Codex auth profile and an actual MCP server (e.g. `@modelcontextprotocol/server-everything`) capturing the agent's `tools[]` enumeration before vs. after this patch. The acceptance criteria Codex listed for this PR explicitly include this kind of run when feasible. Not done here because it requires (a) a fresh Codex auth profile credential, (b) installation of the `@openclaw/codex` plugin into a local OpenClaw setup, and (c) a deterministic stub MCP server harness. The production code path from `openclaw/plugin-sdk/codex-mcp-projection` through `thread-lifecycle.ts` to the JSON-RPC `thread/start` config param is identical between the unit-test boundary and a live run — the wiring tests in step 3 capture the exact `params` object the production `client.request("thread/start", ...)` call receives.

## User-visible behavior change

Before: an agent under `agentRuntime.id: codex` with `mcp.servers.outlook` (or any user-configured MCP entry) in `openclaw.json` would silently lack the `outlook__*` tools at runtime, while `openclaw mcp list` reported the server configured. Operators saw an agent silently confabulate "I don't have outlook tools" responses despite the server child process being healthy.

After: the same configuration produces the expected `mcp_servers` block in the codex thread config, the codex app-server picks up the configured stdio/HTTP server entry, and `server__*` tools appear in the agent's tool catalog. The behavior now matches the `agentRuntime.id: codex-cli` runtime, which never had this gap.

Plugin-curated marketplace apps (`apps` configPatch) keep working unchanged — they remain on a separate config surface and are not double-counted into `mcp_servers`.

## Security impact

None. The helper reads `cfg.mcp.servers` — the same already-trusted, owner-managed surface that the codex CLI runtime, embedded Pi runtime, and `openclaw mcp list` consume. No new privileged surface, no credential exposure path. The per-server normalization is the exact `normalizeCodexServerConfig` function the CLI runtime has been using in production for headed and headerless MCP entries; we are reusing its bearer-token env-var decoding (which keeps secrets in env vars rather than embedding them in the config patch) and its env-header decoding (same). The new SDK subpath is registered as **private-local-only**, so third-party plugins cannot import it via `openclaw/plugin-sdk/...` — only the bundled `@openclaw/codex` extension can consume it.

### CODE REVIEW

**Comment by steipete** [comment]
Thanks @kinjitakabe. Landed the fix on main with your Co-authored-by credit:

- fix commit: https://github.com/openclaw/openclaw/commit/8a406528b4
- cleanup commit: https://github.com/openclaw/openclaw/commit/1f59031373

I kept the user mcp.servers projection, added binding fingerprint rotation so changed user MCP config starts a fresh Codex app-server thread instead of relying on ignored resume config, and fixed the unrelated Matrix SDK guardrail failure separately.

Proof:
- Crabbox AWS live E2E run_a737e826a2aa: Codex app-server loaded a temp user MCP server, called openclaw_e2e_probe.get_probe_token with a live OpenAI key, and persisted userMcpServersFingerprint on binding 019e22b2-995c-7232-a302-f451176f6535
- pnpm test extensions/codex/src/app-server/thread-lifecycle.user-mcp-servers.test.ts extensions/codex/src/app-server/session-binding.test.ts src/agents/cli-runner/bundle-mcp-codex.user-config.test.ts src/plugins/sdk-alias.test.ts src/plugins/contracts/plugin-sdk-root-alias.test.ts
- pnpm test src/plugins/contracts/plugin-sdk-package-contract-guardrails.test.ts extensions/matrix/src/test-runtime.ts
- pnpm plugin-sdk:api:check
- pnpm build

Closing this PR because main now contains the shipped fix.
