### ISSUE TITLE
v2026.3.7: Mattermost extension plugin fails to load - broken import path in monitor.ts

### ISSUE THREAD

**Issue by zeroxer** [openclaw/openclaw#40014]
## Description

After upgrading from v2026.3.2 to v2026.3.7, the bundled Mattermost extension plugin fails to load with the following error:

```
[gateway] [plugins] mattermost failed to load from extensions/mattermost/index.ts:
Error: Cannot find module '../../../../src/infra/parse-finite-number.js'
Require stack:
- extensions/mattermost/src/mattermost/monitor.ts
```

This causes the entire Mattermost channel to not start (no `[mattermost] connected` message appears).

## Root Cause

In `extensions/mattermost/src/mattermost/monitor.ts`, line:

```typescript
import { parseStrictPositiveInteger } from "../../../../src/infra/parse-finite-number.js";
```

This is a **source tree relative path** that doesn't exist in the published npm package. The module is only available as:

- Type declarations at `dist/plugin-sdk/infra/parse-finite-number.d.ts`
- Bundled JS chunks at `dist/parse-finite-number-*.js`

There is no `src/infra/parse-finite-number.js` in the published package, and `./plugin-sdk/infra/parse-finite-number` is not listed in `package.json` `exports` map, so neither a relative path nor a package specifier can resolve this module.

## Workaround

Replace the import with an inline function:

```typescript
// Replace this:
import { parseStrictPositiveInteger } from "../../../../src/infra/parse-finite-number.js";

// With this:
function parseStrictPositiveInteger(value: unknown): number | undefined {
  if (typeof value === "number" && Number.isInteger(value) && value > 0) return value;
  if (typeof value === "string") { const n = Number(value); if (Number.isInteger(n) && n > 0) return n; }
  return undefined;
}
```

## Suggested Fix

Either:
1. Add `"./plugin-sdk/infra/parse-finite-number"` to the `exports` map in `package.json`, or
2. Re-export `parseStrictPositiveInteger` from an existing public entry point (e.g., `openclaw/plugin-sdk/mattermost`), or
3. Bundle the extensions so they don't reference source paths

## Environment

- openclaw v2026.3.7 (installed via `npm install -g openclaw`)
- Node.js v22
- Ubuntu (systemd user service)
