### PR TITLE
fix(sqlite): support Node 23.0–23.10 runtimes lacking StatementSync.columns()

### LINKED ISSUE #90007: [Bug]: 2026.6.1 — plugin install index + task registry/flow sidecar migrations fail with "statement.columns is not a function" after upgrade from 2026.5.7
## Description

After upgrading from 2026.5.7 to 2026.6.1 via `openclaw update --yes`, the
post-update `openclaw doctor` step fails. The npm install + global swap succeed;
the doctor verification fails; the gateway is restarted but plugin/task state
stores are broken. The same `TypeError: statement.columns is not a function`
appears across three independent state migrations.

## Environment

- OS: macOS 25.3.0 (Darwin, arm64)
- Node: v23.9.0
- Install method: npm global
- Previous version: 2026.5.7
- Target version: 2026.6.1 (latest tag — just promoted from beta)

## Steps to reproduce

1. Have `openclaw@2026.5.7` installed globally with state in `~/.openclaw/`
2. Run `openclaw backup create`
3. Run `openclaw update --dry-run` (planned actions look normal)
4. Run `openclaw update --yes`

## Actual

```
Update Result: ERROR
  Before: 2026.5.7
  After:  2026.6.1
  Steps:
    ✓ global update (7.09s)
    ✓ global install swap (1.95s)
    ✗ openclaw doctor (2.24s)
        PluginStateStoreError: Failed to open the plugin state database.
```

`openclaw plugins doctor` shows the underlying cause:

```
- Failed migrating plugin install index /Users/<user>/.openclaw/plugins/installs.json:
  TypeError: statement.columns is not a function
- Failed migrating task registry sidecar /Users/<user>/.openclaw/tasks/runs.sqlite:
  TypeError: statement.columns is not a function
- Failed migrating task flow sidecar /Users/<user>/.openclaw/flows/registry.sqlite:
  TypeError: statement.columns is not a function
```

## Workaround

Downgrade to 2026.5.28 — migrations from 2026.5.7 → 2026.5.28 succeed cleanly.

```
npm install -g openclaw@2026.5.28
```

## Possible cause

`statement.columns()` is a method on `node:sqlite` prepared statements
(Node 22.16+/23.x). Node 23.9.0 should have it, so either:

1. The 2026.6.1 migration code is calling `.columns()` against a non-`node:sqlite`
   library (e.g. better-sqlite3 with a different API shape), or
2. The migration code in 2026.6.1 has a regression vs. 2026.5.28.

Happy to provide more logs or test a patch.

### PR DESCRIPTION
**Pull request by sjf**
## Summary

Fixes #90007. After upgrading to 2026.6.1, the post-update `openclaw doctor` step crashed on **Node 23.0–23.10** with:

```
TypeError: statement.columns is not a function
```

across the plugin install index, task registry sidecar, and task flow sidecar migrations.

### Root cause

`StatementSync.prototype.columns()` (node:sqlite) was **Added in: v23.11.0, v22.16.0** (per the [Node docs](https://nodejs.org/api/sqlite.html#statementcolumns)). Because Node 22 is LTS and got the backport, the timeline is non-linear: `.columns()` exists on **22.16+** (so all of our `engines: >=22.19.0` floor), on **23.11+**, and on **24+** — but **not on 23.0 through 23.10**. The reporter's **Node 23.9.0** lands squarely in that hole, yet satisfies the declared engine, so it is a supported runtime.

Both SQLite execute paths called `statement.columns()` unconditionally to decide between `.all()` (result-returning) and `.run()`:

- `src/infra/kysely-sync.ts` — the sync helper used by every state migration
- `src/infra/kysely-node-sqlite.ts` — the Kysely driver `executeQuery`

### Fix

Two changes, both centered in `src/infra/kysely-node-sqlite.ts`:

**1. Make the `.all()`-vs-`.run()` decision version-robust (`statementReturnsRows`).** Feature-detect `.columns()`; on runtimes that have it (Node 22.16+/23.11+/24+) behavior is unchanged. When it's absent (Node 23.0–23.10), classify result-returning statements from the typed Kysely operation node — **no SQL string parsing**:

- `SelectQueryNode` → rows
- `Insert`/`Update`/`DeleteQueryNode` → rows iff a `RETURNING` clause is present (`node.returning != null`)
- anything else → no rows (the dialect only ever raw-executes transaction-control statements — begin/commit/rollback/savepoint)

This is exact for every query OpenClaw runs through this dialect: all callers use Kysely builders, and the dialect itself only raw-executes transaction control.

**2. Coalesced the two duplicated execute paths to remove the duplication.** `statementReturnsRows` has to be shared by both call sites, and the surrounding bodies were already near-identical copies (`prepare` → row check → `all()`/`run()` → insert metadata). Rather than duplicate the new logic across both, the async driver's `executeQuery` and the sync helper's `executeCompiledSqliteQuerySync` are now unified into a single `executeCompiledQuerySync`, and both delegate to it. This also reconciles a pre-existing inconsistency where the two paths detected inserts differently (raw SQL `startsWith("insert")` vs `InsertQueryNode.is`) — they now share `InsertQueryNode.is`. Net result: `kysely-sync.ts` shrinks (its bespoke body is deleted), and the row-detection logic lives in exactly one place.

## Verification

Reproduced and verified against a standalone **Node v23.9.0** (the reporter's runtime) and local **Node v26**:

| | Node 23.9.0 (`columns` absent) | Node 26 (`columns` present) |
|---|---|---|
| **Before fix** | `TypeError: statement.columns is not a function` | ✅ works |
| **After fix** | ✅ all queries pass | ✅ all queries pass |

Exercised through both the sync helper (`executeSqliteQuerySync`, the path the migrations use) and the async Kysely driver: insert + `insertId`, select, `INSERT … RETURNING`, update, delete, `takeFirst`, transaction rollback, savepoints, and streaming — identical results on both runtimes.

New regression tests simulate a `node:sqlite` build without `StatementSync.columns()` (a `Proxy` that hides the method), so CI on Node 24 still exercises the fallback classifier through both the sync and driver entry points.

Local commands (normal source checkout):

```
pnpm tsgo:core && pnpm tsgo:core:test
node scripts/run-oxlint.mjs src/infra/kysely-node-sqlite.ts src/infra/kysely-sync.ts src/infra/kysely-node-sqlite.test.ts
node scripts/check-kysely-guardrails.mjs
pnpm test src/infra/kysely-node-sqlite.test.ts src/infra/kysely-sync.types.test.ts \
          src/plugins/installed-plugin-index-store.test.ts src/commands/doctor-state-migrations.test.ts
```

All green (kysely infra 7, types 1, doctor-state-migrations 51, installed-plugin-index 14).

Thanks to @TreyLawrence for the precise report and reproduction.

### CODE REVIEW

**Comment by sjf** [comment]
@clawsweeper review

**Comment by sjf** [comment]
@clawsweeper review

**Comment by sjf** [comment]
@clawsweeper review
