### PR TITLE
fix(agents): prevent transcript timer mocks from failing CI

### PR DESCRIPTION
**Pull request by steipete**
## What Problem This Solves

Resolves a problem where a passing agents test shard could fail with an unhandled `slot.idleTimer.unref is not a function` while a Claude transcript-probe test awaited a file append. This unrelated failure surfaced in #138960.

## Why This Change Was Made

Three tests replaced global timers with numeric handles and dropped unrelated callbacks. A native worker completing during that interval could throw before settling its result. The warning cases now use native scheduling; the delayed-flush test restores its one-shot grace observer before awaiting the append, then releases and joins its probe in `finally`.

The fix belongs to the tests that changed the global timer contract. Production code is unchanged; tests are +35/−52, net −17 lines. Existing success, grace-window, and structured-warning assertions remain.

## User Impact

No runtime behavior changes. CI can exercise transcript persistence alongside native worker completion without these tests corrupting timer handles or leaving asynchronous work unjoined.

## Evidence

The unchanged-source diagnostic released a real repository Worker/SAB fixture during the existing test's append and reproduced the exact native idle-timer error with an unsettled result. The same candidate scenario proves result settlement, successor thread reuse, idle retirement, replacement execution, and joined close. Injecting an append failure produces only the expected test failure; the probe joins and the global timer is restored.

The 59 transcript-helper tests, 13 native worker-pool tests, and full changed-file gate pass. The original 62-file CI subgroup passes 1,067 tests with one existing skip, using normal isolation, unchanged disk-reserve rules, and two workers. Six independent Codex review passes found no P0–P2 findings. Pinned Node timer declarations and Vitest spy implementation were inspected directly.

The local reproduction establishes the timer contract defect, but does not identify which production worker originally overlapped in hosted CI. Earlier full-shard attempts hit the host's real disk-capacity reserve; the final complete pass followed cleanup. The failing baseline diagnostic also triggered Vitest's process-exit trap during its own cleanup; that secondary instrumentation error is separate from the recorded native timer failure.

### CODE REVIEW

**Comment by steipete** [comment]
Merged via squash.

- Prepared head SHA: [90c4829b497c67765f1e00df39dfb17b9ebb7292](https://github.com/openclaw/openclaw/pull/138980/commits/90c4829b497c67765f1e00df39dfb17b9ebb7292)
- Landed commit: [cd4504de2dae09abbd1786ccca3b193535a1a01d](https://github.com/openclaw/openclaw/commit/cd4504de2dae09abbd1786ccca3b193535a1a01d)
