### ISSUE TITLE
Update fails on arm64: @discordjs/opus NEON compile error (node-v127)

### ISSUE THREAD

**Issue by jeadland** [openclaw/openclaw#23737]
## Bug Report

**Platform:** Raspberry Pi 5, Linux 6.12.62+rpt-rpi-2712 (arm64)
**Node:** v22.22.0
**OpenClaw version:** 2026.2.19-2 → tried updating to 2026.2.21-2

### Problem

`openclaw update` fails every time due to `@discordjs/opus` failing to compile from source. No prebuilt binary exists for `node-v127-napi-v3-linux-arm64-glibc-2.41`, so npm falls back to building from source — which fails.

### Error

```
npm error ../deps/opus/celt/arm/celt_neon_intr.c: In function 'celt_pitch_xcorr_float_neon':
npm error ../deps/opus/celt/arm/celt_neon_intr.c:208:18: error: implicit declaration of function 'celt_inner_prod_neon'; did you mean 'celt_inner_prod_c'?
npm error make: *** [deps/libopus.target.mk:310: Release/obj.target/libopus/deps/opus/celt/arm/celt_neon_intr.o] Error 1
npm error gyp ERR! build error
```

### Workaround

```bash
npm install -g openclaw --ignore-scripts
```

This skips the native build and installs successfully. Confirmed working on 2026.2.21-2 after applying.

### Suggested Fix

Either:
1. Mark `@discordjs/opus` as `optionalDependencies` so a build failure doesn't block the install, or
2. Add a prebuilt binary for `node-v127/arm64`, or
3. Have `openclaw update` automatically retry with `--ignore-scripts` on compile failure

### Impact

Every arm64 user on Node v22+ is stuck on their current version and can't update without knowing this workaround.
