### PR TITLE
fix(bash): add missing path import and DEFAULT_PATH constant

### PR DESCRIPTION
**Pull request by velvet-shark**
Fixing the breaking changes that prevented me from building clawdis, going through onboarding and setting everything up. Only after making these changes did everything go through.

## Error when doing `pnpm build`

```bash
clawdis main ❯ pnpm build

> clawdis@2.0.0-beta5 build /home/radek/Developer/clawdis
> tsc -p tsconfig.json && tsx scripts/canvas-a2ui-copy.ts

src/agents/pi-embedded-runner.ts:489:27 - error TS2339: Property 'queueMessage' does not exist on type 'AgentSession'.

489             await session.queueMessage(text);
                              ~~~~~~~~~~~~

src/gateway/server.ts:860:26 - error TS18047: 'bridge' is possibly 'null'.

860       bridge ? (opts) => bridge.sendEvent(opts) : undefined,
                             ~~~~~~

src/gateway/server.ts:866:26 - error TS18047: 'bridge' is possibly 'null'.

866       bridge ? (opts) => bridge.sendEvent(opts) : undefined,
                             ~~~~~~

src/gateway/server.ts:872:22 - error TS18047: 'bridge' is possibly 'null'.

872       bridge ? () => bridge.listConnected() : undefined,
                         ~~~~~~

src/gateway/server.ts:873:26 - error TS18047: 'bridge' is possibly 'null'.

873       bridge ? (opts) => bridge.sendEvent(opts) : undefined,
                             ~~~~~~


Found 5 errors in 2 files.

Errors  Files
     1  src/agents/pi-embedded-runner.ts:489
     4  src/gateway/server.ts:860
 ELIFECYCLE  Command failed with exit code 1.
```

## Summary

- Add missing `import path from "node:path"` required for `path.sep`, `path.posix.sep`, `path.posix.join` usage
- Add missing `DEFAULT_PATH` constant used in `buildSandboxEnv()`

These were introduced in 3b075dff (feat: add per-session agent sandbox) and break the build:

```
src/agents/bash-tools.ts(831,11): error TS2304: Cannot find name 'DEFAULT_PATH'.
src/agents/bash-tools.ts(888,33): error TS2304: Cannot find name 'path'.
src/agents/bash-tools.ts(888,48): error TS2304: Cannot find name 'path'.
src/agents/bash-tools.ts(891,9): error TS2304: Cannot find name 'path'.
```

## Test plan

- [x] `pnpm build` passes
- [x] `pnpm lint` (no new warnings)

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by steipete** [comment]
Hi Radek! Better ping me on Discord if you see this. Usually I'm already on it, and it's much faster to type "fix ci" than to review a PR.

**Comment by steipete** [comment]
Thanks for the report! This change is already on main (path import + DEFAULT_PATH), so I’m closing this PR as redundant. Appreciate the help.

**Comment by velvet-shark** [comment]
> Hi Radek! Better ping me on Discord if you see this. Usually I'm already on it, and it's much faster to type "fix ci" than to review a PR.

You did say to submit a PR on Discord, so I did :)
Glad to see that it's fixed already.
