### ISSUE TITLE
Module Not Found After Upgrading to 2026.5.2 (ERR_MODULE_NOT_FOUND)

### ISSUE THREAD

**Issue by visionzhang-prog** [openclaw/openclaw#76425]
1. Environment
OS: macOS (Apple Silicon / m2)
Node Version: v22.22.2 (managed via fnm)
OpenClaw Version: 2026.5.2
Package Manager: npm
2. Problem Description

After upgrading to OpenClaw 2026.5.2, the Gateway process starts, but core functionalities (including Feishu, DingTalk, and internal dispatch/runtime) crash immediately with ERR_MODULE_NOT_FOUNDerrors.

The root cause appears to be stale hashed runtime artifacts. The running Gateway process attempts to import JavaScript files with old hash suffixes (e.g., -CtxgXAPs) that no longer exist after the upgrade overwrote the dist/directory.

3. Steps to Reproduce
Ensure Node version is v22.22.2 using fnm.
Upgrade OpenClaw globally:
npm install -g openclaw@2026.5.2
Start the gateway:
openclaw start
Send a test message via Feishu or DingTalk, or observe initialization logs.
4. Observed Behavior & Logs (Sanitized)

The logs consistently show failures to resolve paths containing hashed filenames within the ~/.local/share/fnm/.../openclaw/dist/directory.

Example Errors:
Feishu Channel Dispatch Failure:
error gateway/channels/feishu feishu[default]: failed to dispatch message: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/[USER]/.../openclaw/dist/reply-media-paths.runtime-CtxgXAPs.js' imported from .../dist/dispatch-DGQApgF3.js
General Inbound Runtime Failure:
error channels/feishu Cannot find module '/Users/[USER]/.../openclaw/dist/inbound.runtime-By6GtcRw.js'
DingTalk SDK Dispatch Failure:
error [DingTalk:__default__] SDK dispatch failed: Cannot find module '/Users/[USER]/.../openclaw/dist/reply-media-paths.runtime-CtxgXAPs.js'
5. Expected Behavior

The gateway should correctly regenerate all runtime assets upon upgrade. A simple restart (openclaw start) should not result in MODULE_NOT_FOUNDerrors caused by stale file references.

6. Temporary Workaround

Manually killing all Node processes and clearing runtime caches resolves the issue until the next upgrade:
pkill -f openclaw
pkill -f node
rm -rf ~/.openclaw/plugin-runtime-deps
npm uninstall -g openclaw
npm install -g openclaw@2026.5.2
openclaw start
7. Additional Context

This issue was not observed in version 2026.4.25. The problem seems related to the upgrade mechanism between 2026.4.x and 2026.5.x not properly handling the regeneration of runtime assets while the gateway is running.

**Comment by apex-system** [comment]
Field update from a local macOS/Homebrew install on 2026.5.7.

Observed failure before repair:
- OpenClaw package was installed at 2026.5.7, but the running LaunchAgent Gateway still reported self version 2026.5.6.
- Gateway RPC handlers failed with stale hashed chunk imports, including `bash-tools-BvsIc29z.js`, `task-registry.maintenance-CvTYvEjK.js`, `status.link-channel-C7zLFzlT.js`, and `secrets-BXw8r2d-.js`.
- Slack config/status checks were blocked by those stale imports.

Repair path that worked:
- `openclaw gateway restart --safe --json` was accepted, but joined an existing pending restart and did not reload the stale PID.
- `openclaw gateway restart --force --json` killed the stale Gateway PID and relaunched the LaunchAgent.

Post-restart proof:
- `openclaw gateway status` showed a new Gateway PID listening on `127.0.0.1:18789`.
- Fresh `openclaw status --json` reported runtime/self version 2026.5.7 and no secret diagnostics.
- Fresh `openclaw channels status --json --probe` reported Slack `running: true`, `connected: true`, `healthState: healthy`, and probe `ok: true` / HTTP 200.
- Logs after restart showed `gateway ready` and `slack socket mode connected`.

Notes:
- This supports the stale-live-process explanation for package updates that replace `dist/` while an old Gateway process remains alive.
- In this case, a normal/safe restart request was not sufficient; a force restart was needed to clear the old process.
- I did not verify a real inbound Slack message in this run, only Gateway health, Slack socket connection, and Slack API probe.

**Comment by apex-system** [comment]
Follow-up from the same machine after the stale-dist restart fix.

Observed a separate failure mode from Slack after local exec tools completed successfully:

- Local exec commands finished and Slack showed the tool completion.
- The final assistant reply then failed with: `The model did not produce a response before the model idle timeout...`
- Gateway logs showed `Profile google:default timed out` and `embedded_run_failover_decision ... fallbackConfigured=false ... provider=google model=gemini-2.5-flash`.
- Attempting to add `openai/gpt-5.5` as a fallback was not safe on this host because the `opopenai` secret provider can time out during Gateway startup. I removed that fallback so startup is not blocked by an unavailable OpenAI secret.
- Set `agents.defaults.timeoutSeconds` to `600` as a safer host-level mitigation for the current Google primary model.

Verification after restart:

- Gateway restarted cleanly and is reachable on 127.0.0.1:18789.
- Runtime version: 2026.5.7.
- Slack socket mode reconnected and `channels status --probe` reports Slack probe HTTP 200.
- Non-delivered diagnostic agent turn against `google/gemini-2.5-flash` returned `PONG` in ~4.7s.

Remaining risk:

- This does not prove a real inbound Slack message end-to-end; it proves Gateway, Slack probe, and a direct agent/model turn.
- The host still depends on 1Password exec secret providers (`op*`) during cold startup, and those have previously timed out at 30s. That is likely a separate durability issue.

**Comment by IgnacioPro** [comment]
I hit what looks like the same stale-hash / mixed-dist family on Linux x64, but the visible symptom is Telegram `message.action=send` failing locally before any provider call.

New issue with full evidence: #81461

Key details from this repro:
- `openclaw --version` = `2026.5.3 (06d46f7)`
- `openclaw status` still reports `Gateway self ... app 2026.5.2`
- `message` tool error: `Cannot find module '/usr/lib/node_modules/openclaw/dist/action-runtime-JVgOnJIQ.js' imported from /usr/lib/node_modules/openclaw/dist/probe-gofM6JmN.js`
- those exact files are missing on disk, while sibling hashed chunks exist (`action-runtime-CYqPrZR6.js`, `probe-DoAxOwuy.js`)
- controlled restart + manual restart did not clear it

So this is not just inbound/runtime boot; it is also breaking outbound tool-driven message delivery.
