### ISSUE TITLE
[Bug]: 2026.04.29 installation：failed to load bundled channels  安装报错：信道配置全部丢失

### ISSUE THREAD

**Issue by yaaboo-gif** [openclaw/openclaw#76022]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

After upgrading from 4.27 to 4.29 by 'openclaw update', it takes about 5 mins for the automatic doctor post installation diagnosis, and 'openclaw status' shows the follwoing message after the 1st post-installation run; 
执行 openclaw update 从 4.27 升级到 4.29 后，安装后的自动诊断（doctor）流程大约耗时 5 分钟。在首次安装后运行时，openclaw status 会显示以下错误信息：

17:17:55 [channels] failed to load bundled channel discord: Cannot find module 'discord-api-types/v10'
Require stack:

/opt/homebrew/lib/node_modules/openclaw/dist/extensions/discord/discord-dGuI-41N.js
17:17:56 [channels] failed to load bundled channel nostr: Cannot find module 'nostr-tools'
Require stack:
/opt/homebrew/lib/node_modules/openclaw/dist/extensions/nostr/setup-surface-DxAaUTyC.js
17:17:57 [channels] failed to load bundled channel slack: Cannot find module '@slack/web-api'
Require stack:
/opt/homebrew/lib/node_modules/openclaw/dist/extensions/slack/client-CPe4GmDR.js
17:17:57 [channels] failed to load bundled channel telegram: Cannot find module 'grammy'
Require stack:
/opt/homebrew/lib/node_modules/openclaw/dist/extensions/telegram/send-t4GTTdHF.js

All channels that are working properly under 4.27 are now lost at all. 
之前在 4.27 版本下正常工作的所有频道，现在已全部失效。

The agent prompoed the following instruction, but no channels  are back even after these dependencies are properly installed. 
按照代理（agent）提示的指令操作后，即便这些依赖项已正确安装，所有频道依然未能恢复。

```
cd /opt/homebrew/lib/node_modules/openclaw && npm install discord-api-types@v10.0.0 nostr-tools@v2.0.0 @slack/web-api@v6.12.0 grammy@v1.42.0
```

### Steps to reproduce

1. Openclaw update
2. OpenClaw doctor
3. cd /opt/homebrew/lib/node_modules/openclaw && npm install discord-api-types@v10.0.0 nostr-tools@v2.0.0 @slack/web-api@v6.12.0 grammy@v1.42.0

### Expected behavior

All channels should be working propoerly post version upgrades and installations. 

### Actual behavior

All channels are lost at all.

### OpenClaw version

2026.04.29

### Operating system

macOS 26.5 (25F5068a)

### Install method

openclaw update

### Model

ollama/qwen3.5/deepseek v4 Flash/GLM5.1/Codex GPT5.4

### Provider / routing chain

openclaw -> ollama/qwen3.5 (local model)

### Logs, screenshots, and evidence

```shell

```

**Comment by zolawuzhigang** [comment]
由于4.29版本目前已经存在的各种严重问题，经过我29轮的16个版本的单独测试，已经找到完美解决办法
目前4.29版本存在的问题：
1.进程堵塞，memory-wiki会严重堵塞主进程，导致任何消息都无法发送和处理
2.在升级后，每次请求都需要全量重新加载一遍所有工具，token消耗相比之前提升20倍
3.在升级后，由于1-2问题，你只能重启网关，在重启网关后会丢失大量会话信息与记忆和缓存文件，丢失数据
4.大量插件无法与其他版本适配，个别工具几乎无法使用

完美解决办法：
由于我的生产遇到了该类问题，对我造成了严重的精神伤害，在一夜的修复过程中，已经找到了完美解决办法，就是将升级后的4.29版本降级到4.27版本，只有这一个版本其他版本仍存在一些故障，且有严格命令，详细命令如下：

openclaw gateway stop

npm install -g openclaw@2026.4.27

openclaw --version

openclaw plugins list

严格按照上述命令在cli中按照顺序执行，严格执行，错一条都不行，尤其是第二条，这是在我巨大精神折磨下，穷尽所有命令与版本虚拟机故障复原测试中得出的唯一解决办法，可以解决所有版本升级到4.29版本的故障

好处：
在执行此方案后，你的openclaw不仅会恢复以前所有功能，且memory-wiki功能相比其他任何版本都会无比稳定
根据我们生产目前解决后的使用情况来看，已经连续8个小时任务复杂任务不报错，且流畅度与使用体验是目前所有版本中最优

按照此方案一定能够解决你遇到的问题版本问题，这是我穷尽了所有版本与虚拟机生产故障复原单元测试出的唯一方案，注意是唯一方案

最后留言：
由于此事故影响范围大，问题严重，故此在社区分享此办法，
按照此方案解决问题后的兄弟，希望能够去我们github项目下，为我的相关项目点个star 星星即可，
方案找到不易，给个start星星即可，万分感谢！
