### ISSUE TITLE
openclaw tui hangs on all agents after upgrading to 2026.4.29 — WebSocket handshake timeout, missing dist file

### ISSUE THREAD

**Issue by bryanbaer** [openclaw/openclaw#75717]
## Summary

Upgrading from `2026.4.11` to `2026.4.29` via `openclaw gateway update.run` causes all `openclaw tui` sessions to hang indefinitely for **all agents**. TUI never completes the WebSocket handshake. Processes spin at 50–92% CPU until killed. Only fix was downgrading to `2026.4.11`.

## Environment

- **Before (working):** OpenClaw `2026.4.11` (769908e)
- **After (broken):** OpenClaw `2026.4.29` (a448042)
- **OS:** macOS Darwin 25.4.0 arm64
- **Node:** v25.6.1
- **Install:** `npm install -g openclaw@latest` via `openclaw gateway update.run`
- **Gateway:** LaunchAgent, bind=lan, port 18789

## Steps to Reproduce

1. `openclaw gateway update.run` from 2026.4.11
2. Confirm gateway restarts on 2026.4.29
3. `openclaw tui` (any agent)
4. TUI shows `connecting | idle` then `gateway disconnected: closed`

## Observed Behavior

- Gateway HTTP `/health` returns 500 immediately after upgrade restart
- WebSocket handshake times out (`cause: handshake-timeout`)
- Root cause in logs: `Cannot find module '.../dist/control-ui-BKlfXfAt.js'` — stale hashed dist file not cleaned by npm update
- Re-running `npm install -g openclaw@latest` regenerated the file but 500 and timeouts persisted
- All TUI sessions hung 50–92% CPU, required `kill -9`
- Affects ALL agents (default and non-default)
- Ollama discovery probe fires at TUI client startup regardless of `enabled: false` in config

## Expected Behavior

`openclaw tui` connects within ~2 seconds as on 2026.4.11.

## Workaround

`npm install -g openclaw@2026.4.11`

## Relevant Logs

```
[gateway-http] unhandled error: Cannot find module
'/opt/homebrew/lib/node_modules/openclaw/dist/control-ui-BKlfXfAt.js'
code: 'ERR_MODULE_NOT_FOUND'

gateway/ws: handshake timeout conn=3e07d582
  cause: handshake-timeout, handshakeMs: 10000

gateway connect failed: Error: gateway closed (1000):
```

## Root Cause Hypothesis

`update.run` npm global install leaves stale hashed dist files from the previous version. New version references `control-ui-BKlfXfAt.js` in its import map but installed file is `control-ui-Cf8YUkqZ.js`. A pre-clean step in `update.run` is needed to remove old dist files before writing new ones.

Approximately 2 hours of productive work lost to this regression. A pre-flight check verifying all referenced dist files exist before restarting the gateway would prevent this.

**Comment by chengoak** [comment]
Any update on this? The TUI hang and WebSocket timeout issue is still present in 4.29, making the release unusable for many users. Would be great to know the ETA for a fix.
