### ISSUE TITLE
Beta blocker: openclaw-snowluma - runtime.channel.reply.formatInboundEnvelope is not a function in 2026.8.1-beta.2

### ISSUE THREAD

**Issue by unknowbug** [openclaw/openclaw#124133]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

Yes

### Summary

After upgrading to 2026.8.1-beta.2, the openclaw-snowluma channel plugin fails every inbound dispatch with `TypeError: runtime.channel.reply.formatInboundEnvelope is not a function`, so QQ messages are no longer processed.

### Steps to reproduce

1. Install OpenClaw `2026.8.1-beta.2` (npm global) on Windows.
2. Enable the `openclaw-snowluma` channel plugin (v0.6.0) with a configured group/DM allowlist.
3. Send a message to an allowed group or DM.
4. Observe the gateway log.

### Expected behavior

Inbound messages dispatch normally to the configured agent, as observed on `2026.7.1-2`.

### Actual behavior

The SnowLuma socket connects and the gateway reports `ready (selfId=...)`, but every inbound batch fails:

```
error channels/snowluma [snowluma:default] dispatchBatch failed: TypeError: runtime.channel.reply.formatInboundEnvelope is not a function
```

### OpenClaw version

2026.8.1-beta.2 (8f382a2)

### Operating system

Windows 11 (10.0.26200, x64)

### Install method

npm global

### Model

N/A — channel inbound dispatch (no model request involved)

### Provider / routing chain

N/A — channel inbound dispatch (no provider routing involved)

### Logs

```shell
error channels/snowluma [snowluma:default] dispatchBatch failed: TypeError: runtime.channel.reply.formatInboundEnvelope is not a function
```

### Impact and severity

- Affected: openclaw-snowluma (QQ) users on `2026.8.1-beta.2`; any channel plugin that calls `runtime.channel.reply.formatInboundEnvelope`
- Severity: High (blocks all inbound message processing for the channel)
- Frequency: Always (every inbound batch)
- Consequence: QQ group/DM messages are received by the bot but never dispatched to the agent; no replies are produced

### Additional information

Root cause (confirmed by source inspection): the core's plugin runtime `runtime.channel.reply` object (built in the channel runtime) exposes `formatAgentEnvelope` and `resolveEnvelopeFormatOptions`, but does not expose `formatInboundEnvelope`. The plugin SDK (`openclaw/plugin-sdk`, channel-inbound) exports `formatInboundEnvelope` as a standalone function, but the SnowLuma plugin calls it on `runtime.channel.reply`, which is undefined in 2026.8.1-beta.2.

Suggested fix: expose `formatInboundEnvelope` on `runtime.channel.reply` alongside `formatAgentEnvelope` (verified locally: adding it restores inbound dispatch).

Last known good: `2026.7.1-2`. First known bad: `2026.8.1-beta.2`.

**Comment by MilkyWay008** [comment]
Saw the same `formatInboundEnvelope is not a function` trace on the beta. The 2026.8.1-beta.2 core moved that member off `runtime.channel.reply` and the snowluma plugin still expects it there, so no config change is gonna bring it back. Roll back with `npm install -g openclaw@2026.7.1-2`, that was the last good build, and the channel should come back up. Oh and btw, I built a portable Hermes OTG that runs off a USB stick, I keep it around as a rescue agent for exactly these update-broke-it moments, https://github.com/MilkyWay008/Hermes-OTG if you want to poke at it.

**Comment by unknowbug** [comment]
Update from the reporter: this is resolved on my end.

**Environment:** OpenClaw 2026.8.2 (0965053) on Windows 11 + openclaw-snowluma 0.9.0.

**Verification:** The channel now works end-to-end:
- Gateway connects: `[snowluma:default] gateway ready (selfId=...)`
- Inbound messages dispatch normally to the agent — no more `dispatchBatch failed: TypeError: runtime.channel.reply.formatInboundEnvelope is not a function`
- Outbound replies are delivered to QQ groups/DMs

**Root cause confirmation:** The SnowLuma plugin has migrated off the retired `runtime.channel.reply.formatInboundEnvelope` API (0.6.0 → 0.9.0), which matches the direction ClawSweeper recommended — migrate to the public channel-inbound SDK rather than restoring the runtime member. No core-side change is needed.

Suggest closing this issue as resolved. Thanks to everyone who weighed in.
