### PR TITLE
fix(ci): restore native PR merge tests after author verification

### LINKED ISSUE #145214: Native PR merge success tests fail after author verification
The native PR merge success tests fail after #145128 added published-commit author verification during squash-body preparation. The shared main-refresh fixture does not implement the new GitHub commit lookup, so valid synthetic merges stop before dispatch.

CI run [34635760951](https://github.com/openclaw/openclaw/actions/runs/34635760951), whose checkout merged the unrelated Node cleanup into main commit `ba8294bd0eaf5a1ae29d7c8526bc5f3515bfeb3f`, failed in:

- [Shard 28](https://github.com/openclaw/openclaw/actions/runs/34635760951/job/103383435292): `test/scripts/pr-main-refresh.test.ts`, “completes supervised merge with two checkpoints and releases its exact lock after cleanup.”
- [Shard 29](https://github.com/openclaw/openclaw/actions/runs/34635760951/job/103383435336): `test/scripts/pr-merge-hosted.test.ts`, “dispatches once with the exact prepared head and ordinary server enforcement.”

Both report `Unexpected GitHub API endpoint repos/fixture/repo/commits/<SHA>`. The fixture remains unchanged on main `8b343fce338da60722778eb2e25acdb936c88b40`; running the two existing test files there reproduces exactly those two failures with 64 passing cases.

Update the shared fixture to provide the published-commit author and GraphQL PR author responses consumed by the existing squash-body path. Keep the production wrapper and current merge, cleanup, and refusal assertions intact.

### PR DESCRIPTION
**Pull request by steipete**
Closes #145214

## What Problem This Solves

Resolves a problem where unrelated PRs fail the native merge-success CI tests after #145128 introduced published-commit author verification. The shared fixture rejects the new commit lookup before the synthetic merge can dispatch.

## Why This Change Was Made

Complete the shared fixture’s GitHub response contract: return raw commit-author data from its real Git objects with the synthetic linked user, and include the PR author in the GraphQL squash preview. Its existing output boundary continues to apply `--jq`. The change adds ten test-support lines and preserves production code and every test assertion.

## User Impact

Restores reliable CI coverage for the native PR merge workflow. No product behavior changes.

## Evidence

At base `8b343fce338da60722778eb2e25acdb936c88b40`, the unchanged tests reproduced the [two CI failures](https://github.com/openclaw/openclaw/actions/runs/34635760951): **64 passed, 2 failed**. After the fixture repair, the same 66 cases in the same order **all passed**.

```sh
node scripts/run-vitest.mjs test/scripts/pr-main-refresh.test.ts test/scripts/pr-merge-hosted.test.ts
node scripts/check-changed.mjs -- test/scripts/pr-main-refresh.test-support.ts
```

The selected root-test/tooling gate, formatting, and `git diff --check` passed. Independent review found no actionable issues through P2.

### CODE REVIEW

**Comment by steipete** [comment]
Superseded by #145170, which landed the shared fixture repair in [03234b50810910cd0075a5a325073f28123d51d3](https://github.com/openclaw/openclaw/commit/03234b50810910cd0075a5a325073f28123d51d3) while this PR was being published. The broader commit matcher here is unnecessary for the affected cases.

Verified the exact landed commit in an isolated checkout with the normal test runner. Both originally failing cases passed:

- `pr-main-refresh.test.ts`: completes supervised merge with two checkpoints and releases its exact lock after cleanup.
- `pr-merge-hosted.test.ts`: dispatches once with the exact prepared head and ordinary server enforcement.

Result: **2 passed**; the other 64 cases were unselected by the explicit name filter.

Closing without merge; the candidate branch and evidence are preserved.
