### ISSUE TITLE
v2026.3.23 regression: memory-lancedb-pro plugin tools fail with 'stringEnum is not a function'

### ISSUE THREAD

**Issue by bo-blue** [openclaw/openclaw#53339]
## Summary

After upgrading to v2026.3.23, the memory-lancedb-pro plugin fails to register its management tools with `TypeError: (0 , _pluginSdk.stringEnum) is not a function`. The plugin loads and hooks fire, but all tool calls fail.

## Error

```
[plugins] plugin tool failed (memory-lancedb-pro): TypeError: (0 , _pluginSdk.stringEnum) is not a function
```

Appears 4+ times per agent turn in gateway.err.log.

## Impact

- memory_recall, memory_store, memory_stats tools all fail silently
- Auto-capture (agent_end hook) and auto-inject (before_agent_start) still appear to work
- Management tools are broken

## Root Cause (suspected)

The plugin uses `stringEnum` from the OpenClaw plugin SDK. This function appears to have been removed or renamed in v2026.3.23, breaking plugins built against the previous SDK API.

## Steps to Reproduce

1. Install memory-lancedb-pro plugin
2. Upgrade to v2026.3.23
3. Start gateway — see repeated `plugin tool failed` errors in gateway.err.log

## Environment

- OpenClaw CLI: v2026.3.23 (rolled back to v2026.3.22 to recover)
- Companion app: v2026.3.23 macOS
- Plugin: memory-lancedb-pro v1.0.32
- macOS: 26.3.1 arm64
- Worked on v2026.3.22

**Comment by Hollychou924** [comment]
## Root cause: stringEnum removed from plugin-sdk in v2026.3.23 (same breaking change as #52842)

This is the same SDK breaking change reported in #52842 — `stringEnum` was removed from `@openclaw/plugin-sdk` without a backward-compatible shim or changelog entry.

### What happened

In v2026.3.23, `stringEnum` was removed (or renamed) from the plugin SDK. Plugins built against the previous API that import `{ stringEnum }` from `@openclaw/plugin-sdk` will fail at runtime with:

```
TypeError: (0 , _pluginSdk.stringEnum) is not a function
```

The function is still called (it exists in the import), but resolves to `undefined` — hence "is not a function" rather than a module-not-found error.

### Fix direction

**For the OpenClaw core team:** Add a backward-compatible re-export shim in `plugin-sdk/index.ts`:

```ts
// backward compat shim — remove after 2 major versions
/** @deprecated use Type.Union([Type.Literal('a'), Type.Literal('b')]) instead */
export function stringEnum<T extends string>(values: readonly T[]): TUnion<TLiteral<T>[]> {
  return Type.Union(values.map(v => Type.Literal(v))) as any;
}
```

This matches the pattern discussed in #52842 (23-line compat shim). The migration path is to use TypeBox's `Type.Union([Type.Literal(...)])` pattern directly.

**For plugin authors affected now:**

Replace `stringEnum` usage with TypeBox inline:
```ts
// Before (broken in v2026.3.23)
import { stringEnum } from '@openclaw/plugin-sdk';
const myField = stringEnum(['option1', 'option2']);

// After (TypeBox pattern)
import { Type } from '@sinclair/typebox';
const myField = Type.Union([Type.Literal('option1'), Type.Literal('option2')]);
```

### Related

- #52842 — original report of `stringEnum` removal without changelog
- This issue confirms the same breakage affects third-party plugins in the ClawHub ecosystem, not just internal plugins

**Comment by steipete** [comment]
Codex maintainer triage: closing this into #68279 as the current canonical tracker for the bare `openclaw/plugin-sdk` missing `stringEnum` / `optionalStringEnum` compatibility break. Current `main` still returns `undefined` for both helpers from `src/plugin-sdk/index.ts`, while `src/plugin-sdk/core.ts` exports them; PR #66214 is the active fix attempt and needs baseline/test/docs follow-through before merge.
