### ISSUE TITLE
[Bug]: [Regression] `openclaw doctor` throws TypeError after upgrading to 2026.6.5 stable

### ISSUE THREAD

**Issue by cn1313113** [openclaw/openclaw#91991]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

After upgrading from `2026.6.5-beta.5` to `2026.6.5` stable, `openclaw doctor` throws:

TypeError: (0, _sessionStoreRuntime.resolveAllAgentSessionStoreTargetsSync) is not a function

### Steps to reproduce

`resolveAllAgentSessionStoreTargetsSync` exists in `targets-C2SNGXVF.js` but is **not re-exported** from `plugin-sdk/session-store-runtime.js` / `.d.ts` in the stable release.

Multiple dist files import it from `./targets-C2SNGXVF.js` correctly, but some code paths attempt to import it from `openclaw/plugin-sdk/session-store-runtime`, which fails.

### Expected behavior

.

### Actual behavior

.

### OpenClaw version

2026.6.5 stable (regression from 2026.6.5-beta.5)

### Operating system

Ubuntu

### Install method

pnpm

### Model

qwen3.7-plus

### Provider / routing chain

Unknown

### Logs, screenshots, and evidence

```shell

```

## Workaround
Manually add the missing re-export to:
- `dist/plugin-sdk/session-store-runtime.js`
- `dist/plugin-sdk/session-store-runtime.d.ts`

Import from `../targets-C2SNGXVF.js` and add `resolveAllAgentSessionStoreTargetsSync` to the export list.

## Suggested Fix
Ensure `resolveAllAgentSessionStoreTargetsSync` is re-exported from `plugin-sdk/session-store-runtime` in the build process, or update all consumers to import directly from the internal `targets` module.

**Comment by amknight** [comment]
**Root cause confirmed — but it's plugin/core version skew, not a missing re-export in the 2026.6.5 build.** The supported fix is one command, no dist patching needed:

```
openclaw plugins update feishu
```

What actually happened:

- #91322 (merged 2026-06-08) added `resolveAllAgentSessionStoreTargetsSync` to the public SDK subpath `openclaw/plugin-sdk/session-store-runtime`, and the Feishu plugin's doctor started consuming it. That state shipped in `openclaw@2026.6.5-beta.5` **and** `@openclaw/feishu@2026.6.5-beta.5` — a consistent pair, which is why beta.5 worked.
- #91322 was then reverted before beta.6/stable (`9075912386` on the release line, `7f1d82ab25` on main), removing both the SDK export and its in-repo consumer. Each release is internally consistent: I unpacked the published `openclaw@2026.6.5` tarball — every core reference to this function imports from the shared `targets-C2SNGXVF.js` chunk, and no file in the core package imports it from `plugin-sdk/session-store-runtime`. So there is no dropped re-export in the core build.
- The dangling import lives in the **installed plugin**: `@openclaw/feishu@2026.6.5-beta.5` (`dist/channel-DR5JCyFd.js`) imports `resolveAllAgentSessionStoreTargetsSync` from `openclaw/plugin-sdk/session-store-runtime`. beta.5 is the only affected plugin version — `@openclaw/feishu@2026.6.5-beta.6` and `@openclaw/feishu@2026.6.5` no longer reference it.
- Plugins load through jiti's ESM→CJS transform, so the missing named export becomes `undefined` at call time instead of failing at import — hence `TypeError: (0, _sessionStoreRuntime.resolveAllAgentSessionStoreTargetsSync) is not a function`, and only in `openclaw doctor`: the Feishu doctor adapter (`runConfigSequence`) is the sole caller, so normal messaging is unaffected.

So: upgrading core beta.5 → stable while keeping the beta.5 Feishu plugin produces exactly this crash. Updating the plugin (docs: https://docs.openclaw.ai/plugins/manage-plugins) resolves it today; after switching trains (beta → stable), update installed plugins alongside core.

We're not re-adding the export to core: it existed in exactly one beta tag (~1 day), its only consumer was fixed in the next beta, and keeping a stale beta plugin running against stable core isn't a supported state. The separate robustness gap this exposed — one failing plugin doctor adapter aborting the entire `doctor` run instead of degrading to a warning — is worth fixing on its own and doesn't need this issue open.

Closing as not planned (resolved by updating the plugin). If you still hit this TypeError with `@openclaw/feishu@2026.6.5` or later installed (check `openclaw plugins list`), or from a plugin other than Feishu, please comment with the plugin list and full stack trace and we'll reopen.

Related: #91816 (same root cause, hit during `openclaw update`).
