### ISSUE TITLE
Bug: contradictory plugins.allow guidance for /lossless command on 2026.4.11

### ISSUE THREAD

**Issue by mcdeeai** [openclaw/openclaw#65319]
# OpenClaw bug report draft: contradictory `/lossless` allowlist guidance on 2026.4.11

## Summary
On OpenClaw 2026.4.11, the CLI gives contradictory guidance for the bundled `lossless-claw` command surface.

- The runtime error for `openclaw /lossless` says `plugins.allow` must include `"/lossless"`.
- The config validator/schema says `plugins.allow` only accepts plugin ids, and warns that `"/lossless"` and `"/lcm"` are stale/invalid because they are commands, not plugins.

This creates an impossible configuration:
- if `"/lossless"` is absent, runtime says to add it
- if `"/lossless"` is present, config validation warns it is invalid and should be removed

## Environment
- OpenClaw version: 2026.4.11
- Prior version audited before update: 2026.4.10
- Host: macOS arm64
- lossless-claw plugin installed and enabled
- `plugins.allow` includes `lossless-claw`
- `plugins.entries.lossless-claw.enabled = true`
- `plugins.slots.contextEngine = lossless-claw`

### Config state
Use a valid plugin-only allowlist such as:

```json
"plugins": {
  "allow": [
    "telegram",
    "discord",
    "lossless-claw",
    "browser",
    "exa",
    "google",
    "openai",
    "ollama",
    "openrouter",
    "memory-core"
  ]
}
```

### Step 1
Run:

```bash
cd /Users/mcdee/.openclaw/workspace && openclaw /lossless
```

### Actual result
CLI fails with:

```text
[openclaw] Failed to start CLI: Error: The `openclaw /lossless` command is unavailable because `plugins.allow` excludes "/lossless". Add "/lossless" to `plugins.allow` if you want that bundled plugin CLI surface.
```

### Step 2
Add `"/lossless"` and optionally `"/lcm"` to `plugins.allow`.

### Actual result
Config validation warns:

```text
Config warnings:
- plugins.allow: plugin not found: /lossless (stale config entry ignored; remove it from plugins config)
- plugins.allow: plugin not found: /lcm (stale config entry ignored; remove it from plugins config)
```

## Expected result
One of these should be true, but not both:

1. `plugins.allow` should accept command ids for bundled plugin command surfaces, and schema/validation should reflect that
2. `plugins.allow` should remain plugin-id-only, and the CLI error should instruct the user to allow the parent plugin id (`lossless-claw`), not the command id (`/lossless`)

### CLI missing-command guidance
In compiled 2026.4.11 code:

`/opt/homebrew/lib/node_modules/openclaw/dist/run-main-3Kd3X1tI.js`

A branch in `resolveMissingPluginCommandMessage(...)` emits:

- if alias owner exists and parent plugin is missing, it correctly says to add the parent plugin id
- otherwise it falls back to:
  - `The \`openclaw ${normalizedPluginId}\` command is unavailable because \`plugins.allow\` excludes "${normalizedPluginId}". Add "${normalizedPluginId}" to \`plugins.allow\` ...`

That fallback is incorrect for command ids like `/lossless`.

### Config validation / schema
In compiled 2026.4.11 code:

`/opt/homebrew/lib/node_modules/openclaw/dist/io-B-YPX79V.js`

validation warns:

- `"/lossless" is not a plugin — it is a command provided by the "lossless-claw" plugin. Use "lossless-claw" in plugins.allow instead.`

And schema/help text in:

`/opt/homebrew/lib/node_modules/openclaw/dist/runtime-schema-HP9KKAMz.js`

defines `plugins.allow` as:

- `Optional allowlist of plugin IDs`

## Impact
- bundled command surfaces for installed plugins can become effectively undiscoverable
- operator is given mutually contradictory remediation guidance
- this is especially confusing for diagnostics like `lossless-claw` where the skill/docs refer to `/lossless`

## Notes
- This was observed after updating from 2026.4.10 to 2026.4.11
- The core app updated successfully, but plugin update also emitted a separate npm plugin updater error referencing a missing hashed runtime import during update of `lossless-claw`
- That separate updater issue may or may not be related, but the allowlist contradiction is independently reproducible

## Suggested fix
Most likely fix is in the CLI missing-command guidance path:
- when the missing token resolves to a command alias owned by a plugin, do not ever recommend adding the command token itself to `plugins.allow`
- instead consistently recommend the owning plugin id (`lossless-claw`)
- if the command is runtime-only slash surface, say so explicitly and point to the correct usage surface

## Minimal expected behavior
For `openclaw /lossless`, if `lossless-claw` is already allowed/enabled, the error should not suggest adding `/lossless` to `plugins.allow`.

Either:
- invoke correctly, or
- fail with a non-contradictory message about command-surface availability.

**Comment by mcdeeai** [comment]
Additional datapoint that may be related, though I'm not claiming it is the same root cause:

During the 2026.4.10 -> 2026.4.11 update flow, the lossless-claw plugin update step also emitted an npm/runtime error referencing a missing hashed dist import:

```
ERR_MODULE_NOT_FOUND
Cannot find module /opt/homebrew/lib/node_modules/openclaw/dist/install.runtime-BhCKlLSJ.js
imported by .../install-BObWtgWE.js
```

Afterward, `openclaw --version` still reported `OpenClaw 2026.4.11 (769908e)`, and the installed dist contained different install runtime artifacts such as `install.runtime.js` rather than the missing hashed filename above.

So the core app update appears to have succeeded, but there may also be a packaging/updater inconsistency affecting plugin/update surfaces in this release path. Mentioning in case it helps explain why the lossless command surface behavior is inconsistent across runtime vs config validation.

**Comment by BeliefanX** [comment]
I can still reproduce a closely related variant on OpenClaw `2026.4.12` with `lossless-claw 0.8.2` on macOS arm64.

## What I see

- `openclaw plugins info lossless-claw` shows the plugin is loaded and exposes:
  - `id: lossless-claw`
  - `Commands: lcm`
- `plugins.allow` already includes `"lossless-claw"`
- runtime health looks normal:
  - plugin loads successfully
  - LCM tools work from chat/runtime (`lcm_grep`, `lcm_describe`, `lcm_expand_query`)

But root CLI still fails:

```bash
openclaw lcm --help
```

returns:

```text
[openclaw] Failed to start CLI: Error: The `openclaw lcm` command is unavailable because `plugins.allow` excludes "lcm". Add "lcm" to `plugins.allow` if you want that bundled plugin CLI surface.
```

If I add `"lcm"` to `plugins.allow`, config validation then reports:

```text
plugins.allow: plugin not found: lcm (stale config entry ignored; remove it from plugins config)
```

## Why this still looks like the same class of bug

This is the same contradiction described here, just with the `lcm` root instead of `/lossless`:

- runtime guidance says to allow the command name
- config validation only accepts plugin ids
- plugin info clearly shows the command surface exists
- runtime plugin health is fine, so this does not look like a failed plugin load

## Environment

- OpenClaw: `2026.4.12`
- lossless-claw: `0.8.2`
- OS: macOS arm64
- `plugins.allow` contains `lossless-claw`
- plugin loaded from npm install path under `~/.openclaw/extensions/lossless-claw`

## Additional clue

There is also a current lossless-claw issue about id mismatch:
- `LcmContextEngine.info.id is "lcm" but plugin registers as "lossless-claw"`

That mismatch may be related to why command-name/owner resolution falls back to the wrong allowlist hint.

If useful, I can provide the exact `plugins info` output and config excerpt, but the short version is:
- plugin id = `lossless-claw`
- command surface shown = `lcm`
- root CLI says allow `lcm`
- config validator says `lcm` is not a plugin

**Comment by steipete** [comment]
Maintainer review on current `main` (`38e61e0046`): leaving this open, but it is adjacent to #64732.

Current core has better handling for manifest-declared command aliases: `resolveMissingPluginCommandMessage()` asks `resolveManifestCommandAliasOwner(...)` for the primary command (`src/cli/run-main.ts:120` / `:125`), then points users at the parent plugin ID rather than the command token when the parent plugin is excluded (`src/cli/run-main.ts:126` / `:131`). Runtime slash aliases also get a chat-only message instead of an allowlist suggestion (`src/cli/run-main.ts:141` / `:149`). Config validation likewise warns when a `plugins.allow` entry is a command alias and tells users to use the owning plugin ID (`src/config/validation.ts:1121` / `:1132`).

What I cannot prove from core source alone is whether the affected external `lossless-claw` package exposes `lcm` / `/lossless` through manifest `commandAliases` in the shape current core expects. If it does, this should be fixed by current core. If it does not, the remaining fix may belong in that plugin manifest plus the broader fallback cleanup tracked in #64732.
