### ISSUE TITLE
Beta blocker: core build - 11 workspace packages ship without scripts.build

### ISSUE THREAD

**Issue by fansaner** [openclaw/openclaw#106351]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

Yes

### Summary

After upgrading from v2026.7.1-beta.2 to v2026.7.1-beta.5+, the bundled feishu plugin fails to load with ERR_MODULE_NOT_FOUND on packages/ai/dist/index.mjs, because @openclaw/ai (which replaces llm-runtime) ships without scripts.build so its dist is never produced by pnpm build.

### Steps to reproduce

1. On a checkout of v2026.7.1-beta.6 after `pnpm install && pnpm build` has completed
   successfully (top-level builds; `dist/.buildstamp` exists):

   $ ls -la packages/ai/dist
   ls: cannot access 'packages/ai/dist': No such file or directory

2. From the same checkout:

   $ node --input-type=module \
     -e "import('@openclaw/ai').then(m=>console.log('ok',Object.keys(m).length)).catch(e=>console.log('FAIL',e.message))"
   FAIL Cannot find module '.../packages/ai/dist/index.mjs'

### Expected behavior

On v2026.7.1-beta.2 (the prior known-good version), the gateway runs continuously and the bundled feishu plugin loads successfully — that version uses the `packages/llm-runtime` workspace package, not `@openclaw/ai`. After upgrading to v2026.7.1-beta.6, the same workflow is expected to work: `pnpm install && pnpm build` should produce `packages/ai/dist/index.mjs` (matching the `main: "./dist/index.mjs"` declared in `packages/ai/package.json`), and `import('@openclaw/ai')` should return a positive key list.

### Actual behavior

After `pnpm install && pnpm build` completes without errors on a v2026.7.1-beta.6
checkout:

1. `packages/ai/dist/` does not exist:
   $ ls -la packages/ai/dist
   ls: cannot access 'packages/ai/dist': No such file or directory

2. Direct ESM probe fails:
   $ node --input-type=module \
     -e "import('@openclaw/ai').then(m=>console.log('ok',Object.keys(m).length)).catch(e=>console.log('FAIL',e.message))"
   FAIL Cannot find module '.../packages/ai/dist/index.mjs'

3. The `pnpm install` step does create the workspace symlink correctly:
   $ ls -la node_modules/@openclaw/ai
   lrwxrwxrwx ... node_modules/@openclaw/ai -> ../../packages/ai

4. No build step produces the dist. `packages/ai/package.json` lacks any `scripts`
   field (so `pnpm -r --if-present run build` skips it), and    `grep -E '\bai\b|workspace' scripts/build-all.mjs` returns zero matches (so the
   top-level pipeline doesn't handle this case explicitly either).

Downstream: a fresh v2026.7.1-beta.6 install attempting to start the gateway crashes repeatedly. The watchdog log on the affected host shows 12+
spawn-and-die cycles within minutes (PIDs 11730, 15549, 15875, 16350, 16837,17016, 17267, 18008, 18365, 18505, 18652, 18978, 19274 — all logged as "successfully spawned, then not detected running" by the watchdog before the host is rolled back to v2026.7.1-beta.2. After rollback, the gateway runs continuously (PID 20327 stable for 9+ hours at the time of this report).

### OpenClaw version

2026.7.1-beta.6

### Operating system

Ubuntu 22.04 (build host) / Termux on Android 7 (runtime crash host)

### Install method

git clone + pnpm install + pnpm build

### Model

minimax/MiniMax-M3-highspeed

### Provider / routing chain

openclaw → minimax (no proxy)

### Additional provider/model setup details

N/A — this bug occurs during build-time + plugin load, before any provider/model call.

### Logs

```shell
# Evidence on Termux/Note 5 (OpenClaw-backup = the v2026.7.1-beta.6 install):

# 1. Workspace symlink exists (pnpm install completed):
$ ls -la node_modules/@openclaw/ai
lrwxrwxrwx 1 u0_a188 u0_a188 17 Jul 13 17:26 node_modules/@openclaw/ai -> ../../packages/ai

# 2. Top-level dist/ exists (top-level pnpm build completed):
$ cat dist/.buildstamp
{"builtAt":1783934411824,"head":null}

# 3. But packages/ai/dist/ does NOT exist:
$ ls -la packages/ai/dist
ls: cannot access 'packages/ai/dist': No such file or directory

# 4. Direct ESM probe confirms runtime resolution fails:
$ node --input-type=module \
    -e "import('@openclaw/ai').then(m=>console.log('ok',Object.keys(m).length)).catch(e=>console.log('FAIL',e.message))"
FAIL Cannot find module '.../node_modules/@openclaw/ai/dist/index.mjs'

# 5. scripts/build-all.mjs grep returns zero matches (top-level pipeline gap):
$ grep -cE '\bai\b|workspace' scripts/build-all.mjs
0

# 6. Watchdog log excerpt (notes on the host during beta.6 install attempt):
[Watchdog] OpenClaw 已成功拉起，PID: 11730
[Watchdog] OpenClaw 已成功拉起，PID: 15549
[Watchdog] OpenClaw 已成功拉起，PID: 15875
[Watchdog] OpenClaw 已成功拉起，PID: 16350
[Watchdog] OpenClaw 已成功拉起，PID: 16837
[Watchdog] OpenClaw 已成功拉起，PID: 17016
[Watchdog] OpenClaw 已成功拉起，PID: 17267
[Watchdog] OpenClaw 已成功拉起，PID: 18008
[Watchdog] OpenClaw 已成功拉起，PID: 18365
[Watchdog] OpenClaw 已成功拉起，PID: 18505
[Watchdog] OpenClaw 已成功拉起，PID: 18652
[Watchdog] OpenClaw 已成功拉起，PID: 18978
[Watchdog] OpenClaw 已成功拉起，PID: 19274
[Watchdog] 检测到系统正在升级，拒绝拉起 OpenClaw。
[Watchdog] OpenClaw 已成功拉起，PID: 20327   # post-rollback to v2026.7.1-beta.2

(Each "successfully spawned" PID is followed on the next watchdog cycle by
"未检测到运行中实例" — i.e., the process exited before being detected by
the watchdog's next check. The watchdog's "已成功拉起" message indicates
that OpenClaw was launched, not that it stayed up.)

# 7. No API keys, tokens, or passwords included.
```

### Screenshots, recordings, and evidence

Logs field above contains all command-output evidence. Notable local files
that can be inspected on the affected host:
- ~/storage/shared/noteshare/openclaw-issue-draft.md (full structured writeup)
- ~/.openclaw/openclaw.json.last-good (the post-rollback config snapshot)

### Impact and severity

Affected: Hosts running v2026.7.1-beta.5 or beta.6 (evidence base: one Termux/Android 7
host on beta.6 where the bundled feishu channel was directly observed crashing; other
bundled channels that import @openclaw/ai via the workspace alias were not directly
tested in this report but would likely fail similarly given shared dependency topology).

Severity: High — beta.5 and beta.6 effectively cannot be started (gateway exits
non-zero immediately at startup). No data loss or security implication observed.

Frequency: Always — every start attempt on the affected host (12+ watchdog cycles
recorded, all identical) reproduced the same crash. Not intermittent, not edge-case.

Consequence: This host can only run beta.5 / beta.6 by rolling back; the only
working recovery observed was downgrade to v2026.7.1-beta.2 (gateway then stable
for 9+ hours). Broader user-impact scope across the OpenClaw user base is
NOT_ENOUGH_INFO.

### Additional information

Regression version range:
- Last known good: v2026.7.1-beta.2 (currently running on the affected host,
  stable 9+ hours at the time of this report).
- First known bad: v2026.7.1-beta.5 (per a prior 2026-07-12 attempt; same
  watchdog restart-loop symptom was observed at that time and recorded
  internally — see the "Regression timeline" section of this host's MEMORY.md
  for the prior observation).
- Still affected: v2026.7.1-beta.6 (directly observed in this report — same
  root cause: `packages/ai` lacks `scripts.build`, so `dist/index.mjs` is
  never produced).

Temporary workaround (verified): downgrade to v2026.7.1-beta.2. That version
uses the `packages/llm-runtime` workspace package rather than `@openclaw/ai`,
so it does not depend on the missing dist and is not affected by this gap.

Architecture context: `packages/llm-runtime` was removed in beta.5 and
`packages/ai` (~100 source files) was introduced in its place. This
restructuring is what introduced the missing-dist problem; the release notes
do not call out the `llm-runtime → ai` migration explicitly.
