### ISSUE TITLE
v2026.2.14: Missing @microsoft/agents-hosting module + missing workspace templates

### ISSUE THREAD

**Issue by dortaa** [openclaw/openclaw#17089]
## Bug Report

**Version:** OpenClaw 2026.2.14 (c1feda1)
**Platform:** macOS (Intel, Homebrew install via `/usr/local/Cellar`)
**Previous working version:** 2026.2.6-3

## Description

After upgrading from v2026.2.6-3 to v2026.2.14, two critical issues prevent the agent from starting:

### Issue 1: Missing `@microsoft/agents-hosting` module

The MS Teams provider fails to start:

```
[msteams] resolve failed; using config entries. Error: Cannot find module '@microsoft/agents-hosting'
Require stack:
- /usr/local/Cellar/openclaw-cli/2026.2.14/libexec/lib/node_modules/openclaw/extensions/msteams/src/sdk.ts
[msteams] [default] channel exited: Cannot find module '@microsoft/agents-hosting'
```

### Issue 2: Missing workspace template AGENTS.md

Agent fails to bootstrap:

```
⚠️ Agent failed: Missing workspace template: AGENTS.md
(/usr/local/Cellar/openclaw-cli/2026.2.6-3/libexec/lib/node_modules/openclaw/docs/reference/templates/AGENTS.md).
Ensure docs/reference/templates are packaged.
```

## Steps to Reproduce

1. Have a working OpenClaw v2026.2.6-3 installation with MS Teams channel configured
2. Upgrade via `brew upgrade openclaw-cli` to v2026.2.14
3. Run `openclaw gateway`

## Expected Behavior

Gateway starts normally with MS Teams provider and agent bootstrapping.

## Actual Behavior

- MS Teams channel exits immediately (missing dependency)
- Agent fails to start (missing template file)

## Workaround

**For missing module:**
```bash
cd /usr/local/Cellar/openclaw-cli/2026.2.14/libexec/lib/node_modules/openclaw/
npm install @microsoft/agents-hosting
```

**For missing template:**
```bash
sudo mkdir -p /usr/local/Cellar/openclaw-cli/2026.2.14/libexec/lib/node_modules/openclaw/docs/reference/templates/
echo '# AGENTS.md' | sudo tee /usr/local/Cellar/openclaw-cli/2026.2.14/libexec/lib/node_modules/openclaw/docs/reference/templates/AGENTS.md
```

## Environment

- macOS (Intel)
- Homebrew install (`/usr/local/Cellar/openclaw-cli/`)
- Channels: MS Teams (Bot Framework)
- Previous version: 2026.2.6-3 (ARM64/Homebrew, `/opt/homebrew/`) worked fine

**Comment by dortaa** [comment]
This issue was reported against v2026.2.14. We have since upgraded to v2026.2.19-2 and can confirm the problem no longer occurs on our installation. Safe to close.
