### ISSUE TITLE
[Bug]: Codex plugin fails to load with ERR_REQUIRE_ESM_RACE_CONDITION on fresh Ubuntu 24.04 install (Node 24.18.0)

### ISSUE THREAD

**Issue by FiscapeScott** [openclaw/openclaw#112427]
### Bug type

Behavior bug (incorrect output/state without crash)

### Beta release blocker

No

### Summary

The official Codex plugin fails during initialization with ERR_REQUIRE_ESM_RACE_CONDITION on a fresh Ubuntu 24.04 installation using Node.js v24.18.0, preventing the embedded agent from processing Telegram messages.

### Steps to reproduce

1. Install OpenClaw 2026.7.1 globally via npm on a fresh Ubuntu 24.04 server running Node.js v24.18.0.
2. Configure the Gateway in local mode and install it as a systemd user service.
3. Configure a Telegram bot, pair a Telegram user, and set commands.ownerAllowFrom.
4. Complete OpenAI/Codex device OAuth successfully.
5. Restart the Gateway.
6. Send a Telegram message to the paired bot.
7. Observe that the embedded agent fails before replying and the Gateway logs report ERR_REQUIRE_ESM_RACE_CONDITION while loading the official Codex plugin.

### Expected behavior

After successful Telegram pairing and OpenAI/Codex OAuth, the official Codex plugin should initialize successfully and the embedded agent should process and reply to Telegram messages.

### Actual behavior

The Gateway starts successfully, Telegram pairing succeeds, and OpenAI/Codex OAuth completes successfully. When a Telegram message is received, the embedded agent fails before replying because the official Codex plugin fails during initialization with ERR_REQUIRE_ESM_RACE_CONDITION. The Telegram user receives an error instead of a model response.

### OpenClaw version

2026.7.1-2 (0790d9f)

### Operating system

Ubuntu 24.04 LTS

### Install method

Global npm installation

### Model

openai/gpt-5.5

### Provider / routing chain

OpenClaw Gateway -> OpenAI OAuth (device authorization) -> GPT-5.5

### Additional provider/model setup details

Fresh Ubuntu 24.04 installation on a DigitalOcean droplet. OpenClaw installed globally via npm. Gateway configured in local mode and installed as a systemd user service. Telegram configured with a bot token and paired successfully. OpenAI/Codex device authorization completed successfully using a ChatGPT account. No OpenAI API key was configured. The saved OAuth profile remained valid throughout testing. The issue persisted after rebooting the server, upgrading OpenClaw from 2026.7.1 to 2026.7.1-2, restarting the Gateway, and running openclaw update repair.

### Logs

```shell
2026-07-21T19:51:15 [diagnostic] PluginLoadFailureError: plugin load failed: codex: Error [ERR_REQUIRE_ESM_RACE_CONDITION]: Cannot require() ES Module /usr/lib/node_modules/openclaw/dist/plugin-sdk/number-runtime.js because it is not yet fully loaded.

This may be caused by a race condition if the module is simultaneously dynamically import()-ed via Promise.all().

Embedded agent failed before reply.

2026-07-21T19:51:15 [telegram] final reply failed: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/usr/lib/node_modules/openclaw/dist/kernel-BQumOGdZ.js' imported from /usr/lib/node_modules/openclaw/dist/channel-outbound-B8kl3T7S.js
```

### Screenshots, recordings, and evidence

Evidence attached:

• Telegram conversation showing successful pairing ("OpenClaw access approved") followed by failed message processing.

• Gateway logs showing the Codex plugin failing during initialization with ERR_REQUIRE_ESM_RACE_CONDITION.

• After upgrading from OpenClaw 2026.7.1 to 2026.7.1-2, the same behavior persisted. The gateway continued to report plugin initialization failures and subsequent ERR_MODULE_NOT_FOUND errors when processing Telegram messages.

Additional observations:

- Fresh Ubuntu 24.04 DigitalOcean server.
- Node.js v24.18.0.
- Telegram pairing completed successfully.
- OpenAI/Codex device OAuth completed successfully.
- Gateway configured in local mode and running as a systemd user service.
- Issue reproduced after rebooting the server and restarting the gateway.

[openclaw-gateway-bug.log](https://github.com/user-attachments/files/30244877/openclaw-gateway-bug.log)

### Impact and severity

Affected: Users running the official Codex plugin with OpenClaw on Ubuntu 24.04 using the Telegram channel.

Severity: High. The Gateway starts and Telegram pairing succeeds, but the embedded agent cannot process messages because the Codex plugin fails during initialization.

Frequency: Reproduced consistently after initial installation, Gateway restart, server reboot, and after upgrading from OpenClaw 2026.7.1 to 2026.7.1-2.

Consequence: Users can pair and communicate with the Telegram bot, but the agent fails before generating a reply.

### Additional information

The issue was reproduced on a fresh Ubuntu 24.04 DigitalOcean server using Node.js v24.18.0.

The following troubleshooting steps were completed before filing this report:

- Verified Telegram bot configuration and pairing.
- Verified command owner configuration.
- Successfully completed OpenAI/Codex device OAuth.
- Rebooted the server.
- Restarted the Gateway multiple times.
- Upgraded OpenClaw from 2026.7.1 to 2026.7.1-2.
- Ran the update/repair process.

The behavior remained unchanged after each step.
