### ISSUE TITLE
[Bug]: Gateway startup fails after update to 2026.6.8 — ERR_MODULE_NOT_FOUND for server-chat-DVXWYmKw.js (regression of #72042)

### ISSUE THREAD

**Issue by dbernaltbn** [openclaw/openclaw#94570]
## Summary

After upgrading from **2026.4.27** to **2026.6.8**, the Gateway crashes immediately on startup with `ERR_MODULE_NOT_FOUND`. A critical file is missing from the npm tarball — the same pattern as issue #72042 (2026.4.24).

The only workaround is reverting to 2026.4.27.

## Steps to reproduce

1. `npm install -g openclaw@latest` (2026.6.8)
2. `openclaw gateway restart`

## Expected

Gateway starts normally.

## Actual

Gateway crashes with an unhandled rejection:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module
'/home/david/.npm-global/lib/node_modules/openclaw/dist/server-chat-DVXWYmKw.js'
imported from
/home/david/.npm-global/lib/node_modules/openclaw/dist/server-runtime-subscriptions-CxKq-Z61.js
```

## Environment

- **Platform:** WSL2 on Windows 11 (x86_64)
- **Kernel:** 6.6.87.2-microsoft-standard-WSL2
- **Node.js:** v24.15.0
- **npm:** 11.12.1
- **Install path:** `~/.npm-global/lib/node_modules/openclaw`

## Analysis

The 2026.4.27 `dist/` contains 2864 files including `server-chat-BHbejvgn.js`. After upgrading to 2026.6.8, the import hash changed to `server-chat-DVXWYmKw.js` but the corresponding file is not present in the installed package — suggesting files are missing from the npm tarball or stripped during postinstall.

This looks like the same root cause as #72042 (2026.4.24), where 1617 files were silently deleted during postinstall.

## Crash dumps

Available in `~/.openclaw/logs/stability/`:
- `openclaw-stability-2026-06-18T11-46-55-146Z-2620-unhandled_rejection.json` (45KB)
- `openclaw-stability-2026-06-18T11-59-25-309Z-14421-unhandled_rejection.json` (14KB)

Can upload on request.

## Workaround

`npm install -g openclaw@2026.4.27` → Gateway starts normally.

---

cc @steipete (based on previous similar fix for #72042)
