### ISSUE TITLE
[Feature]: Incremental transcript index reconcile for append-lagging sessions after imports

### ISSUE THREAD

**Issue by lsr911** [openclaw/openclaw#134113]
## Summary

Incremental transcript index reconcile for sessions that are only append-lagging behind their watermark, instead of a full delete-and-reinsert rebuild of the whole session.

## Problem to solve

`listSessionsNeedingTranscriptIndexReconcile` flags sessions under three conditions, and all of them currently funnel into the same full rebuild path in `rebuildSessionTranscriptIndexInTransaction` (`src/config/sessions/session-transcript-index.ts`): drop every FTS row and every active-event row for the session, then reinsert the complete resolved active branch via `visitSessionTranscriptProjection` — all inside one write transaction.

One of the trigger conditions is pure append lag (`latest.seq > coalesce(st.indexed_seq, -1)`), which is the normal state right after upgrades or `doctor` imports: an existing store gains transcript rows without index state for many sessions at once. For a large store with hundreds of sessions and thousands of events per session, the reconcile pass therefore performs an O(session length) delete-plus-reinsert per lagging session under a single write transaction, stretching write-lock hold time and delaying unrelated sessions' writes. The cost scales with session length instead of the number of rows actually missing from the index.

The data needed to avoid this is already persisted: `session_transcript_index_state` tracks `indexed_seq` (see #133403), but the rebuild path never uses it as a resume point.

## Proposed solution

Keep full rebuilds for `needs_rebuild` (branch-switch) sessions, and add an incremental path for append-lagging sessions that have a valid watermark:

- Thread an optional `fromSeq` (resume point) into `visitSessionTranscriptProjection` (`src/config/sessions/session-transcript-projection-rebuild.ts`) so the visit starts after `indexed_seq`.
- For the incremental path, insert only rows with `seq > indexed_seq` using the existing `createFtsInserter` / `createActiveEventInserter` factories instead of delete-all plus reinsert.
- Keep the watermark write semantics unchanged: the incremental pass ends with the same `indexed_seq` / `leafEventId` update the append path produces today.

No schema, index-definition, retention, configuration, or persistence-semantic change.

## Alternatives considered

- Lowering `SYNC_REBUILD_MAX_ROWS` so more sessions index synchronously on append: this changes existing behavior boundaries and does nothing for stores that are already behind after an import.
- Chunking the rebuild across transactions from a background worker: introduces crash-recovery semantics of its own, while resuming from the persisted `indexed_seq` watermark is already crash-safe by construction.

## Impact

- Affected: long-lived stores running upgrades or `doctor` imports, and any multi-agent gateway whose reconcile pass runs while other sessions write.
- Severity: medium — no data loss, but import/reconcile time and write-lock hold time grow with session length rather than lagging row count.
- Frequency: every upgrade/doctor import that backfills index state; reconcile passes are periodic.
- Consequence: imports that scale super-linearly with store size, and write latency spikes on unrelated sessions during rebuild transactions.

## Evidence/examples

- Trigger conditions in `listSessionsNeedingTranscriptIndexReconcile` include pure append lag (`latest.seq > coalesce(st.indexed_seq, -1)`) — `src/config/sessions/session-transcript-index.ts`.
- `reconcileSessionTranscriptIndexInTransaction` routes every flagged session, including append-lagging ones, into `rebuildSessionTranscriptIndexInTransaction`, which unconditionally deletes all FTS/active rows and reinserts the full branch.
- `visitSessionTranscriptProjection` (`src/config/sessions/session-transcript-projection-rebuild.ts`) visits the complete event set with no seq start point today.
- This is the natural next step on the existing import-path performance line: #133403 (direct watermark updates), #133742 (importer streaming), #133802 (batch-prepared index inserts).

## Non-goals

- No schema, index-definition, retention, or configuration changes.
- No change to full rebuilds for `needs_rebuild` (branch-switch) sessions — those must stay exact.
- No change to the synchronous append indexing path introduced in #133802.
- No new public API surface.

## Compatibility and risk

The incremental path applies only to sessions with a valid watermark and no `needs_rebuild` flag; anything ambiguous falls back to the existing full rebuild. Worst case is equivalent to today's behavior. FTS and active-event inserts reuse the same factories the append path uses, so row shapes and ordering stay identical.

cc @steipete as owner of the importer/indexing line.

I plan to implement this myself.

**Comment by VACInc** [comment]
Related consumer change merged in #142453: delivery-mirror comparison now uses the active-event projection and waits for pending projection reconciliation before entering the guarded append.

The PR does not implement incremental reconciliation or change the full-rebuild algorithm described here. Its latest-message lookup improvement must not be interpreted as a bound on stale-projection rebuild work. Keep this feature request open; reconciliation remains a separate scope.
