### ISSUE TITLE
tsgo: Slack monitor event tests fail after test dedupe (dmPolicy type mismatch)

### ISSUE THREAD

**Issue by tonydehnke** [openclaw/openclaw#31441]
## Bug

`pnpm tsgo` (and `pnpm check`) fails on `main` after commit 45888276a ("test(integration): dedupe messaging, secrets, and plugin test suites").

Four Slack monitor event test files have `dmPolicy: string` in their test case arrays, but the types now expect the literal union `"allowlist" | "disabled" | "open" | "pairing" | undefined`.

## Errors

```
src/slack/monitor/events/members.test.ts(116,25): error TS2345
src/slack/monitor/events/messages.test.ts(134,26): error TS2345
src/slack/monitor/events/pins.test.ts(113,12): error TS2345
src/slack/monitor/events/reactions.test.ts(133,31): error TS2345
```

All share the same root cause:
```
Type 'string' is not assignable to type '"allowlist" | "disabled" | "open" | "pairing" | undefined'.
```

## Reproducing

```bash
git checkout main
pnpm tsgo  # or pnpm check
```

## Impact

- CI `check` job fails on all open PRs that touch non-docs files
- Not caught on `main` because recent pushes are docs-only (docs-scoped CI skips `tsgo`)

## Fix

The test case arrays likely need `as const` assertions or explicit type annotations on the `dmPolicy` values so TypeScript narrows them from `string` to the literal union.

## Introduced by

45888276a (2026-03-02)
