### PR TITLE
fix: restore plugin-sdk/feishu compatibility facade

### LINKED ISSUE #74138: [Bug]: feishu  createScopedPairingAccess
### Bug type

Regression (worked before, now fails)

### Beta release blocker

Yes

### Summary

After upgrade to latest version, my feishu channel broken.My message can be processed.even if revert the change of the channel config

### Steps to reproduce

1.upgrade to latest version
2.config multi accounts

### Expected behavior

can works well

### Actual behavior

The log as below:

------------

14:05:15
info
[info]: [ '[ws]', 'ws client ready' ]
[info]: [ '[ws]', 'ws client ready' ]
14:06:13
info
gateway/ws
[93m⇄[39m [1mres[22m [92m✓[39m [1mconfig.openFile[22m [2m78ms[22m [2mconn[22m=[90m79c5422b…0f76[39m [2mid[22m=[90meaa1d169…1d4e[39m
14:07:10
info
gateway/channels/feishu
feishu[default]: received message from ou_1d6652c4fd501068d66c18cb2c8137ca in oc_cba239e67811408d32e4a89aeacf075b (p2p)
14:07:10
error
gateway/channels/feishu
feishu[default]: failed to dispatch message: TypeError: (0 , _feishu.createScopedPairingAccess) is not a function

### OpenClaw version

2026.4.26

### Operating system

macOS 15.3.1

### Install method

npm 

### Model

qwen3.6-plus

### Provider / routing chain

bailian

### Additional provider/model setup details

_No response_

### Logs, screenshots, and evidence

```shell

```

### Impact and severity

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yfge**
## Background

Fixes a Feishu/Lark regression reported in #74138 where older channel packages still importing `openclaw/plugin-sdk/feishu` hit `TypeError: createScopedPairingAccess is not a function` after upgrading OpenClaw.

## Changes

- restore a thin deprecated `openclaw/plugin-sdk/feishu` compatibility facade for pairing helpers used by older Feishu/Lark packages
- wire the facade back into the plugin SDK export map and supported bundled-facade metadata
- document the restored compatibility subpath in the SDK docs
- add a contract test that keeps the Feishu facade importable with the expected pairing exports

## Verification

- `pnpm test src/plugins/contracts/plugin-sdk-subpaths.test.ts src/plugins/contracts/plugin-sdk-package-contract-guardrails.test.ts`
- `pnpm build`
- `pnpm check:changed`

## Impact

- restores upgrade compatibility for older Feishu/Lark channel packages without changing the newer generic channel SDK path
- keeps the compatibility surface explicitly deprecated so new plugins still migrate to generic subpaths

Fixes #74138

### CODE REVIEW

**Comment by stielemans** [comment]
Thanks for the compatibility-facade fix. I checked the current gate status and the PR is blocked only on the required Real behavior proof check:

- `Real behavior proof` fails because the PR body does not include a `Real behavior proof` section with after-fix evidence from a real OpenClaw setup.
- CI/type/lint/security/package-contract checks are otherwise green, and the diff does not introduce a second turn-summary contract (`groupedTurnSummary` remains the canonical backend contract; no `logicalTurnSummary` drift seen in this patch).

Please add after-fix evidence from a real setup to the PR body, for example terminal output/screenshot/logs showing an older Feishu/Lark package can import `openclaw/plugin-sdk/feishu` and access the restored pairing helpers. Unit tests and CI are supplemental but do not satisfy this external-PR gate by themselves.
