### PR TITLE
fix(diagnostics): share event bus and log transport across module bundles

### LINKED ISSUE #13783: diagnostics-otel: sanitize OTLP endpoint URL resolution (avoid false /v1 detection)
## Problem
Current resolver treats any endpoint containing "/v1/" as a fully-qualified OTLP signal URL.
For backends like Opik (`.../api/v1/private/otel`), this prevents appending `/v1/traces|metrics|logs`, so exports go to wrong path. Discovered during testing on https://github.com/openclaw/openclaw/pull/12897 for https://github.com/openclaw/openclaw/issues/3201.

## Current Behavior
- Endpoint: `https://www.comet.com/opik/api/v1/private/otel`
- Resolver sees `/v1/` and returns it unchanged.
- Trace exporter posts to `/api/v1/private/otel` instead of `/api/v1/private/otel/v1/traces`.

## Expected Behavior
Base collector-like endpoints should append signal path:
- `/v1/traces`
- `/v1/metrics`
- `/v1/logs`

Only skip append when endpoint is already signal-specific.

## Proposed Fix
Replace `endpoint.includes("/v1/")` logic with strict path checks:
- if endpoint path ends with `/v1/traces|/v1/metrics|/v1/logs`, keep as-is
- otherwise append requested signal path

Keep trailing slash normalization.
Optionally parse with `new URL()` when valid; fallback to string handling for non-URL inputs.

### LINKED ISSUE #18794: diagnostics-otel loads but does not emit OTLP traffic to configured endpoint
## Summary
`diagnostics-otel` loads successfully, but OpenClaw does not emit any OTLP traffic to the configured endpoint.

Environment date: **February 17, 2026**
OpenClaw version: **2026.2.15**
Host: Linux (user service)

## What I configured
1. Enabled plugin:
```bash
openclaw plugins enable diagnostics-otel
```
2. Configured diagnostics:
```json
"diagnostics": {
  "enabled": true,
  "otel": {
    "enabled": true,
    "endpoint": "http://localhost:4318",
    "serviceName": "openclaw-gateway",
    "traces": true,
    "metrics": true,
    "logs": true
  }
}
```
3. Started local OTLP HTTP collector on `:4318`.

## Initial issue and fix
Initially plugin failed with:
`Cannot find module '@opentelemetry/api'`

Installed required `@opentelemetry/*` packages in OpenClaw runtime and restarted gateway. After that, plugin status became `loaded`.

## Evidence after plugin is loaded
- `openclaw plugins info diagnostics-otel` -> `Status: loaded`
- Gateway logs show:
  - `diagnostics-otel: logs exporter enabled (OTLP/HTTP)`
  - many diagnostic events during agent runs (`lane enqueue/dequeue`, `run start/done`, heartbeat, etc.)
- Collector is listening on `0.0.0.0:4318`

## Expected
When diagnostic events occur, OpenClaw should send OTLP HTTP data to `http://localhost:4318`.

## Actual
No outgoing TCP activity from OpenClaw to port `4318` during multiple agent runs.

Repro check used:
```bash
ss -tn '( sport = :4318 or dport = :4318 )'
```
Observed result during runs: no `ESTAB`/no traffic.

Collector logs show startup only, with no received traces/metrics/logs.

## Reproduction
```bash
openclaw plugins enable diagnostics-otel
# set diagnostics.otel.enabled=true endpoint=http://localhost:4318
openclaw gateway restart
openclaw agent --channel telegram --session-id otel-test --message "health ping" --timeout 60
```

## Notes
- This might be a plugin/runtime wiring issue where diagnostics events are logged but not exported.
- Please let me know if there is an additional config key required beyond `diagnostics.otel.*`.

### PR DESCRIPTION
**Pull request by triclambert**
## Summary

- **Problem:** The `diagnostics-otel` extension ships with every install but has never actually worked. Three bugs stack on top of each other to prevent any telemetry from reaching a collector.
- **Why it matters:** Users configuring OTel get no errors but also no data. There are multiple open issues:  
  - #5190
  - #18794
  - #13783
- **What changed:** (1) Diagnostic event bus and log transport registry now use `globalThis[Symbol.for()]` singletons so plugin bundles share state with core. (2) `resolveOtelUrl()` uses `endsWith` against OTLP signal suffixes instead of `includes("/v1/")`.
- **What did NOT change:** No new dependencies, no config schema changes, no new diagnostic event types. The OTel plugin's metrics/spans/logs handling is untouched.

## Change Type (select all)

- [x] Bug fix
- [ ] Feature
- [ ] Refactor
- [ ] Docs
- [ ] Security hardening
- [ ] Chore/infra

## Scope (select all touched areas)

- [x] Gateway / orchestration
- [ ] Skills / tool execution
- [ ] Auth / tokens
- [ ] Memory / storage
- [x] Integrations
- [ ] API / contracts
- [ ] UI / DX
- [ ] CI/CD / infra

## Linked Issue/PR

- Closes #5190
- Closes #18794
- Closes #13783
- Related #11168, #16865, #12475, #12897, #13791

## User-visible / Behavior Changes

Users who configure `diagnostics.otel.enabled: true` with an OTLP endpoint will now actually receive traces, metrics, and logs in their collector. Previously this configuration was silently non-functional.

## Security Impact (required)

- New permissions/capabilities? `No`
- Secrets/tokens handling changed? `No`
- New/changed network calls? `No` (the OTel plugin already makes OTLP calls when enabled -- they just never fired due to the event bus bug)
- Command/tool execution surface changed? `No`
- Data access scope changed? `No`

### Environment

- OS: macOS (Darwin arm64)
- Runtime: Node v25.6.1
- Integration: diagnostics-otel extension + Jaeger OTLP collector

### Steps

1. Start Jaeger: `docker run -d -p 127.0.0.1:4318:4318 -p 127.0.0.1:16686:16686 jaegertracing/all-in-one:latest`
2. Configure OpenClaw with `diagnostics.enabled: true`, `diagnostics.otel.enabled: true`, `diagnostics.otel.endpoint: http://127.0.0.1:4318`
3. Emit diagnostic events (via gateway activity or test script)

### Expected

Traces appear in Jaeger at http://localhost:16686

### Actual

Before fix: zero traces (confirmed via `ss -tn`, matching #18794 repro).
After fix: 3 traces with 3 spans appear in Jaeger.

## Evidence

- [x] Failing test/log before + passing after
- [x] Trace/log snippets

Unit tests: 18/18 pass (5 new tests added covering the exact bug scenarios).

Integration test output:
```
OTel service started, emitting test events...
Events emitted. Waiting for OTel batch flush...
OTel service stopped.
SUCCESS: Found 3 trace(s) with 3 span(s) in Jaeger.
```

URL resolution test covers the #13783 case directly:
```
"appends signal path when endpoint contains /v1/ in a non-terminal position"
  https://api.example.com/api/v1/private/otel -> .../api/v1/private/otel/v1/traces
```

## Human Verification (required)

- Verified scenarios: Event bus isolation fix confirmed with live Jaeger collector. URL resolution fix confirmed with Opik-style endpoint containing `/v1/` in base path.
- Edge cases checked: Endpoint already ending in `/v1/traces` (no double-append), `resetDiagnosticEventsForTest()` correctly clears shared state, unsubscribe removes only the target listener.
- What I did **not** verify: gRPC protocol (intentionally unsupported), concurrent multi-process scenarios (Vitest workers are isolated).

## Compatibility / Migration

- Backward compatible? `Yes`
- Config/env changes? `No`
- Migration needed? `No`

## Failure Recovery (if this breaks)

- How to disable/revert this change quickly: Revert this single commit. The `globalThis` singletons degrade gracefully -- if removed, behavior returns to the pre-fix state (events don't cross module boundaries, but nothing crashes).
- Files/config to restore: `src/infra/diagnostic-events.ts`, `src/logging/logger.ts`, `extensions/diagnostics-otel/src/service.ts`
- Known bad symptoms reviewers should watch for: If `globalThis` symbols collide with another library (extremely unlikely with `openclaw.` prefix), diagnostic events could leak to unintended listeners.

## Risks and Mitigations

- Risk: `globalThis` shared state could cause test interference if tests in the same Vitest worker share the bus.
  - Mitigation: `resetDiagnosticEventsForTest()` already exists for this purpose and now clears the shared bus. Existing tests already call it in `beforeEach`. New test added to verify this works.

---

**AI disclosure:** This PR was developed with AI assistance (Claude). All changes were manually reviewed, understood, and verified with live integration testing against Jaeger.

<h3>Greptile Summary</h3>

This PR fixes three stacked bugs that prevented the `diagnostics-otel` extension from ever delivering telemetry to a collector:

1. **Event bus isolation** (`diagnostic-events.ts`): The diagnostic event bus (listeners + sequence counter) was module-scoped, so plugin bundles that received a separate copy of the module had their own isolated bus. Events emitted by core never reached plugin listeners. Fixed by storing the bus on `globalThis` via `Symbol.for("openclaw.diagnosticEventBus")`, following the established pattern in `src/plugins/runtime.ts`.

2. **Log transport isolation** (`logger.ts`): Same module-boundary problem for the log transport registry. Fixed with the same `globalThis` + `Symbol.for()` singleton pattern.

3. **URL resolution false positive** (`service.ts`): `resolveOtelUrl()` used `includes("/v1/")` to detect fully-qualified OTLP endpoints, which incorrectly matched backends whose base URL contained `/v1/` (e.g. Opik, Fiddler). Fixed by checking `endsWith` against the three known OTLP signal suffixes (`/v1/traces`, `/v1/metrics`, `/v1/logs`).

- No new dependencies, no config schema changes, no new diagnostic event types
- 5 new tests covering the exact bug scenarios, 18/18 tests passing
- The `globalThis` singleton pattern is well-established in this codebase (used by `plugins/runtime.ts`, `warning-filter.ts`, `fetch.ts`, etc.)

<h3>Confidence Score: 5/5</h3>

- This PR is safe to merge — well-scoped bug fixes using established patterns with thorough test coverage.
- All three changes are minimal and targeted: two apply an existing globalThis singleton pattern (already used in plugins/runtime.ts) to fix module-boundary isolation, and one narrows a string check from includes() to endsWith(). No new dependencies, no config changes, no behavioral changes for users who don't have OTel enabled. Five new tests cover the exact bug scenarios. The patterns are well-established in the codebase.
- No files require special attention.

<sub>Last reviewed commit: 1fda875</sub>

<sub>(2/5) Greptile learns from your feedback when you react with thumbs up/down!</sub>

**Context used:**

- Context from `dashboard` - CLAUDE.md ([source](https://app.greptile.com/review/custom-context?memory=fd949e91-5c3a-4ab5-90a1-cbe184fd6ce8))
- Context from `dashboard` - AGENTS.md ([source](https://app.greptile.com/review/custom-context?memory=0d0c8278-ef8e-4d6c-ab21-f5527e322f13))

### CODE REVIEW

**Comment by triclambert** [comment]
The `check` CI failure is a pre-existing type error on `main` (not from this PR):

```
src/test-utils/model-auth-mock.ts(3,17): error TS2742: The inferred type of
'createModelAuthMockModule' cannot be named without a reference to
'.pnpm/@vitest+spy@4.0.18/node_modules/@vitest/spy'.
```

Introduced by ff50d3303 (`test(memory): dedupe model-auth mock setup`). This PR does not touch that file. Will rebase once `main` is green.
