### ISSUE TITLE
[Bug]:  4.29 runtime-deps missing grammy, @grammyjs/runner, @grammyjs/transformer-throttler — Telegram channel fails to load

### ISSUE THREAD

**Issue by fenglanhua** [openclaw/openclaw#75320]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

After upgrading to 4.29, the Telegram channel fails to load due to missing grammy runtime dependencies. Manually installing into the runtime-deps directory restores Telegram functionality.
Error
[channels] failed to load bundled channel telegram: Cannot find module 'grammy'
Require stack:
- /home/michael/.nvm/versions/node/v24.14.1/lib/node_modules/openclaw/dist/extensions/telegram/send-t4GTTdHF.js

### Steps to reproduce

openclaw update from 4.23 to 4.29
Restart gateway
Observe [channels] failed to load bundled channel telegram: Cannot find module 'grammy'
Workaround
bashcd ~/.openclaw/plugin-runtime-deps/openclaw-2026.4.29-*/
pnpm install grammy @grammyjs/runner @grammyjs/transformer-throttler
After gateway restart, Telegram loads normally.
Note
Similar to #74883 (4.27 missing chokidar/sqlite-vec). This appears to be a recurring runtime-deps packaging issue across releases.

### Expected behavior

After upgrading to 4.29, Telegram channel should load normally without manual intervention. grammy and related dependencies should be present in the runtime-deps directory.

### Actual behavior

Telegram channel fails to load with Cannot find module 'grammy'. Manual pnpm install into runtime-deps directory is required to restore functionality.

### OpenClaw version

 2026.4.29 (a448042)

### Operating system

 Rocky Linux   node 24.14.1

### Model

N/A — plugin packaging issue, not model-related

### Provider / routing chain

N/A — plugin packaging issue, not provider-related

### Logs, screenshots, and evidence

```shell

```
