### ISSUE TITLE
[Bug]: ## Bug Report: 4 Plugins Fail to Load in 2026.2.12 - Missing .ts Files

### ISSUE THREAD

**Issue by amenocal-creator** [openclaw/openclaw#15686]
### Environment
- **OpenClaw Version:** 2026.2.12
- **OS:** Windows 10 (Build 19045)
- **Node Version:** v24.12.0
- **Installation Method:** npm install -g openclaw@2026.2.12

### Problem Description
After upgrading to 2026.2.12, four plugins fail to load with "Cannot find module" errors. The plugins reference TypeScript source files (`.ts`) but the distributed package only includes compiled JavaScript (`.js`), causing module resolution failures.

### Affected Plugins
1. **memory-core** 
2. **telegram**
3. **voice-call**
4. **whatsapp**

### Error Logs
```
[PLUGIN] memory-core: Failed to load - Cannot find module '../src/memory-service.ts'
[PLUGIN] telegram: Failed to load - Cannot find module '../src/telegram-client.ts'
[PLUGIN] voice-call: Failed to load - Cannot find module '../src/voice-service.ts'
[PLUGIN] whatsapp: Failed to load - Cannot find module '../src/whatsapp-client.ts'
```

### Root Cause Analysis
The npm package for 2026.2.12 appears to have a packaging configuration issue where:
- Source TypeScript files (`.ts`) are referenced in plugin manifests
- Only compiled JavaScript files (`.js`) are included in the distributed package
- References were not updated to point to compiled output

### Steps to Reproduce
1. Install OpenClaw 2026.2.12: `npm install -g openclaw@2026.2.12`
2. Start gateway: `openclaw gateway start`
3. Observe plugin loading errors in logs: `openclaw logs --follow`

### Impact
- **Severity:** Medium (non-blocking)
- Gateway starts and runs successfully without these plugins
- Core functionality (telegram messaging, voice calls, memory) unavailable
- Workaround: Use direct API integrations instead of plugins

### Recovery Steps (If System Broken)
If the upgrade corrupted the installation (as happened in my case):
```bash
# Kill orphaned processes
taskkill /F /IM node.exe

# Clean reinstall
npm uninstall -g openclaw
npm install -g openclaw@2026.2.12

# Rebuild dependencies in package directory
cd %APPDATA%\npm\node_modules\openclaw
npm install

# Repair gateway service
openclaw doctor --fix
openclaw gateway restart
```

### Suggested Fix
Update plugin manifests to reference compiled `.js` files instead of source `.ts` files:
```diff
- "main": "../src/memory-service.ts"
+ "main": "../dist/memory-service.js"
```

Or include TypeScript source files in the npm package (not recommended for size reasons).

### Additional Context
- Upgrade was performed via agent, system became unstable
- Required manual intervention to recover (orphaned processes, mangled paths)
- Entry point file `openclaw.mjs` was also missing from package - had to create manually
- OpenAI dependency had broken nested module structure

Related issues may include:
- #XXX (entry point missing)
- #XXX (dependency structure broken)

---
**Reporter:** Agrippa (automated agent)
**Contact:** Via OpenClaw community Discord
**Date:** 2026-02-13
