### ISSUE TITLE
[Bug]: esbuild binary incompatible with macOS 10.15 Catalina (macOS 12.0+ required) since ~2026.3.8

### ISSUE THREAD

**Issue by alex-espinoza** [openclaw/openclaw#58595]
### Bug type

Regression (worked before, now fails)

### Beta release blocker

No

### Summary

OpenClaw versions after 2026.3.8 fail to start on macOS 10.15.7 (Catalina) due to an esbuild binary that requires macOS 12.0+. The Discord plugin fails to load with Cannot find module '@buape/carbon', and any attempt to install missing dependencies also fails with the same dyld error.

**Error**
```
dyld: Symbol not found: _SecTrustCopyCertificateChain
Referenced from: .../openclaw/node_modules/esbuild/bin/esbuild (which was built for Mac OS X 12.0)
Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
```

**Workaround**
Pinning to 2026.3.8 restores functionality. The regression appears to have been introduced by an esbuild upgrade somewhere between 2026.3.8 and 2026.3.24.

**Environment**
- OpenClaw: 2026.3.28 (latest)
- Last working version: 2026.3.8
- macOS: 10.15.7 Catalina
- Node.js: v22.22.0
- Hardware: MacBook Air

### Steps to reproduce

**Steps to reproduce**
1. macOS 10.15.7 Catalina
2. Node.js v22.22.0 via nvm
3. `npm i -g openclaw@latest` (2026.3.24+)
4. `openclaw gateway` — Discord plugin fails, Internal Server Error on any API call

### Expected behavior

**Expected behavior**
OC should work on macOS 10.15 Catalina, or clearly document the minimum macOS version requirement.

### Actual behavior

**Error**
```
dyld: Symbol not found: _SecTrustCopyCertificateChain
Referenced from: .../openclaw/node_modules/esbuild/bin/esbuild (which was built for Mac OS X 12.0)
Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
```

### OpenClaw version

2026.3.24

### Operating system

macOS 10.15.7 Catalina

### Install method

npm i -g openclaw@latest

### Model

any

### Provider / routing chain

openclaw

### Logs, screenshots, and evidence

```shell

```

**Comment by junteng-li** [comment]
I used macOS 10.15.7 (Catalina) before and encountered a similar problem. I upgraded my system to 11.7.11. Versions of OpenClaw prior to 3.28 run normally. I recommend installing Node.js version 22 from the official website, and only installing one Node.js version. Do not use NVM.
