### ISSUE TITLE
[Bug]: Cannot find module diagnostic-session-state-CDEk5vOn.js after updating to 2026.3.7 — all tools fail

### ISSUE THREAD

**Issue by jbmx77** [openclaw/openclaw#39586]
## Description

After updating from **2026.3.2 → 2026.3.7**, the gateway starts but all tool calls fail with:

```
Cannot find module '/home/ubuntu/.npm-global/lib/node_modules/openclaw/dist/diagnostic-session-state-CDEk5vOn.js'
imported from /home/ubuntu/.npm-global/lib/node_modules/openclaw/dist/subagent-registry-CkqrXKq4.js
```

This affects every tool: `exec`, `read`, `memory_search`, etc. The gateway process stays up but is completely non-functional.

## Steps to Reproduce

1. `npm install -g openclaw@2026.3.7` (or update via Control UI dashboard)
2. Restart gateway
3. Send any message that triggers a tool call

## Expected Behavior

Tools work normally after update.

## Actual Behavior

All tools fail with `Cannot find module` error. The file `diagnostic-session-state-CDEk5vOn.js` is **not present** in the `dist/` directory of the published package. Reproduced twice with fresh installs on Ubuntu 24.04 / Node 22.

In 2026.3.7: **zero** `diagnostic-session-state-*.js` files exist in dist/.
In 2026.3.2: 6 `diagnostic-session-state-*.js` files present including `CDEk5vOn`.

## Workaround

```bash
npm install -g openclaw@2026.3.2
systemctl --user restart openclaw-gateway.service
```

## Notes

Likely related to the `ContextEngine` plugin refactor (#22201) — internal module references may have been updated in `subagent-registry` but the corresponding file was not included in the published npm package.

**Comment by steipete** [comment]
Closing this as implemented after Codex review.

Current main already contains a targeted fix and regression coverage for the 2026.3.7 published-build chunk failure behind this report, and the reporter later confirmed the bug no longer reproduced on v2026.3.8.

What I checked:

- **Process-global context-engine registry on main:** Current main keeps context-engine registrations on a process-global singleton so split dist chunks share one registry at runtime, which is the relevant fix shape for the 2026.3.7 failure. ([`src/context-engine/registry.ts:320`](https://github.com/openclaw/openclaw/blob/cb2c36b04975/src/context-engine/registry.ts#L320), [cb2c36b04975](https://github.com/openclaw/openclaw/commit/cb2c36b04975))
- **Regression test names the 2026.3.7 failure mode:** The test suite now explicitly documents that published builds may split the context-engine registry across chunks and says these tests cover the invariant that failed in 2026.3.7 when a plugin registered successfully but resolution could not find it. ([`src/context-engine/context-engine.test.ts:1009`](https://github.com/openclaw/openclaw/blob/cb2c36b04975/src/context-engine/context-engine.test.ts#L1009), [cb2c36b04975](https://github.com/openclaw/openclaw/commit/cb2c36b04975))
- **Publish/install guard for broken runtime packaging:** Main now verifies installed packages for missing bundled runtime sidecars and unresolved context-engine runtime loaders during npm postpublish verification, adding a release guard against this class of broken publish. ([`scripts/openclaw-npm-postpublish-verify.ts:107`](https://github.com/openclaw/openclaw/blob/cb2c36b04975/scripts/openclaw-npm-postpublish-verify.ts#L107), [cb2c36b04975](https://github.com/openclaw/openclaw/commit/cb2c36b04975))
- **Dist inventory drift detection:** Main also has package dist inventory validation that fails closed on missing or unexpected packaged dist files, with tests covering missing/stale artifact detection. ([`src/infra/package-dist-inventory.ts:151`](https://github.com/openclaw/openclaw/blob/cb2c36b04975/src/infra/package-dist-inventory.ts#L151), [cb2c36b04975](https://github.com/openclaw/openclaw/commit/cb2c36b04975))
- **Reporter-confirmed resolution on later release:** The issue thread includes a follow-up from the reporter saying the missing-module failure did not reproduce after upgrading to v2026.3.8 and concluding that #39586 appeared resolved on that host/workload.

So I’m closing this as already implemented rather than keeping a duplicate issue open.

Review notes: reviewed against [cb2c36b04975](https://github.com/openclaw/openclaw/commit/cb2c36b04975e34ab7014a11575d6589aa96ae32); fix evidence: commit [cb2c36b04975](https://github.com/openclaw/openclaw/commit/cb2c36b04975e34ab7014a11575d6589aa96ae32).
