### ISSUE TITLE
Native PR merge success tests fail after author verification

### ISSUE THREAD

**Issue by steipete** [openclaw/openclaw#145214]
The native PR merge success tests fail after #145128 added published-commit author verification during squash-body preparation. The shared main-refresh fixture does not implement the new GitHub commit lookup, so valid synthetic merges stop before dispatch.

CI run [34635760951](https://github.com/openclaw/openclaw/actions/runs/34635760951), whose checkout merged the unrelated Node cleanup into main commit `ba8294bd0eaf5a1ae29d7c8526bc5f3515bfeb3f`, failed in:

- [Shard 28](https://github.com/openclaw/openclaw/actions/runs/34635760951/job/103383435292): `test/scripts/pr-main-refresh.test.ts`, “completes supervised merge with two checkpoints and releases its exact lock after cleanup.”
- [Shard 29](https://github.com/openclaw/openclaw/actions/runs/34635760951/job/103383435336): `test/scripts/pr-merge-hosted.test.ts`, “dispatches once with the exact prepared head and ordinary server enforcement.”

Both report `Unexpected GitHub API endpoint repos/fixture/repo/commits/<SHA>`. The fixture remains unchanged on main `8b343fce338da60722778eb2e25acdb936c88b40`; running the two existing test files there reproduces exactly those two failures with 64 passing cases.

Update the shared fixture to provide the published-commit author and GraphQL PR author responses consumed by the existing squash-body path. Keep the production wrapper and current merge, cleanup, and refusal assertions intact.

**Comment by steipete** [comment]
Fixed by #145170 in [03234b50810910cd0075a5a325073f28123d51d3](https://github.com/openclaw/openclaw/commit/03234b50810910cd0075a5a325073f28123d51d3). The shared fixture now provides the missing GraphQL author and raw REST commit-author responses.

Verified the exact landed commit in an isolated checkout with the normal test runner. Both originally failing cases passed:

- `pr-main-refresh.test.ts`: completes supervised merge with two checkpoints and releases its exact lock after cleanup.
- `pr-merge-hosted.test.ts`: dispatches once with the exact prepared head and ordinary server enforcement.

Result: **2 passed**; the other 64 cases were unselected by the explicit name filter.

The redundant repair PR #145216 is superseded by that landed fix.
