### ISSUE TITLE
Extensions fail to load after Docker build: send-deps.ts missing from runtime image

### ISSUE THREAD

**Issue by domlen** [openclaw/openclaw#47260]
### Bug type

Regression (worked before, now fails)

### Summary

After building the Docker image from source, both Discord bots fail to load with `Error: Cannot find module '/app/src/infra/outbound/send-deps.js'` because the Dockerfile omits the `src/` directory from the runtime image.

### Steps to reproduce

1. Clone repo at v2026.3.13-1
2. `docker build -t openclaw:local .`
3. Start container with Discord channel configured
4. Observe bot fails to load with missing module error

### Expected behavior

Both Discord bots load successfully without module resolution errors after a Docker build.

### Actual behavior

Both Discord bots fail to load with:

```
Error: Cannot find module '/app/src/infra/outbound/send-deps.js'
```

Commit d9c285e93 (Mar 14) refactored `resolveOutboundSendDep` into `src/infra/outbound/send-deps.ts` and updated all channel extensions to import from it. The extensions are loaded at runtime via `tsx` and reference `../../../src/infra/outbound/send-deps.js` — but the Dockerfile only copies `dist/` into the runtime image. The `src/` directory is never included, so the import resolves to a missing file.

### OpenClaw version

2026.3.13-1

### Operating system

Docker (Linux, x86_64)

### Install method

Docker (built from source)

### Model

N/A (bug occurs before model interaction)

### Provider / routing chain

N/A (bug occurs before model interaction)

### Config file / key location

N/A

### Additional provider/model setup details

**Proposed Fix:**

Add a targeted COPY line to the Dockerfile after the dist copy stage:

```dockerfile
COPY --from=runtime-assets --chown=node:node /app/src/infra/outbound/send-deps.ts ./src/infra/outbound/send-deps.ts
```

### Logs, screenshots, and evidence

```shell

```

### Impact and severity

Affected: All users running Docker-built images with Discord channel configured
Severity: High (blocks workflow — both Discord bots fail to load entirely)
Frequency: 100% repro on v2026.3.13-1 Docker build
Consequence: Discord channel is completely non-functional after Docker build from source

### Additional information

First known bad version: 2026.3.13-1 (introduced by commit d9c285e93, Mar 14)

The regression was introduced when `resolveOutboundSendDep` was refactored into `src/infra/outbound/send-deps.ts`. This file is needed at runtime but the Dockerfile does not copy the `src/` directory into the runtime image.

**Comment by steipete** [comment]
Closing this as implemented after Codex review.

Current `main` no longer relies on `/app/src/infra/outbound/send-deps.js` in packaged Docker installs. Bundled plugin discovery now prefers compiled `dist/extensions` artifacts in installed/package roots, bundled channel sources import `resolveOutboundSendDep` through the public plugin SDK runtime seam, and regression tests guard against falling back to legacy `src/.../send-deps` imports.

What I checked:

- **Bundled plugin discovery prefers built artifacts in installed packages:** `resolveBundledPluginsDir()` returns `dist-runtime/extensions` or `dist/extensions` before source `extensions/` outside source-checkout flows, so packaged/Docker installs do not need `/app/src/**` available at runtime. ([`src/plugins/bundled-dir.ts:79`](https://github.com/openclaw/openclaw/blob/68315792677f/src/plugins/bundled-dir.ts#L79), [68315792677f](https://github.com/openclaw/openclaw/commit/68315792677f))
- **Channel catalog follows the same bundled-plugin resolver:** Bundled channel metadata resolution explicitly documents `source extensions/ in dev/test, dist/extensions in published installs, dist-runtime/extensions when paired with dist`. ([`src/channels/bundled-channel-catalog-read.ts:30`](https://github.com/openclaw/openclaw/blob/68315792677f/src/channels/bundled-channel-catalog-read.ts#L30), [68315792677f](https://github.com/openclaw/openclaw/commit/68315792677f))
- **Discord channel now imports outbound send resolution from the public SDK seam:** Current bundled Discord code imports `resolveOutboundSendDep` from `openclaw/plugin-sdk/outbound-runtime`, not from [`../../../src/infra/outbound/send-deps.js`](https://github.com/openclaw/openclaw/blob/68315792677f/../../../src/infra/outbound/send-deps.js). ([`extensions/discord/src/channel.ts:18`](https://github.com/openclaw/openclaw/blob/68315792677f/extensions/discord/src/channel.ts#L18), [68315792677f](https://github.com/openclaw/openclaw/commit/68315792677f))
- **Regression guard forbids legacy core `src/.../send-deps` imports from bundled extensions:** A repo test asserts bundled extension source files must not import `src/infra/outbound/send-deps.*`, which directly covers the reported failure mode. ([`src/channels/plugins/contracts/channel-import-guardrails.test.ts:565`](https://github.com/openclaw/openclaw/blob/68315792677f/src/channels/plugins/contracts/channel-import-guardrails.test.ts#L565), [68315792677f](https://github.com/openclaw/openclaw/commit/68315792677f))
- **Docker/runtime behavior is documented as fixed in a shipped release:** The changelog for `2026.4.7` says: `Docker/plugins: stop forcing bundled plugin discovery to /app/extensions in runtime images so packaged installs use compiled dist/extensions artifacts again and Node 24 containers do not boot through source-only plugin entry paths.`. ([`CHANGELOG.md:1141`](https://github.com/openclaw/openclaw/blob/68315792677f/CHANGELOG.md#L1141), [68315792677f](https://github.com/openclaw/openclaw/commit/68315792677f))
- **Dockerfile has a regression test preventing runtime bundled-plugin path override:** A test asserts the Dockerfile does not set `OPENCLAW_BUNDLED_PLUGINS_DIR` in runtime images, which is consistent with letting installed-package discovery choose compiled `dist/extensions` artifacts. ([`src/dockerfile.test.ts:71`](https://github.com/openclaw/openclaw/blob/68315792677f/src/dockerfile.test.ts#L71), [68315792677f](https://github.com/openclaw/openclaw/commit/68315792677f))

So I’m closing this as already implemented rather than keeping a duplicate issue open.

Review notes: reviewed against [68315792677f](https://github.com/openclaw/openclaw/commit/68315792677f9628d1370d6869366442f1d3ecad); fix evidence: release [v2026.4.7](https://github.com/openclaw/openclaw/releases/tag/v2026.4.7), commit [68315792677f](https://github.com/openclaw/openclaw/commit/68315792677f9628d1370d6869366442f1d3ecad).
