### ISSUE TITLE
@larksuite/openclaw-lark v2026.7.16 incompatible with OpenClaw 2026.9.3: LarkClient.runtime.config.loadConfig is not a function

### ISSUE THREAD

**Issue by alexltl9527** [openclaw/openclaw#144013]
## Problem

After upgrading OpenClaw from an older version to **2026.9.3**, the Feishu/Lark channel stops working with the following error:

```
TypeError: lark_client_1.LarkClient.runtime.config.loadConfig is not a function
```

## Environment

- **OpenClaw version:** 2026.9.3 (1391f7c)
- **Node.js version:** v24.21.0
- **Plugin:** `@larksuite/openclaw-lark` v2026.7.16 (latest on npm)
- **OS:** Linux (Ubuntu/AWS)

## Steps to Reproduce

1. Upgrade OpenClaw to 2026.9.3 (`npm install -g openclaw@latest`)
2. Restart the gateway
3. Send a message from Feishu — the bot fails to handle it

## Error Log

```
[feishu] feishu[danhuang]: error handling message: TypeError: lark_client_1.LarkClient.runtime.config.loadConfig is not a function
```

## Root Cause Analysis

The plugin `@larksuite/openclaw-lark@2026.7.16` calls `LarkClient.runtime.config.loadConfig()` internally (in `lark-client.js` and `monitor.js`). It appears this method was removed or renamed in OpenClaw 2026.9.3 — the new gateway source contains a migration hint mapping `"runtime.config"` → `"config.normalize"`.

## Impact

Feishu/Lark channel is completely non-functional after upgrading to 2026.9.3. The only workaround is to roll back to an older OpenClaw version.

## Request

Please either:
1. Update `@larksuite/openclaw-lark` to be compatible with OpenClaw 2026.9.3, **or**
2. Provide a compatibility shim in OpenClaw 2026.9.3 for the old `loadConfig()` API to avoid breaking existing plugins
