### PR TITLE
Fix clipboard module crash on linux-arm-gnueabihf

### PR DESCRIPTION
**Pull request by spiceoogway**
Fixes #4596

## Problem
The  dependency was missing native bindings for 32-bit ARM Linux (), causing OpenClaw to crash on startup on platforms like Raspberry Pi 3 and earlier devices.

The error occurred when the clipboard module tried to load the missing  package, which doesn't exist in the npm registry.

## Solution
This PR patches the clipboard module to gracefully handle missing native bindings:

1. **Emits a warning** instead of throwing a fatal error when native bindings are unavailable
2. **Provides stub implementations** that throw informative errors when clipboard functions are called
3. **Allows OpenClaw to start and run normally** on unsupported platforms

The patch is applied via pnpm's patch mechanism, which modifies the clipboard module at install time without requiring a fork.

## Technical Details
- Added a pnpm patch for `@mariozechner/clipboard@0.3.0`
- Modified the module's error handling to be non-fatal
- Stub implementations inform users that clipboard operations are unavailable on their platform
- OpenClaw's own clipboard implementation (in `src/infra/clipboard.ts`) uses system commands and is unaffected

## Testing
The patch allows the module to load successfully, and OpenClaw should start without errors on linux-arm-gnueabihf systems. Clipboard operations in the pi-coding-agent will throw informative errors if called, but won't crash the application.

## Related
- Issue: #4596
- Reported by: @shifoc

### CODE REVIEW

**Comment by spiceoogway** [comment]
## Testing Instructions

Rebased onto current `main` — merge conflict resolved. Here's how to test:

### Setup (on your Raspberry Pi / ARM gnueabihf system)

```bash
# Clone the fork with this branch
git clone --branch fix/clipboard-arm-gnueabihf-4596 --depth 1 \
  https://github.com/spiceoogway/openclaw.git /tmp/openclaw-test
cd /tmp/openclaw-test

# Install deps (the pnpm patch will be applied automatically)
pnpm install
```

### 1. Verify the crash is fixed

```bash
# This should start without the "Cannot find module @mariozechner/clipboard-linux-arm-gnueabihf" error
node dist/entry.mjs --help
```

**Expected:** OpenClaw starts normally, no crash. You should see a **warning** like:
```
[clipboard] Clipboard native bindings not available for linux-arm...
```
This warning is intentional — it means the module loaded gracefully instead of crashing.

### 2. Verify clipboard stubs work correctly

```bash
node -e "
  const clip = require('@mariozechner/clipboard');
  try { clip.getText(); } catch(e) { console.log('Stub works:', e.message); }
"
```

**Expected:** Should print something like `Stub works: Clipboard.getText is not available on linux-arm`

### 3. Verify OpenClaw's own clipboard still works

OpenClaw has its own clipboard implementation in `src/infra/clipboard.ts` that uses system commands (`xclip`, `xsel`, `wl-copy`). This should be unaffected:

```bash
# If you have xclip installed:
echo "test" | xclip -selection clipboard
# OpenClaw's clipboard operations should work independently
```

### 4. Regression check on supported platforms (x64/arm64)

On a supported platform (x64 Linux, macOS, etc.), verify the clipboard module still loads normally with its native bindings — no warning should appear, and `getText()`/`setText()` should work as before.

### What to look for
- ✅ No crash on startup
- ✅ Warning message (not error) about clipboard bindings
- ✅ OpenClaw functions normally (gateway starts, chat works)
- ✅ Native clipboard still works on supported platforms
- ❌ Any new errors in logs

cc @shifoc — this is the updated PR with testing steps. Would you be able to test on your Raspberry Pi setup?
